// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, TextInput, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA10_M2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim name="sheetIn" duration={350} style={[s.s0, { paddingBottom: Math.max(32, insets.bottom) }]}>
      <View style={s.s1} />
      <Text style={s.s2}>
        Enter a pallet id
      </Text>
      <TextInput style={s.s3} defaultValue="PLT-44" />
      <Pressable onPress={v.manualAdd} style={s.s4}>
        <Text style={s.s5}>Add</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    position: "absolute",
    right: 0,
  },
  s1: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s2: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s3: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "RobotoMono_500Medium",
    fontSize: 20,
    height: 56,
    marginTop: 14,
    paddingBottom: 0,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 0,
    width: "100%",
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 16,
    width: "100%",
  },
  s5: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
