// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA12_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim name="sheetIn" duration={350} style={[s.s0, { paddingBottom: Math.max(32, insets.bottom) }]}>
      <View style={s.s1} />
      <Svg width={30} height={30} viewBox="0 0 24 24" fill="none" stroke="#B45309" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
        <Circle cx="12" cy="12" r="9" />
        <Path d="M12 7.5V12l3.5 2.2" />
      </Svg>
      <Text style={s.s2}>
        A 30 minute break is due by 12:52
      </Text>
      <Text style={s.s3}>
        Taking it now keeps you inside the rolling 5.5 hour window with 30 minutes to spare.
      </Text>
      <Pressable onPress={v.startBreakNow} style={s.s4}>
        <Text style={s.s5}>Start break now</Text>
      </Pressable>
      <Pressable onPress={v.t_remind} style={s.s6}>
        <Text style={s.s7}>Remind me in 15 minutes</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FEF6E9",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    position: "absolute",
    right: 0,
  },
  s1: {
    backgroundColor: "#EBD9B8",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s2: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
    marginTop: 10,
  },
  s3: {
    color: "#B45309",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#0F1B2A",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 18,
    width: "100%",
  },
  s5: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s6: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "#EBD9B8",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 10,
    width: "100%",
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
