// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, Image, StyleSheet } from 'react-native';
import Svg, { Circle, Path, Rect } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { IMG } from '@/proto/theme/images';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA14_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <Text style={s.s3}>
        Vehicle
      </Text>
      <Pressable onPress={v.pickVehicleRedgum} style={s.s4}>
        <Image source={IMG.primeMover} resizeMode="cover" accessibilityLabel="Kenworth T610" style={s.s5} />
        <View style={s.s6}>
          <Text style={s.s7}>
            1RG4XT
          </Text>
          <Text style={s.s8}>
            Kenworth T610 · Redgum Freightlines
          </Text>
        </View>
        <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
          <Path d="M5 12.5l4.5 4.5L19 7" />
        </Svg>
      </Pressable>
      <Pressable onPress={v.pickVehicleTanker} style={s.s9}>
        <Image source={IMG.tanker} resizeMode="cover" accessibilityLabel="Volvo FH tanker" style={s.s5} />
        <View style={s.s6}>
          <Text style={s.s7}>
            1BF7KQ
          </Text>
          <Text style={s.s8}>
            Volvo FH tanker · Barwon Fuel Haulage
          </Text>
        </View>
      </Pressable>
      <Text style={s.s10}>
        Trailers
      </Text>
      <View style={s.s11}>
        <View style={s.s12}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.75" strokeLinecap="round">
            <Rect x="2.5" y="7" width={15} height={8} rx="1.5" />
            <Circle cx="7" cy="17.5" r="2" />
            <Circle cx="14" cy="17.5" r="2" />
            <Path d="M17.5 11h4" />
          </Svg>
        </View>
        <View style={s.s6}>
          <Text style={s.s13}>
            T-4471
          </Text>
          <Text style={s.s14}>
            Tautliner, coupled
          </Text>
        </View>
        <View style={s.s15}>
          <Text style={s.s16}>Coupled</Text>
        </View>
      </View>
      <View style={s.s17}>
        <View style={s.s18}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="1.75" strokeLinecap="round">
            <Rect x="2.5" y="7" width={15} height={8} rx="1.5" />
            <Circle cx="7" cy="17.5" r="2" />
            <Circle cx="14" cy="17.5" r="2" />
            <Path d="M17.5 11h4" />
          </Svg>
        </View>
        <View style={s.s6}>
          <Text style={s.s19}>
            T-4489
          </Text>
          <Text style={s.s14}>
            Tautliner, in the yard
          </Text>
        </View>
      </View>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "84%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    marginTop: 6,
    minHeight: 64,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s5: {
    borderRadius: 10,
    flexGrow: 0,
    flexShrink: 0,
    height: 52,
    width: 52,
  },
  s6: {
    flex: 1,
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s9: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s10: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    marginTop: 20,
    textTransform: "uppercase",
  },
  s11: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 56,
    paddingBottom: 10,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 10,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 10,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s13: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
  s14: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 999,
    flexDirection: "row",
    height: 24,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s16: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textTransform: "uppercase",
  },
  s17: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    minHeight: 56,
    paddingBottom: 10,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 10,
  },
  s18: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderRadius: 10,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s19: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
});
