// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA14_M5() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <Text style={s.s3}>
        Severity
      </Text>
      <Pressable onPress={v.pickSevMonitor} style={s.s4}>
        <View style={s.s5} />
        <View style={s.s6}>
          <Text style={s.s7}>
            Monitor
          </Text>
          <Text style={s.s8}>
            Note it and keep an eye on it this trip.
          </Text>
        </View>
      </Pressable>
      <Pressable onPress={v.pickSevRepair} style={s.s9}>
        <View style={s.s10} />
        <View style={s.s6}>
          <Text style={s.s7}>
            Repair soon
          </Text>
          <Text style={s.s8}>
            Raises a work order. You can still drive today.
          </Text>
        </View>
      </Pressable>
      <Pressable onPress={v.pickSevStop} style={s.s11}>
        <View style={s.s12} />
        <View style={s.s6}>
          <Text style={s.s7}>
            Do not drive
          </Text>
          <Text style={s.s13}>
            Locks the vehicle immediately and notifies the workshop.
          </Text>
        </View>
      </Pressable>
      <View style={s.s14}>
        <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#DC2626" strokeWidth="1.75" strokeLinecap="round">
          <Circle cx="12" cy="12" r="9" />
          <Path d="M12 7.5v5" />
          <Path d="M12 16.2h.01" />
        </Svg>
        <Text style={s.s15}>
          Do not drive is not reversible from this phone. Only a fitter can clear it.
        </Text>
      </View>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "82%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    marginTop: 6,
    minHeight: 64,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s5: {
    backgroundColor: "#5B6B7F",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 10,
    width: 10,
  },
  s6: {
    flex: 1,
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "left",
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s9: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s10: {
    backgroundColor: "#F59E0B",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 10,
    width: 10,
  },
  s11: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s12: {
    backgroundColor: "#DC2626",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 10,
    width: 10,
  },
  s13: {
    color: "#DC2626",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s14: {
    alignItems: "flex-start",
    backgroundColor: "#FEF2F2",
    borderRadius: 12,
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s15: {
    color: "#991B1B",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
});
