// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA20_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim name="sheetIn" duration={350} style={[s.s0, { paddingBottom: Math.max(32, insets.bottom) }]}>
      <View style={s.s1} />
      <Text style={s.s2}>
        Reading from the vehicle
      </Text>
      <View style={s.s3}>
        <Text style={s.s4}>
          684 210
        </Text>
        <Text style={s.s5}>
          km
        </Text>
      </View>
      <Text style={s.s6}>
        Taken from 1RG4XT at 11:38 over the telematics link. No one can edit this value, only add an override beside it.
      </Text>
      <Pressable onPress={v.dismiss} style={s.s7}>
        <Text style={s.s8}>Accept</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    position: "absolute",
    right: 0,
  },
  s1: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s2: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s3: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  s4: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 32,
    lineHeight: 36,
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s6: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 18,
    width: "100%",
  },
  s8: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
