// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA27_M4() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <Text style={s.s3}>
        Driving for
      </Text>
      <Pressable onPress={v.switchRedgum} style={s.s4}>
        <View style={s.s5}>
          <Text style={s.s6}>RF</Text>
        </View>
        <View style={s.s7}>
          <Text style={s.s8}>
            Redgum Freightlines
          </Text>
          <Text style={s.s9}>
            Laverton VIC · Full time
          </Text>
        </View>
        {v.redgumIsCurrent ? (
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M5 12.5l4.5 4.5L19 7" />
          </Svg>
        ) : null}
      </Pressable>
      <Pressable onPress={v.switchBarwon} style={s.s10}>
        <View style={s.s11}>
          <Text style={s.s12}>BF</Text>
        </View>
        <View style={s.s7}>
          <Text style={s.s8}>
            Barwon Fuel Haulage
          </Text>
          <Text style={s.s9}>
            Corio VIC · Casual
          </Text>
        </View>
        {v.barwonIsCurrent ? (
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M5 12.5l4.5 4.5L19 7" />
          </Svg>
        ) : null}
      </Pressable>
      <Pressable onPress={v.push_A34_M1} style={s.s13}>
        <Text style={s.s14}>My companies</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "82%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
    minHeight: 64,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#0E2033",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s6: {
    color: "#F5A21E",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "left",
  },
  s7: {
    flex: 1,
  },
  s8: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "left",
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s10: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s11: {
    alignItems: "center",
    backgroundColor: "#0EA5A4",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s12: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "left",
  },
  s13: {
    backgroundColor: "transparent",
    borderWidth: 0,
    flexShrink: 0,
    height: 56,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s14: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "left",
  },
});
