// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA27_M3() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <Text style={s.s3}>
        Looking for work
      </Text>
      <Text style={s.s4}>
        Turn this on and operators inside your radius can offer you work. You choose the work types, the days and how far you will travel.
      </Text>
      <View style={s.s5}>
        <View style={s.s6}>
          <View style={s.s7} />
          <Text style={s.s8}>
            <Text style={s.s9}>
              They see
            </Text>
             your first name, your verified file and how far away you are.
          </Text>
        </View>
        <View style={s.s6}>
          <View style={s.s10} />
          <Text style={s.s8}>
            <Text style={s.s9}>
              They do not see
            </Text>
             your address, your phone, your rate history or who else you drive for.
          </Text>
        </View>
        <View style={s.s6}>
          <View style={s.s11} />
          <Text style={s.s8}>
            <Text style={s.s9}>
              An offer you cannot legally take
            </Text>
             is blocked before it reaches you, and the operator is not told which document is short.
          </Text>
        </View>
      </View>
      <Pressable onPress={v.dismiss} style={s.s12}>
        <Text style={s.s13}>Got it</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "82%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s4: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
  },
  s5: {
    flexDirection: "column",
    gap: 14,
    marginTop: 18,
  },
  s6: {
    flexDirection: "row",
    gap: 12,
  },
  s7: {
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 8,
    marginTop: 7,
    width: 8,
  },
  s8: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
  },
  s9: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 22,
  },
  s10: {
    backgroundColor: "#DC2626",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 8,
    marginTop: 7,
    width: 8,
  },
  s11: {
    backgroundColor: "#F5A21E",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 8,
    marginTop: 7,
    width: 8,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#0F1B2A",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 22,
    width: "100%",
  },
  s13: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
