// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA27_M2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <Text style={s.s3}>
        End your shift
      </Text>
      <View style={s.s4}>
        <View style={s.s5}>
          <Text style={s.s6}>
            Worked
          </Text>
          <Text style={s.s7}>
            09 h 46 m
          </Text>
        </View>
        <View style={s.s5}>
          <Text style={s.s6}>
            Jobs
          </Text>
          <Text style={s.s7}>
            3
          </Text>
        </View>
        <View style={s.s5}>
          <Text style={s.s6}>
            Kilometres
          </Text>
          <Text style={s.s7}>
            812
          </Text>
        </View>
        <View style={s.s5}>
          <Text style={s.s6}>
            Break
          </Text>
          <Text style={s.s7}>
            10:52 to 11:22
          </Text>
        </View>
        <View style={s.s8}>
          <Text style={s.s6}>
            Week now
          </Text>
          <Text style={s.s7}>
            41 h 31 m
          </Text>
        </View>
      </View>
      <Pressable onPress={v.confirmClockOff} style={s.s9}>
        <Text style={s.s10}>Clock off</Text>
      </Pressable>
      <Pressable onPress={v.dismiss} style={s.s11}>
        <Text style={s.s12}>Not yet</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "86%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s4: {
    marginTop: 14,
  },
  s5: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
  },
  s6: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 20,
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
  s8: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
  },
  s9: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 18,
    width: "100%",
  },
  s10: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s11: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 10,
    width: "100%",
  },
  s12: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
