// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Circle, Path, Rect } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA29_M2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <Text style={s.s3}>
        Confirm location
      </Text>
      <View style={s.s4}>
        <Svg width="100%" height={200} viewBox="0 0 353 200" preserveAspectRatio="xMidYMid slice">
          <Rect width={353} height={200} fill="#F5EFE2" />
          <Rect x="228" y="10" width={140} height={66} rx="10" fill="#EAF0E4" />
          <Path d="M-10 150C60 138 96 62 176 62S300 96 372 54" stroke="#E3D8C2" strokeWidth="18" fill="none" strokeLinecap="round" />
          <Path d="M52 -10C68 60 40 120 66 220" stroke="#E9E1D0" strokeWidth="11" fill="none" />
          <Path d="M-10 96H372" stroke="#EDE6D7" strokeWidth="6" fill="none" />
          <Circle cx="176" cy="62" r="30" fill="#2563EB" opacity=".12" />
          <Circle cx="176" cy="62" r="14" fill="#F5A21E" />
          <Circle cx="176" cy="62" r="5" fill="#0F1B2A" />
        </Svg>
      </View>
      <View style={s.s5}>
        <Text style={s.s6}>
          2 Kirkwood Road, Corio VIC
        </Text>
        <Text style={s.s7}>
          Captured 14:02 · accurate to 8 m
        </Text>
      </View>
      <Pressable onPress={v.dismiss} style={s.s8}>
        <Text style={s.s9}>Use this location</Text>
      </Pressable>
      <Pressable onPress={v.push_A30_M1} style={s.s10}>
        <Text style={s.s11}>Search a different address</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "86%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s4: {
    borderColor: "#E2E8F0",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 14,
    overflow: "hidden",
  },
  s5: {
    marginTop: 14,
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 22,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 18,
    width: "100%",
  },
  s9: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 10,
    width: "100%",
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
