// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, TextInput, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA2_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <View style={s.s3}>
        <View style={s.s4}>
          <Text style={s.s5}>
            Forgot password
          </Text>
          <Text style={s.s6}>
            We will send a reset link to the address your operator has on file.
          </Text>
        </View>
        <Pressable onPress={v.dismiss} style={s.s7}>
          <Text style={s.s8}>×</Text>
        </Pressable>
      </View>
      <View style={s.s9}>
        <Text style={s.s10}>
          Email
        </Text>
        <TextInput style={s.s11} defaultValue="dave.whitmore@redgum.com.au" keyboardType="email-address" autoCapitalize="none" />
      </View>
      <Pressable onPress={v.open_A2_M2} style={s.s12}>
        <Text style={s.s13}>Send reset link</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "82%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  s4: {
    flex: 1,
  },
  s5: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s6: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderRadius: 9,
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 18,
    lineHeight: 18,
    textAlign: "center",
  },
  s9: {
    flexDirection: "column",
    gap: 6,
    marginTop: 20,
  },
  s10: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s11: {
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 20,
    width: "100%",
  },
  s13: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
