// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, Image, TextInput, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { IMG } from '@/proto/theme/images';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA31_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim name="sheetIn" duration={350} style={[s.s0, { paddingBottom: Math.max(32, insets.bottom) }]}>
      <View style={s.s1} />
      <Text style={s.s2}>
        New comment
      </Text>
      <TextInput style={s.s3} defaultValue="Pallets stacked two high on the dock, photo attached." multiline textAlignVertical="top" numberOfLines={3} />
      {v.attach ? (
        <View style={s.s4}>
          <Image source={IMG.palletsDock} resizeMode="cover" accessibilityLabel="Attached photo" style={s.s5} />
          <Pressable onPress={v.removeAttach} style={s.s6}>
            <Text style={s.s7}>Remove</Text>
          </Pressable>
        </View>
      ) : null}
      {v.noAttach ? (
        <Pressable onPress={v.addAttach} style={s.s8}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.75" strokeLinecap="round">
            <Path d="M12 6v12M6 12h12" />
          </Svg>
          <Text style={s.s9}>Add photo</Text>
        </Pressable>
      ) : null}
      <Pressable onPress={v.postWithPhoto} style={s.s10}>
        <Text style={s.s11}>Post</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    position: "absolute",
    right: 0,
  },
  s1: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s2: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s3: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 14,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
    width: "100%",
  },
  s4: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 12,
    marginTop: 12,
  },
  s5: {
    borderRadius: 12,
    height: 82,
    width: 110,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    height: 40,
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
  },
  s7: {
    color: "#DC2626",
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    lineHeight: 13,
    textAlign: "center",
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#94A3B8",
    borderRadius: 12,
    borderStyle: "dashed",
    borderWidth: 1.5,
    flexDirection: "column",
    gap: 4,
    height: 82,
    justifyContent: "center",
    marginTop: 12,
    width: 110,
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 16,
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 18,
    width: "100%",
  },
  s11: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
