// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, Image, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { IMG } from '@/proto/theme/images';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA32_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim name="sheetIn" duration={350} style={[s.s0, { paddingBottom: Math.max(32, insets.bottom) }]}>
      <View style={s.s1} />
      <Text style={s.s2}>
        Use this photo
      </Text>
      <View style={s.s4}>
        <Image source={IMG.driver} resizeMode="cover" accessibilityLabel="Captured declaration photo" style={s.s5} />
      </View>
      <View style={s.s6}>
        <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="2" strokeLinecap="round">
          <Circle cx="12" cy="12" r="9" />
          <Path d="M12 7.5V12l3 2" />
        </Svg>
        <Text style={s.s7}>
          06:14 · Laverton VIC
        </Text>
      </View>
      <Pressable onPress={v.usePhoto} style={s.s8}>
        <Text style={s.s9}>Use photo</Text>
      </Pressable>
      <Pressable onPress={v.retakePhoto} style={s.s10}>
        <Text style={s.s11}>Retake</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    position: "absolute",
    right: 0,
  },
  s1: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s2: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s3: {
    aspectRatio: 1.333,
    borderRadius: 12,
    marginTop: 14,
    width: "100%",
  },
  s4: {
    aspectRatio: 1.333,
    borderRadius: 12,
    marginTop: 14,
    overflow: "hidden",
    width: "100%",
  },
  s5: {
    height: "100%",
    width: "100%",
  },
  s6: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 18,
    width: "100%",
  },
  s9: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 10,
    width: "100%",
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
