// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Circle, Path, Rect } from 'react-native-svg';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA35_M1() {
  const v = useVals();
  return (
    <View style={s.s0}>
      <Anim name="modalIn" duration={200} style={s.s1}>
        <View style={s.s2}>
          <Text style={s.s3}>
            Allow FleetSync to use your location?
          </Text>
          <Text style={s.s4}>
            Your position is recorded when you clock on, arrive at a site and complete a delivery.
          </Text>
          <View style={s.s5}>
            <Svg width="100%" height={90} viewBox="0 0 254 90" preserveAspectRatio="none">
              <Rect width={254} height={90} fill="#F5EFE2" />
              <Path d="M-10 62L90 34L270 52" stroke="#E3D8C2" strokeWidth="10" fill="none" />
              <Path d="M60 -10L82 100" stroke="#E3D8C2" strokeWidth="7" fill="none" />
              <Path d="M-10 62L90 34L270 52" stroke="#F5A21E" strokeWidth="2.5" strokeDasharray="6 5" fill="none" />
              <Circle cx="127" cy="44" r="9" fill="#16324F" />
              <Circle cx="127" cy="44" r="3" fill="#fff" />
            </Svg>
          </View>
        </View>
        <View style={s.s6}>
          <Pressable onPress={v.rep_A36} style={s.s7}>
            <Text style={s.s8}>Allow While Using App</Text>
          </Pressable>
        </View>
        <View style={s.s6}>
          <Pressable onPress={v.rep_A35_S1} style={s.s7}>
            <Text style={s.s9}>Don't Allow</Text>
          </Pressable>
        </View>
      </Anim>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    alignItems: "center",
    bottom: 0,
    flexDirection: "row",
    justifyContent: "center",
    left: 0,
    paddingBottom: 32,
    paddingLeft: 32,
    paddingRight: 32,
    paddingTop: 32,
    position: "absolute",
    right: 0,
    top: 0,
  },
  s1: {
    backgroundColor: "#F7F7F8",
    borderRadius: 14,
    maxWidth: 290,
    overflow: "hidden",
    width: "100%",
  },
  s2: {
    paddingBottom: 16,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 20,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 17,
    lineHeight: 22,
    textAlign: "center",
  },
  s4: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
    textAlign: "center",
  },
  s5: {
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 14,
    overflow: "hidden",
  },
  s6: {
    borderTopColor: "#D8DBE0",
    borderTopWidth: 1,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 46,
    justifyContent: "center",
    width: "100%",
  },
  s8: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s9: {
    color: "#2563EB",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
