// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Polygon } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA6_M2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <Text style={s.s3}>
        Two ways around it
      </Text>
      <Pressable onPress={v.reroute} style={s.s4}>
        <View style={s.s5}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
            <Polygon points="3 11 21 3 13 21 11 13 3 11" />
          </Svg>
        </View>
        <View style={s.s6}>
          <Text style={s.s7}>
            Via Anderson Road
          </Text>
          <Text style={s.s8}>
            Cleared for 4.9 m
          </Text>
        </View>
        <View style={s.s9}>
          <Text style={s.s10}>
            +3.1 km
          </Text>
          <Text style={s.s11}>
            +4 min
          </Text>
        </View>
      </Pressable>
      <Pressable onPress={v.reroute} style={s.s12}>
        <View style={s.s13}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
            <Polygon points="3 11 21 3 13 21 11 13 3 11" />
          </Svg>
        </View>
        <View style={s.s6}>
          <Text style={s.s7}>
            Via the bypass
          </Text>
          <Text style={s.s8}>
            No height limit, one toll
          </Text>
        </View>
        <View style={s.s9}>
          <Text style={s.s10}>
            +8.4 km
          </Text>
          <Text style={s.s14}>
            -2 min
          </Text>
        </View>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "82%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 14,
    marginTop: 6,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 16,
    width: "100%",
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s6: {
    flex: 1,
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "left",
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s9: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 14,
    lineHeight: 18,
    textAlign: "right",
  },
  s11: {
    color: "#16A34A",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "right",
  },
  s12: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    gap: 14,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 16,
    width: "100%",
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s14: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "right",
  },
});
