// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA7_M1() {
  const v = useVals();
  return (
    <View style={s.s0}>
      <Anim name="modalIn" duration={200} style={s.s1}>
        <View style={s.s2}>
          <Text style={s.s3}>
            Apply the suggested order?
          </Text>
          <Text style={s.s4}>
            Kate Ryan will see the change straight away.
          </Text>
        </View>
        <View style={s.s5}>
          <Pressable onPress={v.dismiss} style={s.s6}>
            <Text style={s.s7}>Cancel</Text>
          </Pressable>
          <Pressable onPress={v.useSuggested} style={s.s8}>
            <Text style={s.s9}>Apply</Text>
          </Pressable>
        </View>
      </Anim>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    alignItems: "center",
    bottom: 0,
    flexDirection: "row",
    justifyContent: "center",
    left: 0,
    paddingBottom: 32,
    paddingLeft: 32,
    paddingRight: 32,
    paddingTop: 32,
    position: "absolute",
    right: 0,
    top: 0,
  },
  s1: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    maxWidth: 300,
    overflow: "hidden",
    width: "100%",
  },
  s2: {
    paddingBottom: 22,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 22,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
    textAlign: "center",
  },
  s4: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    textAlign: "center",
  },
  s5: {
    borderTopColor: "#E2E8F0",
    borderTopWidth: 1,
    flexDirection: "row",
  },
  s6: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRightColor: "#E2E8F0",
    borderRightWidth: 1,
    borderWidth: 0,
    flex: 1,
    flexDirection: "row",
    height: 52,
    justifyContent: "center",
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_500Medium",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 0,
    flex: 1,
    flexDirection: "row",
    height: 52,
    justifyContent: "center",
  },
  s9: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
