// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenB4_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <View style={s.s3}>
        <View style={s.s4}>
          <Text style={s.s5}>
            What FleetSync checks
          </Text>
          <Text style={s.s6}>
            Five parameters, set by the Heavy Vehicle National Law and by each operator's accreditation.
          </Text>
        </View>
        <Pressable onPress={v.dismiss} style={s.s7}>
          <Text style={s.s8}>×</Text>
        </Pressable>
      </View>
      <View style={s.s9}>
        <View>
          <Text style={s.s10}>
            Licence class and expiry
          </Text>
          <Text style={s.s11}>
            Matched nightly against the issuing register, so a suspension shows up without anyone reporting it.
          </Text>
        </View>
        <View>
          <Text style={s.s10}>
            NHVR medical certificate
          </Text>
          <Text style={s.s11}>
            Required for fatigue regulated heavy vehicles, renewed on the schedule your age band sets.
          </Text>
        </View>
        <View>
          <Text style={s.s10}>
            Fatigue accreditation
          </Text>
          <Text style={s.s11}>
            BFM or AFM, and it must match the ruleset the operator runs you under.
          </Text>
        </View>
        <View>
          <Text style={s.s10}>
            Dangerous goods licence
          </Text>
          <Text style={s.s11}>
            Only gates tanker and placarded loads. Without it, general freight still runs.
          </Text>
        </View>
        <View>
          <Text style={s.s10}>
            Work rights
          </Text>
          <Text style={s.s11}>
            Checked once through VEVO, rechecked when a visa condition changes.
          </Text>
        </View>
      </View>
      <View style={s.s12} />
      <Text style={s.s13}>
        What the badges mean
      </Text>
      <View style={s.s14}>
        <View style={s.s15}>
          <View style={s.s16}>
            <Text style={s.s17}>Matched with VicRoads</Text>
          </View>
          <Text style={s.s11}>
            The register agrees
          </Text>
        </View>
        <View style={s.s15}>
          <View style={s.s18}>
            <Text style={s.s19}>Checked by FleetSync</Text>
          </View>
          <Text style={s.s11}>
            We read and verified the document
          </Text>
        </View>
        <View style={s.s15}>
          <View style={s.s20}>
            <Text style={s.s21}>Confirmed by employer</Text>
          </View>
          <Text style={s.s11}>
            An operator sighted the original
          </Text>
        </View>
        <View style={s.s15}>
          <View style={s.s22}>
            <Text style={s.s23}>Self declared</Text>
          </View>
          <Text style={s.s11}>
            Nobody has checked it yet
          </Text>
        </View>
      </View>
      <Pressable onPress={v.dismiss} style={s.s24}>
        <Text style={s.s25}>Got it</Text>
      </Pressable>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "86%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  s4: {
    flex: 1,
  },
  s5: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s6: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderRadius: 9,
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 18,
    lineHeight: 18,
    textAlign: "center",
  },
  s9: {
    flexDirection: "column",
    gap: 14,
    marginTop: 18,
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s12: {
    backgroundColor: "#E2E8F0",
    height: 1,
    marginBottom: 18,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 18,
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s14: {
    flexDirection: "column",
    gap: 10,
    marginTop: 12,
  },
  s15: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  s16: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s17: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textTransform: "uppercase",
  },
  s18: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s19: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textTransform: "uppercase",
  },
  s20: {
    alignItems: "center",
    backgroundColor: "#F0FDFA",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s21: {
    color: "#0F766E",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textTransform: "uppercase",
  },
  s22: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s23: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textTransform: "uppercase",
  },
  s24: {
    alignItems: "center",
    backgroundColor: "#0F1B2A",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 20,
    width: "100%",
  },
  s25: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
