// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenC2_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <Anim scroll name="sheetIn" duration={350} style={s.s0} contentContainerStyle={[s.s1, { paddingBottom: Math.max(32, insets.bottom) }]} showsVerticalScrollIndicator={false}>
      <View style={s.s2} />
      <Text style={s.s3}>
        Availability settings
      </Text>
      <View style={s.s4}>
        <View style={s.s5}>
          <Text style={s.s6}>
            Radius from Laverton
          </Text>
          <Text style={s.s7}>
            Currently {v.radius}
          </Text>
        </View>
        <Pressable onPress={v.radiusDown} style={s.s8}>
          <Text style={s.s9}>−</Text>
        </Pressable>
        <Pressable onPress={v.radiusUp} style={s.s8}>
          <Text style={s.s9}>+</Text>
        </Pressable>
      </View>
      <Pressable onPress={v.push_C1} style={s.s10}>
        <View style={s.s5}>
          <Text style={s.s11}>Work types and days</Text>
        </View>
        <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <Path d="M9 6l6 6-6 6" />
        </Svg>
      </Pressable>
      <Pressable onPress={v.pauseAvail} style={s.s12}>
        <View style={s.s5}>
          <Text style={s.s11}>Pause for a week</Text>
        </View>
        <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round">
          <Path d="M9.5 6v12M14.5 6v12" />
        </Svg>
      </Pressable>
      <Pressable onPress={v.stopAvail} style={s.s13}>
        <View style={s.s5}>
          <Text style={s.s14}>Stop looking for work</Text>
        </View>
      </Pressable>
      <Text style={s.s15}>
        Pausing keeps your settings. Stopping hides you and clears the offers you have not answered.
      </Text>
    </Anim>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    bottom: 0,
    boxShadow: "0 -8px 32px rgba(15,27,42,.18)",
    left: 0,
    maxHeight: "84%",
    position: "absolute",
    right: 0,
  },
  s1: {
    flexGrow: 1,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    height: 4,
    marginBottom: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 0,
    width: 40,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderRadius: 12,
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  s5: {
    flex: 1,
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s9: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 20,
    lineHeight: 20,
    textAlign: "center",
  },
  s10: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    marginTop: 6,
    minHeight: 56,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "left",
  },
  s12: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 56,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s13: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 56,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s14: {
    color: "#DC2626",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "left",
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
  },
});
