// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { StyleSheet, Text, View } from 'react-native';
import Svg, { Defs, RadialGradient, Rect, Stop } from 'react-native-svg';
import { FleetLogo } from '@/proto/components/FleetLogo';

/** Five-second FleetSync brand splash. */
export default function ScreenA1() {
  return (
    <View style={s.root}>
      <Svg pointerEvents="none" style={StyleSheet.absoluteFill} width="100%" height="100%" viewBox="0 0 344 702" preserveAspectRatio="xMidYMid slice">
        <Defs>
          <RadialGradient id="navyGlow" cx={0} cy={0} r={1} gradientUnits="userSpaceOnUse" gradientTransform="translate(172 84.24) rotate(-90) scale(561.6 412.8)">
            <Stop stopColor="#1B3A5B" />
            <Stop offset={0.45} stopColor="#12263D" />
            <Stop offset={1} stopColor="#0A1826" />
          </RadialGradient>
          <RadialGradient id="amberGlow" cx={0} cy={0} r={1} gradientUnits="userSpaceOnUse" gradientTransform="translate(172 575.64) rotate(-90) scale(280.8 206.4)">
            <Stop stopColor="#F5A21E" stopOpacity={0.14} />
            <Stop offset={0.7} stopColor="#F5A21E" stopOpacity={0} />
          </RadialGradient>
        </Defs>
        <Rect width={344} height={702} fill="#0B1622" />
        <Rect width={344} height={702} fill="url(#navyGlow)" />
        <Rect width={344} height={702} fill="url(#amberGlow)" opacity={0.5} />
      </Svg>
      <View style={s.content}>
        <View style={s.logoShadow}>
          <FleetLogo size={98} />
        </View>
        <Text style={s.wordmark}>
          <Text style={s.fleet}>Fleet</Text>
          <Text style={s.sync}>Sync</Text>
        </Text>
        <Text style={s.tagline}>Built for the long haul</Text>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  root: {
    alignItems: 'center',
    backgroundColor: '#0E2033',
    flex: 1,
  },
  content: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    transform: [{ translateY: 24 }],
  },
  logoShadow: {
    borderRadius: 24,
    elevation: 12,
    shadowColor: '#0E2033',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 11,
  },
  wordmark: {
    fontFamily: 'BarlowSemiCondensed_700Bold',
    fontSize: 48,
    letterSpacing: 0,
    lineHeight: 54,
    marginTop: 33,
  },
  fleet: {
    color: '#FFFFFF',
  },
  sync: {
    color: '#F5A21E',
  },
  tagline: {
    color: '#9DB1C7',
    fontFamily: 'Inter_400Regular',
    fontSize: 19,
    letterSpacing: 0.25,
    lineHeight: 25,
    marginTop: 14,
  },
});
