// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, StyleSheet } from 'react-native';
import Svg, { Path, Rect } from 'react-native-svg';
import { Anim } from '@/proto/theme/anim';

export default function ScreenA1() {
  return (
    <View style={s.s0}>
      <Svg width={88} height={88} viewBox="0 0 88 88" fill="none">
        <Rect width={88} height={88} rx="22" fill="#16324F" />
        <Path d="M20 60h48" stroke="#F5A21E" strokeWidth="6" strokeLinecap="round" />
        <Path d="M27 45h34" stroke="#FFFFFF" strokeWidth="6" strokeLinecap="round" opacity=".82" />
        <Path d="M34 30h20" stroke="#FFFFFF" strokeWidth="6" strokeLinecap="round" opacity=".42" />
      </Svg>
      <Text style={s.s1}>
        FLEETSYNC
      </Text>
      <Text style={s.s2}>
        Heavy vehicle fleet management
      </Text>
      <View style={s.s3}>
        <Anim name="barFill" duration={1200} style={s.s4} />
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    alignItems: "center",
    backgroundColor: "#0E2033",
    flex: 1,
    flexDirection: "column",
    gap: 18,
    justifyContent: "center",
  },
  s1: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 34,
    letterSpacing: 1.36,
    lineHeight: 38,
  },
  s2: {
    color: "rgba(255,255,255,.6)",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s3: {
    backgroundColor: "rgba(255,255,255,.14)",
    borderRadius: 999,
    bottom: 96,
    height: 3,
    left: 64,
    overflow: "hidden",
    position: "absolute",
    right: 64,
  },
  s4: {
    backgroundColor: "#F5A21E",
    borderRadius: 999,
    height: 3,
  },
});
