// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { Path, Rect } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA10() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <View style={s.s2}>
        <Pressable onPress={v.back} style={s.s3}>
          <Svg width={24} height={24} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M15 18l-6-6 6-6" />
          </Svg>
        </Pressable>
        <View style={s.s4}>
          <Text style={s.s5}>Scan pallets</Text>
        </View>
        <View style={s.s6} />
      </View>
      <View style={s.s7}>
        <Image source={IMG.palletsDock} resizeMode="cover" accessibilityLabel="Scanner view" style={s.s8} />
        <View pointerEvents="none" style={s.s9} />
        <Svg width="100%" height={240} viewBox="0 0 393 240" preserveAspectRatio="none">
          <Rect x="70" y="52" width={253} height={136} rx="14" fill="none" stroke="#F5A21E" strokeWidth="3" />
          <Path d="M78 120h237" stroke="#F5A21E" strokeWidth="1.5" strokeDasharray="8 6" />
        </Svg>
      </View>
      <View style={s.s10}>
        <View style={s.s4}>
          <Text style={s.s11}>
            {v.scanned}
          </Text>
          <View style={s.s12}>
            <View style={[s.s13, { width: v.scanPct }]} />
          </View>
        </View>
        <Pressable onPress={v.scanOne} style={s.s14}>
          <Text style={s.s15}>Scan</Text>
        </Pressable>
      </View>
      <ScrollView style={s.s4} contentContainerStyle={s.s16} showsVerticalScrollIndicator={false}>
        {v.scannedIds.map((p, pI) => (
            <React.Fragment key={pI}>
            <View style={s.s17}>
              <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M5 12.5l4.5 4.5L19 7" />
              </Svg>
              <Text style={s.s18}>
                {p.id}
              </Text>
            </View>
            </React.Fragment>
        ))}
      </ScrollView>
      <View style={[s.s19, { paddingBottom: Math.max(24, insets.bottom) }]}>
        <Pressable onPress={v.open_A10_M2} style={s.s20}>
          <Text style={s.s21}>Enter manually</Text>
        </Pressable>
        <Pressable onPress={v.push_A9} style={s.s22}>
          <Text style={s.s23}>Done</Text>
        </Pressable>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#0B1520",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "center",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 56,
    paddingBottom: 0,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 0,
  },
  s3: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  s4: {
    flex: 1,
  },
  s5: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "center",
  },
  s6: {
    width: 48,
  },
  s7: {
    backgroundColor: "#111C28",
    flexGrow: 0,
    flexShrink: 0,
    height: 240,
    overflow: "hidden",
    position: "relative",
  },
  s8: {
    bottom: 0,
    height: "100%",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    width: "100%",
  },
  s9: {
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  s10: {
    alignItems: "center",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 14,
    paddingBottom: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 18,
  },
  s11: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 30,
  },
  s12: {
    backgroundColor: "rgba(255,255,255,.16)",
    borderRadius: 999,
    height: 5,
    marginTop: 8,
    overflow: "hidden",
  },
  s13: {
    backgroundColor: "#F5A21E",
    borderRadius: 999,
    height: 5,
  },
  s14: {
    alignItems: "center",
    backgroundColor: "#F5A21E",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 48,
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 0,
  },
  s15: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "center",
  },
  s16: {
    flexGrow: 1,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 0,
  },
  s17: {
    alignItems: "center",
    borderBottomColor: "rgba(255,255,255,.08)",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
  },
  s18: {
    color: "rgba(255,255,255,.86)",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 14,
    lineHeight: 20,
  },
  s19: {
    flexDirection: "column",
    flexGrow: 0,
    flexShrink: 0,
    gap: 10,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
  },
  s20: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
  },
  s21: {
    color: "#F5A21E",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 14,
    textAlign: "center",
  },
  s22: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s23: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
