// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA13() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Work diary" sub="Wednesday 8 July 2026" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <View style={s.s6} />
            <View style={s.s7} />
            <View style={s.s8} />
            <View style={s.s9} />
            <View style={s.s10} />
            <View style={s.s11} />
          </View>
          <View style={s.s12}>
            <Text style={s.s13}>
              00:00
            </Text>
            <Text style={s.s13}>
              06:00
            </Text>
            <Text style={s.s13}>
              12:00
            </Text>
            <Text style={s.s13}>
              18:00
            </Text>
            <Text style={s.s13}>
              24:00
            </Text>
          </View>
          <View style={s.s14}>
            <View style={s.s15}>
              <View style={s.s16} />
              <Text style={s.s17}>Work</Text>
            </View>
            <View style={s.s15}>
              <View style={s.s18} />
              <Text style={s.s17}>Drive</Text>
            </View>
            <View style={s.s15}>
              <View style={s.s19} />
              <Text style={s.s17}>Rest</Text>
            </View>
            <View style={s.s15}>
              <View style={s.s20} />
              <Text style={s.s17}>Off duty</Text>
            </View>
          </View>
        </View>
        <View style={s.s21}>
          {v.diaryRows.map((e, eI) => (
              <React.Fragment key={eI}>
              <Pressable onPress={e.open} style={s.s22}>
                <View style={s.s23}>
                  <Text style={s.s24}>{e.at}</Text>
                </View>
                <View style={s.s2}>
                  <Text style={s.s25}>
                    {e.what}
                  </Text>
                  <Text style={s.s26}>
                    {e.note}
                  </Text>
                </View>
                <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <Path d="M9 6l6 6-6 6" />
                </Svg>
              </Pressable>
              </React.Fragment>
          ))}
        </View>
        <Pressable onPress={v.open_A13_M1} style={s.s27}>
          <Text style={s.s28}>Change duty status</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s5: {
    borderRadius: 8,
    flexDirection: "row",
    height: 40,
    overflow: "hidden",
  },
  s6: {
    backgroundColor: "#E2E8F0",
    width: "14%",
  },
  s7: {
    backgroundColor: "#2563EB",
    width: "6%",
  },
  s8: {
    backgroundColor: "#0EA5A4",
    width: "34%",
  },
  s9: {
    backgroundColor: "#16A34A",
    width: "8%",
  },
  s10: {
    backgroundColor: "#0EA5A4",
    width: "26%",
  },
  s11: {
    backgroundColor: "#E2E8F0",
    width: "12%",
  },
  s12: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 11,
    lineHeight: 16,
  },
  s14: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginTop: 14,
  },
  s15: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  s16: {
    backgroundColor: "#2563EB",
    borderRadius: 3,
    height: 12,
    width: 12,
  },
  s17: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
  },
  s18: {
    backgroundColor: "#0EA5A4",
    borderRadius: 3,
    height: 12,
    width: 12,
  },
  s19: {
    backgroundColor: "#16A34A",
    borderRadius: 3,
    height: 12,
    width: 12,
  },
  s20: {
    backgroundColor: "#E2E8F0",
    borderRadius: 3,
    height: 12,
    width: 12,
  },
  s21: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s22: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s23: {
    flexGrow: 0,
    flexShrink: 0,
    width: 52,
  },
  s24: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s25: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s26: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s27: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s28: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
