// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA14() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Pre start" sub={v.checkProgress} showBack={true} onBack={v.back} />
      <View style={s.s2}>
        <View style={[s.s3, { width: v.checkPct }]} />
      </View>
      <ScrollView style={s.s4} contentContainerStyle={s.s5} showsVerticalScrollIndicator={false}>
        <Pressable onPress={v.open_A14_M1} style={s.s6}>
          <Image source={IMG.primeMover} resizeMode="cover" accessibilityLabel="Kenworth T610" style={s.s7} />
          <View style={s.s4}>
            <Text style={s.s8}>
              1RG4XT
            </Text>
            <Text style={s.s9}>
              Kenworth T610 · Trailer T-4471
            </Text>
          </View>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M4 8h13l-3-3" />
            <Path d="M20 16H7l3 3" />
          </Svg>
        </Pressable>
        <View style={s.s10}>
          <Text style={s.s11}>General freight checklist, Redgum Freightlines</Text>
        </View>
        <View style={s.s12}>
          {v.checkRows.map((r, rI) => (
              <React.Fragment key={rI}>
              <View style={s.s13}>
                <View style={s.s4}>
                  <Pressable onPress={r.open} style={s.s14}>
                    <Text style={s.s15}>{r.name}</Text>
                  </Pressable>
                  <View>
                    <Pressable onPress={r.fail} style={s.s16}>
                      <Text style={s.s17}>Add comment</Text>
                    </Pressable>
                  </View>
                </View>
                <Pressable onPress={r.pass} style={s.s18}>
                  {r.isPass ? (
                    <View style={s.s19}>
                      <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round">
                        <Path d="M5 12.5l4.5 4.5L19 7" />
                      </Svg>
                    </View>
                  ) : null}
                  {r.notPass ? (
                    <View style={s.s20}>
                      <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                        <Path d="M5 12.5l4.5 4.5L19 7" />
                      </Svg>
                    </View>
                  ) : null}
                </Pressable>
                <Pressable onPress={r.fail} style={s.s18}>
                  {r.isFail ? (
                    <View style={s.s21}>
                      <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.6" strokeLinecap="round">
                        <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
                      </Svg>
                    </View>
                  ) : null}
                  {r.notFail ? (
                    <View style={s.s20}>
                      <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2.2" strokeLinecap="round">
                        <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
                      </Svg>
                    </View>
                  ) : null}
                </Pressable>
              </View>
              </React.Fragment>
          ))}
        </View>
        <Pressable onPress={v.rep_A14_S1} style={s.s22}>
          <Text style={s.s23}>Finish inspection</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    backgroundColor: "#E2E8F0",
    flexGrow: 0,
    flexShrink: 0,
    height: 4,
  },
  s3: {
    backgroundColor: "#2563EB",
    height: 4,
  },
  s4: {
    flex: 1,
  },
  s5: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    width: "100%",
  },
  s7: {
    borderRadius: 10,
    flexGrow: 0,
    flexShrink: 0,
    height: 52,
    width: 52,
  },
  s8: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s10: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    height: 28,
    paddingBottom: 0,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 0,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 13,
  },
  s12: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s13: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 64,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
  },
  s14: {
    backgroundColor: "transparent",
    borderWidth: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  s15: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s16: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 2,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  s17: {
    color: "#2563EB",
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  s18: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    width: 44,
  },
  s19: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 12,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s20: {
    alignItems: "center",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1.5,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s21: {
    alignItems: "center",
    backgroundColor: "#DC2626",
    borderRadius: 12,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s22: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 4,
    width: "100%",
  },
  s23: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
