// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA14_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Pre start" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <Svg width={26} height={26} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
          </View>
          <View>
            <Text style={s.s6}>
              16 of 16 checked
            </Text>
            <Text style={s.s7}>
              1 comment recorded
            </Text>
          </View>
        </View>
        <View style={s.s8}>
          <View style={s.s4}>
            <Image source={IMG.primeMover} resizeMode="cover" accessibilityLabel="Kenworth T610" style={s.s9} />
            <View style={s.s2}>
              <Text style={s.s10}>
                1RG4XT
              </Text>
              <Text style={s.s7}>
                Kenworth T610 · Trailer T-4471
              </Text>
            </View>
          </View>
          <View style={s.s11}>
            <Image source={IMG.tyreDefect} resizeMode="cover" accessibilityLabel="Defect photo" style={s.s12} />
            <View style={s.s2}>
              <Text style={s.s13}>
                Brakes and air lines
              </Text>
              <Text style={s.s14}>
                Air leak on rear brake line, holding pressure but audible. Repair soon.
              </Text>
            </View>
          </View>
          <Text style={s.s7}>
            Submitted 06:31, Laverton VIC. Kate Ryan and the workshop can see this now.
          </Text>
        </View>
        <Pressable onPress={v.rep_A28} style={s.s15}>
          <Text style={s.s16}>Start work</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 16,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 24,
    lineHeight: 28,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexDirection: "column",
    flexShrink: 0,
    gap: 12,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s9: {
    borderRadius: 10,
    flexGrow: 0,
    flexShrink: 0,
    height: 52,
    width: 52,
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
  s11: {
    alignItems: "flex-start",
    backgroundColor: "#FEF6E9",
    borderRadius: 12,
    flexDirection: "row",
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 12,
  },
  s12: {
    borderRadius: 8,
    flexGrow: 0,
    flexShrink: 0,
    height: 42,
    width: 56,
  },
  s13: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 20,
  },
  s14: {
    color: "#B45309",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s16: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
