// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA14_M2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Check item" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <Text style={s.s4}>
          {v.activeCheck}
        </Text>
        <Text style={s.s5}>
          Walk the length of the combination. Look, listen and feel. If anything is outside what you would sign for, mark it failed and record what you saw.
        </Text>
        <View style={s.s6}>
          <Pressable onPress={v.passItem} style={s.s7}>
            <Svg width={28} height={28} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
            <Text style={s.s8}>PASS</Text>
          </Pressable>
          <Pressable onPress={v.failItem} style={s.s9}>
            <Svg width={28} height={28} viewBox="0 0 24 24" fill="none" stroke="#DC2626" strokeWidth="2.4" strokeLinecap="round">
              <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
            </Svg>
            <Text style={s.s10}>FAIL</Text>
          </Pressable>
        </View>
        <Pressable onPress={v.failItem} style={s.s11}>
          <Text style={s.s12}>Add comment</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 32,
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  s6: {
    flexDirection: "row",
    gap: 12,
    marginTop: 24,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 16,
    borderWidth: 0,
    flexBasis: 0,
    flexDirection: "column",
    flexGrow: 1,
    flexShrink: 1,
    gap: 8,
    height: 96,
    justifyContent: "center",
  },
  s8: {
    color: "#fff",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    letterSpacing: 0.88,
    lineHeight: 22,
  },
  s9: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1.5,
    flexBasis: 0,
    flexDirection: "column",
    flexGrow: 1,
    flexShrink: 1,
    gap: 8,
    height: 96,
    justifyContent: "center",
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    letterSpacing: 0.88,
    lineHeight: 22,
  },
  s11: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 56,
    justifyContent: "center",
    marginTop: 12,
  },
  s12: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "center",
  },
});
