// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { Circle, G, Path, Rect, Text as SvgText } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA18() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Tracking" sub="CN-48213, Coastline Grocers" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <Svg width="100%" height={220} viewBox="0 0 393 220" preserveAspectRatio="xMidYMid slice">
            <Rect width={393} height={220} fill="#F5EFE2" />
            <Rect x="270" y="20" width={140} height={70} rx="10" fill="#EAF0E4" />
            <Path d="M-10 170C70 160 130 120 200 100S320 60 410 66" stroke="#E3D8C2" strokeWidth="18" fill="none" strokeLinecap="round" />
            <Path d="M60 -10C74 60 40 120 70 230" stroke="#E9E1D0" strokeWidth="10" fill="none" />
            <Path d="M-10 170C70 160 130 120 200 100" stroke="#16A34A" strokeWidth="5" fill="none" strokeLinecap="round" />
            <Path d="M200 100S320 60 410 66" stroke="#F5A21E" strokeWidth="4" strokeDasharray="10 8" fill="none" strokeLinecap="round" />
            <Circle cx="200" cy="100" r="11" fill="#2563EB" stroke="#fff" strokeWidth="3" />
            <G>
              <Circle cx="356" cy="66" r="14" fill="#16324F" />
              <SvgText x="356" y="71" textAnchor="middle" fontFamily="Inter_700Bold" fontSize="13" fill="#FFFFFF">
                1
              </SvgText>
            </G>
          </Svg>
        </View>
        <View style={s.s5}>
          <View style={s.s6}>
            <View style={s.s7}>
              <Text style={s.s8}>
                Remaining
              </Text>
              <Text style={s.s9}>
                284 km
              </Text>
            </View>
            <View style={s.s7}>
              <Text style={s.s8}>
                ETA
              </Text>
              <Text style={s.s9}>
                11:04
              </Text>
            </View>
          </View>
          <View style={s.s10}>
            <Image source={IMG.allocator} resizeMode="cover" accessibilityLabel="Kate Ryan" style={s.s11} />
            <View style={s.s2}>
              <Text style={s.s12}>
                Kate Ryan can see this
              </Text>
              <Text style={s.s13}>
                Position updates every two minutes while you are on duty.
              </Text>
            </View>
          </View>
          <Pressable onPress={v.t_shareEta} style={s.s14}>
            <Text style={s.s15}>Send ETA to the site</Text>
          </Pressable>
        </View>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
  },
  s4: {
    flexGrow: 0,
    flexShrink: 0,
    height: 220,
    position: "relative",
  },
  s5: {
    flexDirection: "column",
    gap: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s6: {
    flexDirection: "row",
    gap: 10,
  },
  s7: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s9: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 24,
    lineHeight: 28,
    marginTop: 6,
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  s11: {
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    width: 40,
  },
  s12: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s14: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s15: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
