// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA19() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Fuel" sub="This week" showBack={true} onBack={v.back} rightPlus={true} onRight={v.push_A19_M1} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View>
            <Text style={s.s5}>
              Total this week
            </Text>
            <Text style={s.s6}>
              $2,216.01
            </Text>
          </View>
          <View>
            <Text style={s.s7}>
              1201.8 L
            </Text>
            <Text style={s.s8}>
              44.9 L/100 km
            </Text>
          </View>
        </View>
        <View style={s.s9}>
          {v.fillRows.map((f, fI) => (
              <React.Fragment key={fI}>
              <Pressable onPress={f.tap} style={s.s10}>
                <View style={s.s11}>
                  <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#B45309" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                    <Path d="M5 21V5a2 2 0 0 1 2-2h5a2 2 0 0 1 2 2v16" />
                    <Path d="M4 21h11" />
                    <Path d="M14 9h3a2 2 0 0 1 2 2v6a1.5 1.5 0 0 0 3 0v-6l-2.5-4" />
                  </Svg>
                </View>
                <View style={s.s2}>
                  <Text style={s.s12}>
                    {f.where}
                  </Text>
                  <Text style={s.s13}>
                    {f.ref} · {f.at}
                  </Text>
                </View>
                <View style={s.s14}>
                  <Text style={s.s15}>
                    {f.t}
                  </Text>
                  <Text style={s.s16}>
                    {f.l}
                  </Text>
                </View>
              </Pressable>
              </React.Fragment>
          ))}
        </View>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "flex-end",
    backgroundColor: "#0E2033",
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 18,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 18,
  },
  s5: {
    color: "rgba(255,255,255,.55)",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s6: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 30,
    lineHeight: 34,
    marginTop: 6,
  },
  s7: {
    color: "rgba(255,255,255,.55)",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "right",
  },
  s8: {
    color: "#F5A21E",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "right",
  },
  s9: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s10: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s11: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 10,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s12: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "left",
  },
  s14: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s15: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "right",
  },
  s16: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "right",
  },
});
