// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, TextInput, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA19_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Add a fill" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <Text style={s.s6}>
              Litres
            </Text>
            <TextInput style={s.s7} defaultValue="412.6" />
          </View>
          <View style={s.s5}>
            <Text style={s.s6}>
              Per litre
            </Text>
            <TextInput style={s.s7} defaultValue="1.842" />
          </View>
        </View>
        <View style={s.s4}>
          <View style={s.s5}>
            <Text style={s.s6}>
              Total
            </Text>
            <TextInput style={s.s8} defaultValue="759.99" />
          </View>
          <View style={s.s5}>
            <Text style={s.s6}>
              Odometer
            </Text>
            <TextInput style={s.s7} defaultValue="684 210" />
          </View>
        </View>
        <View style={s.s9}>
          <Text style={s.s6}>
            Location
          </Text>
          <TextInput style={s.s10} defaultValue="Shell Euroa" />
        </View>
        <Pressable onPress={v.push_A19_M2} style={s.s11}>
          <Svg width={26} height={26} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M6 3h12v18l-3-2-3 2-3-2-3 2z" />
            <Path d="M9 8h6M9 12h6" />
          </Svg>
          <Text style={s.s12}>Photograph the receipt</Text>
        </Pressable>
        <Pressable onPress={v.saveFuel} style={s.s13}>
          <Text style={s.s14}>Save</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    flexDirection: "row",
    gap: 10,
  },
  s5: {
    flex: 1,
    flexDirection: "column",
    flexShrink: 0,
    gap: 6,
  },
  s6: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s7: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "RobotoMono_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s8: {
    backgroundColor: "#F4F6FA",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "RobotoMono_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s9: {
    flexDirection: "column",
    flexShrink: 0,
    gap: 6,
  },
  s10: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s11: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#94A3B8",
    borderRadius: 14,
    borderStyle: "dashed",
    borderWidth: 1.5,
    flexDirection: "column",
    gap: 8,
    height: 120,
    justifyContent: "center",
    width: "100%",
  },
  s12: {
    color: "#5B6B7F",
    fontFamily: "Inter_500Medium",
    fontSize: 14,
    lineHeight: 20,
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s14: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
