// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA19_M2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <View style={s.s2}>
        <Pressable onPress={v.back} style={s.s3}>
          <Svg width={24} height={24} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M15 18l-6-6 6-6" />
          </Svg>
        </Pressable>
        <View style={s.s4}>
          <Text style={s.s5}>Receipt</Text>
        </View>
        <View style={s.s6} />
      </View>
      <View style={s.s7}>
        <View style={s.s8}>
          <Text style={s.s9}>
            SHELL EUROA
          </Text>
          <Text style={s.s10}>
            Hume Fwy, Euroa VIC
          </Text>
          <View style={s.s11} />
          <View style={s.s12}>
            <Text style={s.s13}>
              DIESEL
            </Text>
            <Text style={s.s13}>
              412.6 L
            </Text>
          </View>
          <View style={s.s12}>
            <Text style={s.s13}>
              PER L
            </Text>
            <Text style={s.s13}>
              1.842
            </Text>
          </View>
          <View style={s.s11} />
          <View style={s.s12}>
            <Text style={s.s14}>
              TOTAL
            </Text>
            <Text style={s.s14}>
              $759.99
            </Text>
          </View>
          <Text style={s.s15}>
            RC-88410 · 08/07/26 10:56
          </Text>
        </View>
        <Svg width="100%" height="100%" viewBox="0 0 393 420" preserveAspectRatio="none">
          <Path d="M40 60h-16v-16M353 60h16v-16M40 360h-16v16M353 360h16v16" stroke="#F5A21E" strokeWidth="3" fill="none" strokeLinecap="round" />
        </Svg>
      </View>
      <View style={s.s16}>
        <Pressable onPress={v.addReceipt} style={s.s17}>
          <View style={s.s18} />
        </Pressable>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#0B1520",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "center",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 56,
    paddingBottom: 0,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 0,
  },
  s3: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  s4: {
    flex: 1,
  },
  s5: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "center",
  },
  s6: {
    width: 48,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#111C28",
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
  },
  s8: {
    backgroundColor: "#FBF7EE",
    borderRadius: 6,
    boxShadow: "0 12px 30px rgba(0,0,0,.4)",
    paddingBottom: 18,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 18,
    transform: [{
      rotate: "-2deg",
    }],
    width: 200,
  },
  s9: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 16,
    letterSpacing: 0.96,
    lineHeight: 20,
  },
  s10: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 10,
    lineHeight: 16,
  },
  s11: {
    backgroundColor: "#E2E8F0",
    height: 1,
    marginBottom: 10,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 10,
  },
  s12: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  s13: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 11,
    lineHeight: 18,
  },
  s14: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 13,
    lineHeight: 18,
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 10,
    lineHeight: 16,
    marginTop: 8,
  },
  s16: {
    alignItems: "center",
    backgroundColor: "#0B1520",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 150,
    justifyContent: "center",
  },
  s17: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "rgba(255,255,255,.35)",
    borderRadius: 999,
    borderWidth: 4,
    flexDirection: "row",
    height: 74,
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    width: 74,
  },
  s18: {
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    height: 58,
    width: 58,
  },
});
