// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA1_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={[s.s0, { paddingTop: insets.top, paddingBottom: Math.max(40, insets.bottom) }]}>
      <View style={s.s1}>
        <Svg width={56} height={56} viewBox="0 0 24 24" fill="none" stroke="#F5A21E" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
          <Path d="M12 3v13" />
          <Path d="M7 8l5-5 5 5" />
          <Path d="M4 21h16" />
        </Svg>
        <Text style={s.s2}>
          A new version is required
        </Text>
        <Text style={s.s3}>
          Heavy Vehicle National Law changed the way fatigue records are stored on 1 July 2026. This version of FleetSync can no longer submit a work diary, so you need the update before your next shift.
        </Text>
      </View>
      <Pressable onPress={v.t_store} style={s.s4}>
        <Text style={s.s5}>Update now</Text>
      </Pressable>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#0E2033",
    flex: 1,
    flexDirection: "column",
    paddingLeft: 24,
    paddingRight: 24,
  },
  s1: {
    flex: 1,
    flexDirection: "column",
    gap: 16,
    justifyContent: "center",
  },
  s2: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 32,
    lineHeight: 36,
  },
  s3: {
    color: "rgba(255,255,255,.68)",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    lineHeight: 24,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#F5A21E",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s5: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
