// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, TextInput, StyleSheet } from 'react-native';
import Svg, { Path, Rect } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <Svg width={52} height={52} viewBox="0 0 88 88" fill="none">
          <Rect width={88} height={88} rx="22" fill="#0E2033" />
          <Path d="M20 60h48" stroke="#F5A21E" strokeWidth="6" strokeLinecap="round" />
          <Path d="M27 45h34" stroke="#FFFFFF" strokeWidth="6" strokeLinecap="round" opacity=".82" />
          <Path d="M34 30h20" stroke="#FFFFFF" strokeWidth="6" strokeLinecap="round" opacity=".42" />
        </Svg>
        <Text style={s.s4}>
          Sign in to start your shift
        </Text>
        <Text style={s.s5}>
          Wednesday 8 July 2026
        </Text>
        <View style={s.s6}>
          <Text style={s.s7}>
            Email
          </Text>
          <TextInput style={s.s8} defaultValue="dave.whitmore@redgum.com.au" keyboardType="email-address" autoCapitalize="none" />
        </View>
        <View style={s.s9}>
          <Text style={s.s7}>
            Password
          </Text>
          <TextInput style={s.s8} defaultValue="········" secureTextEntry />
        </View>
        <Pressable onPress={v.rep_A26} style={s.s10}>
          <Text style={s.s11}>Sign in</Text>
        </Pressable>
        <Pressable onPress={v.open_A2_M1} style={s.s12}>
          <Text style={s.s13}>Forgot password</Text>
        </Pressable>
        <View style={s.s14}>
          <View style={s.s15} />
          <Text style={s.s16}>
            New to FleetSync
          </Text>
          <View style={s.s15} />
        </View>
        <Pressable onPress={v.push_B1} style={s.s17}>
          <Text style={s.s18}>Create an account</Text>
        </Pressable>
        <View style={s.s2} />
        <Text style={s.s19}>
          Version 4.2.0 · Redgum Freightlines and 1 other operator
        </Text>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    paddingBottom: 32,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 24,
  },
  s4: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 30,
    marginTop: 24,
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  s6: {
    flexDirection: "column",
    gap: 6,
    marginTop: 28,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s9: {
    flexDirection: "column",
    gap: 6,
    marginTop: 16,
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 24,
    width: "100%",
  },
  s11: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s12: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    marginTop: 8,
  },
  s13: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 14,
    textAlign: "center",
  },
  s14: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  s15: {
    backgroundColor: "#E2E8F0",
    flex: 1,
    height: 1,
  },
  s16: {
    color: "#94A3B8",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s17: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 16,
    width: "100%",
  },
  s18: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s19: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
});
