// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { useState } from 'react';
import { View, Text, Pressable, ScrollView, TextInput, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useVals } from '@/proto/runtime/vals';
import { LoginBackground } from '@/proto/components/LoginBackground';
import { FleetWordmark } from '@/proto/components/FleetWordmark';

export default function ScreenA2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [touched, setTouched] = useState({ email: false, password: false });
  const emailError = !email.trim()
    ? 'Email is required'
    : !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())
      ? 'Enter a valid email address'
      : '';
  const passwordError = !password ? 'Password is required' : password.length < 8 ? 'Password must be at least 8 characters' : '';
  const submit = () => {
    setTouched({ email: true, password: true });
    if (!emailError && !passwordError) {
      const firstPart = email.trim().split('@')[0].split(/[._+-]/)[0].replace(/\d+$/g, '');
      const userName = firstPart
        ? firstPart.charAt(0).toUpperCase() + firstPart.slice(1).toLowerCase()
        : 'Driver';
      v.setUserName(userName);
      v.rep_A26();
    }
  };
  return (
    <View style={s.s0}>
      <LoginBackground />
      <View style={[s.s1, { height: insets.top }]} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <FleetWordmark />
        <Text style={s.s4}>
          Sign in to start your shift
        </Text>
        <Text style={s.s5}>
          Wednesday 8 July 2026
        </Text>
        <View style={s.s6}>
          <Text style={s.s7}>
            Email
          </Text>
          <TextInput
            style={[s.s8, touched.email && emailError ? s.inputError : null]}
            value={email}
            onChangeText={setEmail}
            onBlur={() => setTouched((old) => ({ ...old, email: true }))}
            placeholder="you@example.com"
            placeholderTextColor="#94A3B8"
            keyboardType="email-address"
            autoCapitalize="none"
            autoCorrect={false}
            textContentType="emailAddress"
          />
          {touched.email && emailError ? <Text style={s.errorText}>{emailError}</Text> : null}
        </View>
        <View style={s.s9}>
          <Text style={s.s7}>
            Password
          </Text>
          <View style={[s.passwordBox, touched.password && passwordError ? s.inputError : null]}>
            <TextInput
              style={s.passwordInput}
              value={password}
              onChangeText={setPassword}
              onBlur={() => setTouched((old) => ({ ...old, password: true }))}
              placeholder="Enter your password"
              placeholderTextColor="#94A3B8"
              secureTextEntry={!showPassword}
              autoCapitalize="none"
              autoCorrect={false}
              textContentType="password"
            />
            <Pressable onPress={() => setShowPassword((old) => !old)} hitSlop={10} accessibilityRole="button" accessibilityLabel={showPassword ? 'Hide password' : 'Show password'}>
              <Ionicons name={showPassword ? 'eye-outline' : 'eye-off-outline'} size={22} color="#5B6B7F" />
            </Pressable>
          </View>
          {touched.password && passwordError ? <Text style={s.errorText}>{passwordError}</Text> : null}
        </View>
        <Pressable onPress={submit} style={s.s10}>
          <Text style={s.s11}>Sign in</Text>
        </Pressable>
        <Pressable onPress={v.open_A2_M1} style={s.s12}>
          <Text style={s.s13}>Forgot password</Text>
        </Pressable>
        <View style={s.s14}>
          <View style={s.s15} />
          <Text style={s.s16}>
            New to FleetSync
          </Text>
          <View style={s.s15} />
        </View>
        <Pressable onPress={v.push_B1} style={s.s17}>
          <Text style={s.s18}>Create an account</Text>
        </Pressable>
        <View style={s.s2} />
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    paddingBottom: 32,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 24,
  },
  s4: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 30,
    marginTop: 24,
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  s6: {
    flexDirection: "column",
    gap: 6,
    marginTop: 28,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s9: {
    flexDirection: "column",
    gap: 6,
    marginTop: 16,
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 24,
    width: "100%",
  },
  s11: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s12: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    marginTop: 8,
  },
  s13: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 14,
    textAlign: "center",
  },
  s14: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  s15: {
    backgroundColor: "#E2E8F0",
    flex: 1,
    height: 1,
  },
  s16: {
    color: "#94A3B8",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s17: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 16,
    width: "100%",
  },
  s18: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  passwordBox: {
    alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E2E8F0", borderRadius: 10,
    borderWidth: 1, flexDirection: "row", height: 52, paddingLeft: 14, paddingRight: 14,
  },
  passwordInput: {
    color: "#0F1B2A", flex: 1, fontFamily: "Inter_400Regular", fontSize: 16, height: "100%", padding: 0,
  },
  inputError: { borderColor: "#DC2626" },
  errorText: { color: "#DC2626", fontFamily: "Inter_400Regular", fontSize: 12, lineHeight: 16 },
});
