// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA20() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Odometer and hours" sub="1RG4XT" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <Pressable onPress={v.open_A20_M1} style={s.s4}>
          <Text style={s.s5}>
            Odometer
          </Text>
          <Text style={s.s6}>
            684 210
          </Text>
          <Text style={s.s7}>
            kilometres
          </Text>
        </Pressable>
        <View style={s.s8}>
          <Text style={s.s9}>
            Engine hours
          </Text>
          <Text style={s.s10}>
            18 442.6
          </Text>
          <Text style={s.s11}>
            hours
          </Text>
        </View>
        <View style={s.s12}>
          <View style={s.s13}>
            <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="2.4" strokeLinecap="round">
              <Path d="M4 12a8 8 0 0 1 16 0" />
              <Path d="M12 12v5" />
            </Svg>
            <Text style={s.s14}>From telematics</Text>
          </View>
          <Text style={s.s15}>
            read 11:38
          </Text>
        </View>
        <Pressable onPress={v.push_A20_M2} style={s.s16}>
          <Text style={s.s17}>Enter manually</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    paddingBottom: 18,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 18,
    width: "100%",
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 34,
    lineHeight: 38,
    marginTop: 6,
    textAlign: "left",
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
    textAlign: "left",
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    paddingBottom: 18,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 18,
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 34,
    lineHeight: 38,
    marginTop: 6,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  s12: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 999,
    flexDirection: "row",
    gap: 8,
    height: 30,
    paddingBottom: 0,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 0,
  },
  s14: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 12,
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 12,
    lineHeight: 16,
  },
  s16: {
    backgroundColor: "transparent",
    borderWidth: 0,
    height: 48,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  s17: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "left",
  },
});
