// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA21() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Timesheet" sub="Week to 12 July" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={v.timesheetWeek ? s.s8 : s.s5}>
            <Text style={v.timesheetWeek ? s.s9 : s.s6}>
              This shift
            </Text>
            <Text style={v.timesheetWeek ? s.s10 : s.s7}>
              02:47
            </Text>
          </View>
          <View style={v.timesheetWeek ? s.s5 : s.s8}>
            <Text style={v.timesheetWeek ? s.s6 : s.s9}>
              This week
            </Text>
            <Text style={v.timesheetWeek ? s.s7 : s.s10}>
              31 h 45 m
            </Text>
          </View>
        </View>
        <View style={s.s11}>
          {v.weekRows.map((w, wI) => (
              <React.Fragment key={wI}>
              <Pressable onPress={w.tap} style={s.s12}>
                <View style={s.s2}>
                  <Text style={s.s13}>
                    {w.d}
                  </Text>
                  <Text style={s.s14}>
                    {w.n}
                  </Text>
                </View>
                <View style={s.s15}>
                  <Text style={s.s16}>{w.h}</Text>
                </View>
              </Pressable>
              </React.Fragment>
          ))}
          <View style={s.s17}>
            <Text style={s.s18}>
              Total
            </Text>
            <Text style={s.s19}>
              31 h 45 m
            </Text>
          </View>
        </View>
        <Pressable onPress={v.open_A21_M1} style={s.s20}>
          <Text style={s.s21}>Start a break</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    flexDirection: "row",
    gap: 10,
  },
  s5: {
    backgroundColor: "#0E2033",
    borderRadius: 16,
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s6: {
    color: "rgba(255,255,255,.55)",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s7: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 28,
    lineHeight: 32,
    marginTop: 6,
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 28,
    lineHeight: 32,
    marginTop: 6,
  },
  s11: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 56,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s13: {
    color: "#0F1B2A",
    fontFamily: "Inter_500Medium",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s14: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "left",
  },
  s15: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s16: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s17: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 56,
  },
  s18: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 18,
    lineHeight: 22,
  },
  s19: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 16,
    lineHeight: 22,
  },
  s20: {
    alignItems: "center",
    backgroundColor: "#F5A21E",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s21: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
