// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { TabBar } from '@/proto/components/TabBar';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA22_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Messages" sub="2 unread" showBack={false} rightPlus={true} onRight={v.push_A22_M1} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <Pressable onPress={v.push_A22_M1} style={s.s4}>
          <Image source={IMG.allocator} resizeMode="cover" accessibilityLabel="Kate Ryan" style={s.s5} />
          <View style={s.s2}>
            <View style={s.s6}>
              <Text style={s.s7}>
                Kate Ryan
              </Text>
              <View style={s.s8} />
            </View>
            <Text style={s.s9} numberOfLines={1}>
              Coastline moved the dock window to 11:00.
            </Text>
          </View>
          <View style={s.s10}>
            <Text style={s.s11}>11:38</Text>
          </View>
        </Pressable>
        <Pressable onPress={v.push_A22_M1} style={s.s4}>
          <Image source={IMG.primeMover} resizeMode="cover" accessibilityLabel="Redgum workshop" style={s.s5} />
          <View style={s.s2}>
            <View style={s.s6}>
              <Text style={s.s7}>
                Redgum workshop
              </Text>
              <View style={s.s8} />
            </View>
            <Text style={s.s9} numberOfLines={1}>
              Air line on T-4471 is booked in for Friday.
            </Text>
          </View>
          <View style={s.s10}>
            <Text style={s.s11}>09:12</Text>
          </View>
        </Pressable>
        <Pressable onPress={v.push_A22_M1} style={s.s12}>
          <Image source={IMG.palletsDock} resizeMode="cover" accessibilityLabel="Marco Ferretti" style={s.s5} />
          <View style={s.s2}>
            <Text style={s.s13}>
              Marco Ferretti
            </Text>
            <Text style={s.s14} numberOfLines={1}>
              Use the north gate after 15:00.
            </Text>
          </View>
          <View style={s.s10}>
            <Text style={s.s15}>Yesterday</Text>
          </View>
        </Pressable>
      </ScrollView>
      <TabBar active="messages" unread={true} onRun={v.tabRun} onNav={v.tab_A6} onComp={v.tab_A25} onMsg={v.tab_A22} onProf={v.tab_A34} />
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexGrow: 1,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 8,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 14,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
    minHeight: 76,
    paddingBottom: 14,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 14,
    width: "100%",
  },
  s5: {
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 48,
    width: 48,
  },
  s6: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "Inter_700Bold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s8: {
    backgroundColor: "#2563EB",
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  s9: {
    color: "#0F1B2A",
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s10: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s11: {
    color: "#2563EB",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "left",
  },
  s12: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
    minHeight: 76,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s13: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s14: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "left",
  },
});
