// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, TextInput, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA22_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Kate Ryan" sub="Allocator, Redgum Freightlines" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        {v.msgs.map((m, mI) => (
            <React.Fragment key={mI}>
            <View>
              {m.them ? (
                <View style={s.s4}>
                  <Text style={s.s5}>
                    {m.text}
                  </Text>
                  <Text style={s.s6}>
                    {m.at}
                  </Text>
                </View>
              ) : null}
              {m.me ? (
                <View style={s.s7}>
                  <Text style={s.s8}>
                    {m.text}
                  </Text>
                  <Text style={s.s9}>
                    {m.at}
                  </Text>
                </View>
              ) : null}
            </View>
            </React.Fragment>
        ))}
      </ScrollView>
      <View style={[s.s10, { paddingBottom: Math.max(12, insets.bottom) }]}>
        <Pressable onPress={v.t_saved} style={s.s11}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M4 8.5h3l1.6-2.4h6.8L17 8.5h3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1z" />
            <Circle cx="12" cy="13" r="3.4" />
          </Svg>
        </Pressable>
        <TextInput style={s.s12} value={v.msgRef.value} onChangeText={v.msgRef.onChangeText} placeholder="Message Kate" placeholderTextColor="#94A3B8" />
        <Pressable onPress={v.sendMsg} style={s.s13}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M4 12h15" />
            <Path d="M13 6l6 6-6 6" />
          </Svg>
        </Pressable>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 10,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 16,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06)",
    maxWidth: "78%",
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s5: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
  },
  s6: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
  },
  s7: {
    backgroundColor: "#2563EB",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 4,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    marginLeft: "auto",
    maxWidth: "78%",
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s8: {
    color: "#FFFFFF",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
  },
  s9: {
    color: "rgba(255,255,255,.7)",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
    textAlign: "right",
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderTopColor: "#E2E8F0",
    borderTopWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 8,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s11: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s12: {
    backgroundColor: "#F4F6FA",
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 1,
    color: "#0F1B2A",
    flex: 1,
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    height: 44,
    paddingBottom: 0,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 0,
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 999,
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
});
