// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA23_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Consignment note" sub="CN-48213" showBack={true} onBack={v.back} rightShare={true} onRight={v.t_shared} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <View>
              <Text style={s.s6}>
                CONSIGNMENT NOTE
              </Text>
              <Text style={s.s7}>
                CN-48213
              </Text>
            </View>
            <View style={s.s8}>
              <Text style={s.s9}>RF</Text>
            </View>
          </View>
          <View style={s.s10} />
          <View style={s.s11}>
            <View>
              <Text style={s.s12}>
                Consignor
              </Text>
              <Text style={s.s13}>
                Redgum Freightlines, 18 Dohertys Road, Laverton North VIC
              </Text>
            </View>
            <View>
              <Text style={s.s12}>
                Consignee
              </Text>
              <Text style={s.s13}>
                Coastline Grocers, Wodonga Distribution Centre
              </Text>
            </View>
            <View style={s.s14}>
              <View>
                <Text style={s.s12}>
                  Pallets
                </Text>
                <Text style={s.s15}>
                  22
                </Text>
              </View>
              <View>
                <Text style={s.s12}>
                  Weight
                </Text>
                <Text style={s.s15}>
                  18 420 kg
                </Text>
              </View>
              <View>
                <Text style={s.s12}>
                  Vehicle
                </Text>
                <Text style={s.s15}>
                  1RG4XT
                </Text>
              </View>
            </View>
          </View>
          <View style={s.s10} />
          <View style={s.s16}>
            <View style={s.s17} />
            <View style={s.s17} />
            <View style={s.s18} />
          </View>
          <View style={s.s19}>
            <View>
              <View style={s.s20} />
              <Text style={s.s21}>
                Driver signature
              </Text>
            </View>
            <Text style={s.s22}>
              Page 1 of 2
            </Text>
          </View>
        </View>
        <Pressable onPress={v.t_saved} style={s.s23}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M12 4v12" />
            <Path d="M8 12l4 4 4-4" />
            <Path d="M5 20h14" />
          </Svg>
          <Text style={s.s24}>Save to this phone</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#E8ECF2",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#FFFFFF",
    borderRadius: 6,
    boxShadow: "0 4px 18px rgba(15,27,42,.12)",
    paddingBottom: 24,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 24,
  },
  s5: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 11,
    lineHeight: 16,
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#0E2033",
    borderRadius: 8,
    flexDirection: "row",
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  s9: {
    color: "#F5A21E",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 12,
    lineHeight: 12,
  },
  s10: {
    backgroundColor: "#E2E8F0",
    height: 1,
    marginBottom: 16,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 16,
  },
  s11: {
    flexDirection: "column",
    gap: 10,
  },
  s12: {
    color: "#94A3B8",
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    letterSpacing: 0.9,
    lineHeight: 12,
    textTransform: "uppercase",
  },
  s13: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
  },
  s14: {
    flexDirection: "row",
    gap: 24,
  },
  s15: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 12,
    lineHeight: 18,
  },
  s16: {
    flexDirection: "column",
    flexShrink: 0,
    gap: 6,
  },
  s17: {
    backgroundColor: "#F4F6FA",
    borderRadius: 2,
    height: 8,
  },
  s18: {
    backgroundColor: "#F4F6FA",
    borderRadius: 2,
    height: 8,
    width: "72%",
  },
  s19: {
    alignItems: "flex-end",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 24,
  },
  s20: {
    backgroundColor: "#0F1B2A",
    height: 1,
    width: 120,
  },
  s21: {
    color: "#94A3B8",
    fontFamily: "Inter_400Regular",
    fontSize: 9,
    lineHeight: 14,
    marginTop: 4,
  },
  s22: {
    color: "#94A3B8",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 9,
    lineHeight: 14,
  },
  s23: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    gap: 8,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s24: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
  },
});
