// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { TabBar } from '@/proto/components/TabBar';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA25_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Accreditation" sub="Dave Whitmore" showBack={false} />
      <View style={s.s2}>
        <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#DC2626" strokeWidth="1.9" strokeLinecap="round">
          <Circle cx="12" cy="12" r="9" />
          <Path d="M12 7.5v5" />
          <Path d="M12 16.2h.01" />
        </Svg>
        <Text style={s.s3}>
          Your Dangerous Goods licence expired on 2 July. Redgum Freightlines has been notified.
        </Text>
      </View>
      <ScrollView style={s.s4} contentContainerStyle={s.s5} showsVerticalScrollIndicator={false}>
        <View style={s.s6}>
          {v.accreditations.map((a, aI) => (
              <React.Fragment key={aI}>
              <Pressable onPress={v.push_A25_M1} style={s.s7}>
                <View style={s.s4}>
                  <Text style={s.s8}>
                    {a.n}
                  </Text>
                  <Text style={s.s9}>
                    {a.s}
                  </Text>
                </View>
                {a.bad ? (
                  <View style={s.s10}>
                    <Text style={s.s11}>Expired</Text>
                  </View>
                ) : null}
                <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <Path d="M9 6l6 6-6 6" />
                </Svg>
              </Pressable>
              </React.Fragment>
          ))}
        </View>
      </ScrollView>
      <TabBar active="compliance" onRun={v.tabRun} onNav={v.tab_A6} onComp={v.tab_A25} onMsg={v.tab_A22} onProf={v.tab_A34} />
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "flex-start",
    backgroundColor: "#FEF2F2",
    borderBottomColor: "#FCA5A5",
    borderBottomWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
  },
  s3: {
    color: "#991B1B",
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    lineHeight: 18,
  },
  s4: {
    flex: 1,
  },
  s5: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s6: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s8: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s11: {
    color: "#991B1B",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textAlign: "left",
    textTransform: "uppercase",
  },
});
