// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA26() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <View style={s.s2}>
        <View style={s.s3}>
          <Text style={s.s4}>
            Good morning, Dave
          </Text>
          <Text style={s.s5}>
            Who are you driving for today?
          </Text>
        </View>
        <Pressable onPress={v.open_A26_M1} style={s.s6}>
          <Svg width={24} height={24} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
            <Circle cx="12" cy="12" r="9" />
            <Path d="M9.2 9.2a3 3 0 0 1 5.8 1c0 2-2.9 2.6-2.9 3.3" />
            <Path d="M12 17.2h.01" />
          </Svg>
        </Pressable>
      </View>
      <ScrollView style={s.s3} contentContainerStyle={s.s7} showsVerticalScrollIndicator={false}>
        <Pressable onPress={v.pickRedgum} style={s.s8}>
          <View style={s.s9}>
            <Text style={s.s10}>RF</Text>
          </View>
          <View style={s.s3}>
            <Text style={s.s11}>
              Redgum Freightlines
            </Text>
            <Text style={s.s12}>
              Laverton VIC
            </Text>
            <View style={s.s13}>
              <View style={s.s14}>
                <Text style={s.s15}>Full time</Text>
              </View>
              <View style={s.s16}>
                <Text style={s.s17}>Last worked yesterday</Text>
              </View>
            </View>
          </View>
          <Image source={IMG.primeMover} resizeMode="cover" accessibilityLabel="Kenworth T610 prime mover" style={s.s18} />
          {v.redgumSel ? (
            <View style={s.s19} pointerEvents="none" />
          ) : null}
          {v.redgumSel ? (
            <View style={s.s20}>
              <Text style={s.s21}>Driving today</Text>
            </View>
          ) : null}
        </Pressable>
        <Pressable onPress={v.pickBarwon} style={s.s8}>
          <View style={s.s22}>
            <Text style={s.s23}>BF</Text>
          </View>
          <View style={s.s3}>
            <Text style={s.s11}>
              Barwon Fuel Haulage
            </Text>
            <Text style={s.s12}>
              Corio VIC
            </Text>
            <View style={s.s13}>
              <View style={s.s24}>
                <Text style={s.s25}>Casual</Text>
              </View>
              <View style={s.s16}>
                <Text style={s.s17}>Last worked 1 July</Text>
              </View>
            </View>
          </View>
          <Image source={IMG.tanker} resizeMode="cover" accessibilityLabel="Volvo FH fuel tanker" style={s.s18} />
          {v.barwonSel ? (
            <View style={s.s19} pointerEvents="none" />
          ) : null}
          {v.barwonSel ? (
            <View style={s.s20}>
              <Text style={s.s21}>Driving today</Text>
            </View>
          ) : null}
        </Pressable>
        <Pressable onPress={v.push_B5} style={s.s26}>
          <View style={s.s27}>
            <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M12 6v12M6 12h12" />
            </Svg>
          </View>
          <View style={s.s3}>
            <Text style={s.s28}>
              Add a company
            </Text>
            <Text style={s.s29}>
              Use the driver ID and password they issued you
            </Text>
          </View>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M9 6l6 6-6 6" />
          </Svg>
        </Pressable>
        <Pressable onPress={v.toggleRemember} style={s.s30}>
          {v.rememberOff ? (
            <View style={s.s31} />
          ) : null}
          {v.remember ? (
            <View style={s.s32}>
              <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M5 12.5l4.5 4.5L19 7" />
              </Svg>
            </View>
          ) : null}
          <Text style={s.s33}>
            Remember for today
          </Text>
        </Pressable>
        <View style={s.s3} />
        {v.canContinue ? (
          <Pressable onPress={v.rep_A27} style={s.s34}>
            <Text style={s.s35}>Continue</Text>
          </Pressable>
        ) : null}
        {v.cannotContinue ? (
          <View style={s.s36}>
            <Text style={s.s37}>Continue</Text>
          </View>
        ) : null}
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "flex-start",
    backgroundColor: "#FFFFFF",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 8,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 8,
    paddingTop: 4,
  },
  s3: {
    flex: 1,
  },
  s4: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 30,
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  s7: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s8: {
    alignItems: "flex-start",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexDirection: "row",
    gap: 14,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    position: "relative",
    width: "100%",
  },
  s9: {
    alignItems: "center",
    backgroundColor: "#0E2033",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s10: {
    color: "#F5A21E",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 16,
    letterSpacing: 0.64,
    lineHeight: 16,
    textAlign: "left",
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
    textAlign: "left",
  },
  s12: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
    textAlign: "left",
  },
  s13: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
  },
  s14: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 999,
    flexDirection: "row",
    height: 24,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s15: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s16: {
    alignItems: "center",
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    height: 24,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s17: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 12,
    textAlign: "left",
  },
  s18: {
    borderRadius: 12,
    flexGrow: 0,
    flexShrink: 0,
    height: 64,
    width: 64,
  },
  s19: {
    borderColor: "#2563EB",
    borderRadius: 16,
    borderWidth: 2,
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  s20: {
    backgroundColor: "#2563EB",
    borderRadius: 999,
    height: 22,
    left: 14,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
    position: "absolute",
    top: -8,
  },
  s21: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 22,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s22: {
    alignItems: "center",
    backgroundColor: "#0EA5A4",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s23: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 16,
    letterSpacing: 0.64,
    lineHeight: 16,
    textAlign: "left",
  },
  s24: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 999,
    flexDirection: "row",
    height: 24,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s25: {
    color: "#B45309",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s26: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "#94A3B8",
    borderRadius: 16,
    borderStyle: "dashed",
    borderWidth: 1.5,
    flexDirection: "row",
    gap: 12,
    paddingBottom: 14,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 14,
    width: "100%",
  },
  s27: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s28: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s29: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s30: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 48,
    paddingBottom: 0,
    paddingLeft: 4,
    paddingRight: 4,
    paddingTop: 0,
  },
  s31: {
    backgroundColor: "#FFFFFF",
    borderColor: "#94A3B8",
    borderRadius: 6,
    borderWidth: 1.75,
    flexGrow: 0,
    flexShrink: 0,
    height: 22,
    width: 22,
  },
  s32: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 6,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 22,
    justifyContent: "center",
    width: 22,
  },
  s33: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "left",
  },
  s34: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s35: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s36: {
    backgroundColor: "#E2E8F0",
    borderRadius: 12,
    flexShrink: 0,
    height: 56,
    width: "100%",
  },
  s37: {
    color: "#94A3B8",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 56,
    textAlign: "center",
  },
});
