// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA26_S2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <View style={s.s2}>
        <Text style={s.s3}>
          Good morning, Dave
        </Text>
        <Text style={s.s4}>
          Who are you driving for today?
        </Text>
      </View>
      <ScrollView style={s.s5} contentContainerStyle={s.s6} showsVerticalScrollIndicator={false}>
        <View style={s.s7}>
          <View style={s.s8}>
            <Text style={s.s9}>RF</Text>
          </View>
          <View style={s.s5}>
            <Text style={s.s10}>
              Redgum Freightlines
            </Text>
            <Text style={s.s11}>
              Laverton VIC
            </Text>
          </View>
        </View>
        <View style={s.s12}>
          <View style={s.s13}>
            <View style={s.s14}>
              <Text style={s.s15}>BF</Text>
            </View>
            <View style={s.s5}>
              <View style={s.s16}>
                <Text style={s.s17}>Invitation</Text>
              </View>
              <Text style={s.s18}>
                Barwon Fuel Haulage has invited you
              </Text>
              <Text style={s.s19}>
                Casual work out of Corio VIC. Accepting adds their run sheet and their checks to this phone.
              </Text>
            </View>
          </View>
          <View style={s.s20}>
            <Pressable onPress={v.acceptInvite} style={s.s21}>
              <Text style={s.s22}>Accept</Text>
            </Pressable>
            <Pressable onPress={v.rep_A26} style={s.s23}>
              <Text style={s.s24}>Decline</Text>
            </Pressable>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    backgroundColor: "#FFFFFF",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexGrow: 0,
    flexShrink: 0,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 4,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 30,
  },
  s4: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  s5: {
    flex: 1,
  },
  s6: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    width: "100%",
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#0E2033",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s9: {
    color: "#F5A21E",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 16,
    lineHeight: 16,
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s12: {
    backgroundColor: "#FEF6E9",
    borderColor: "#F5A21E",
    borderRadius: 16,
    borderWidth: 1,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    position: "relative",
    width: "100%",
  },
  s13: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 14,
  },
  s14: {
    alignItems: "center",
    backgroundColor: "#0EA5A4",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s15: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 16,
    lineHeight: 16,
  },
  s16: {
    alignItems: "center",
    backgroundColor: "#F5A21E",
    borderRadius: 999,
    flexDirection: "row",
    height: 22,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s17: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textTransform: "uppercase",
  },
  s18: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
    marginTop: 8,
  },
  s19: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  s20: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  s21: {
    alignItems: "center",
    backgroundColor: "#0F1B2A",
    borderRadius: 12,
    borderWidth: 0,
    flex: 1,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
  },
  s22: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "center",
  },
  s23: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
  },
  s24: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "center",
  },
});
