// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { TabBar } from '@/proto/components/TabBar';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA27() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { paddingTop: insets.top }]}>
        <View style={s.s2}>
          <Pressable onPress={v.openCompany} style={s.s3}>
            <Text style={s.s4}>
              {v.opName}
            </Text>
            <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#F5A21E" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M4 8h13l-3-3" />
              <Path d="M20 16H7l3 3" />
            </Svg>
          </Pressable>
          <View style={s.s5} />
          <Pressable onPress={v.openNotifications} style={s.s6}>
            <Svg width={24} height={24} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M18 8.5a6 6 0 0 0-12 0c0 6.5-2.5 8.5-2.5 8.5h17S18 15 18 8.5" />
              <Path d="M13.7 20.5a2 2 0 0 1-3.4 0" />
            </Svg>
            <View style={s.s7} />
          </Pressable>
        </View>
        <View style={s.s8}>
          <Text style={s.s9}>Good morning, Dave</Text>
        </View>
        <View style={s.s10}>
          <Text style={s.s11}>Wednesday 8 July · Clocked off</Text>
        </View>
      </View>
      <ScrollView style={s.s5} contentContainerStyle={s.s12} showsVerticalScrollIndicator={false}>
        <Pressable onPress={v.open_A27_M1} style={s.s13}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#0F1B2A" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
            <Circle cx="12" cy="12" r="9" />
            <Path d="M12 7.5V12l3 2" />
          </Svg>
          <Text style={s.s14}>Clock on</Text>
        </Pressable>
        <View style={s.s15}>
          <Pressable onPress={v.openTimesheetShift} style={s.s16}>
            <Text style={s.s17}>
              This shift
            </Text>
            <Text style={s.s18}>
              00:00
            </Text>
            <Text style={s.s19}>
              Not started
            </Text>
          </Pressable>
          <Pressable onPress={v.openTimesheetWeek} style={s.s16}>
            <Text style={s.s17}>
              This week
            </Text>
            <Text style={s.s20}>
              31 h 45 m
            </Text>
            <Text style={s.s19}>
              4 days worked
            </Text>
          </Pressable>
          <Pressable onPress={v.push_A5} style={s.s16}>
            <Text style={s.s17}>
              Next job
            </Text>
            <Text style={s.s21}>
              CN-48213
            </Text>
            <Text style={s.s22}>
              09:30
            </Text>
          </Pressable>
        </View>
        <View style={s.s23}>
          <View style={s.s24}>
            <View style={s.s5}>
              <View style={s.s2}>
                <Text style={s.s25}>
                  Looking for work
                </Text>
              </View>
            </View>
            <Pressable onPress={v.open_A27_M3} style={s.s26}>
              <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.75" strokeLinecap="round">
                <Circle cx="12" cy="12" r="9" />
                <Path d="M12 11v5" />
                <Path d="M12 8h.01" />
              </Svg>
            </Pressable>
            <Pressable onPress={v.toggleAvail} style={s.s27}>
              {v.availableOff ? (
                <View style={s.s28}>
                  <View style={s.s29} />
                </View>
              ) : null}
              {v.available ? (
                <View style={s.s30}>
                  <View style={s.s29} />
                </View>
              ) : null}
            </Pressable>
          </View>
          {v.availHelpOff ? (
            <Text style={s.s31}>
              Off means no operator can see you. Turn it on to take extra work around your Redgum shifts.
            </Text>
          ) : null}
          {v.availHelpOn ? (
            <Pressable onPress={v.openOffers} style={s.s32}>
              <View style={s.s5}>
                <Text style={s.s33}>3 operators have offered you work</Text>
              </View>
              <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#166534" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M9 6l6 6-6 6" />
              </Svg>
            </Pressable>
          ) : null}
        </View>
      </ScrollView>
      <TabBar active="run" onRun={v.tabRun} onNav={v.tab_A6} onComp={v.tab_A25} onMsg={v.tab_A22} onProf={v.tab_A34} />
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#0E2033",
    flexGrow: 0,
    flexShrink: 0,
    paddingBottom: 20,
    paddingLeft: 12,
    paddingRight: 12,
  },
  s2: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  s3: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,.1)",
    borderColor: "rgba(255,255,255,.16)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    height: 36,
    paddingBottom: 0,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 0,
  },
  s4: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    lineHeight: 13,
  },
  s5: {
    flex: 1,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    position: "relative",
    width: 44,
  },
  s7: {
    backgroundColor: "#DC2626",
    borderColor: "#0E2033",
    borderRadius: 999,
    borderWidth: 2,
    height: 9,
    position: "absolute",
    right: 9,
    top: 9,
    width: 9,
  },
  s8: {
    marginTop: 14,
    paddingBottom: 0,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 0,
  },
  s9: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 32,
    lineHeight: 36,
  },
  s10: {
    marginTop: 2,
    paddingBottom: 0,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 0,
  },
  s11: {
    color: "rgba(255,255,255,.62)",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s12: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 16,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#F5A21E",
    borderRadius: 12,
    borderWidth: 0,
    boxShadow: "0 4px 14px rgba(245,162,30,.36)",
    flexDirection: "row",
    flexShrink: 0,
    gap: 10,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s14: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
  },
  s15: {
    flexDirection: "row",
    gap: 10,
  },
  s16: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 12,
  },
  s17: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s18: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 24,
    lineHeight: 26,
    marginTop: 8,
    textAlign: "left",
  },
  s19: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 2,
    textAlign: "left",
  },
  s20: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
    marginTop: 8,
    textAlign: "left",
  },
  s21: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 14,
    lineHeight: 18,
    marginTop: 10,
    textAlign: "left",
  },
  s22: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
    textAlign: "left",
  },
  s23: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s24: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  s25: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 24,
  },
  s26: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s27: {
    backgroundColor: "transparent",
    borderWidth: 0,
    flexGrow: 0,
    flexShrink: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  s28: {
    alignItems: "center",
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    flexDirection: "row",
    height: 32,
    paddingBottom: 3,
    paddingLeft: 3,
    paddingRight: 3,
    paddingTop: 3,
    width: 52,
  },
  s29: {
    backgroundColor: "#fff",
    borderRadius: 999,
    boxShadow: "0 1px 3px rgba(15,27,42,.28)",
    height: 26,
    width: 26,
  },
  s30: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexDirection: "row",
    height: 32,
    justifyContent: "flex-end",
    paddingBottom: 3,
    paddingLeft: 3,
    paddingRight: 3,
    paddingTop: 3,
    width: 52,
  },
  s31: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  s32: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
    width: "100%",
  },
  s33: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "left",
  },
});
