// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path, Rect } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { TabBar } from '@/proto/components/TabBar';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA27_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { paddingTop: insets.top }]}>
        <View style={s.s2}>
          <Pressable onPress={v.openCompany} style={s.s3}>
            <Text style={s.s4}>
              {v.opName}
            </Text>
            <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#F5A21E" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M4 8h13l-3-3" />
              <Path d="M20 16H7l3 3" />
            </Svg>
          </Pressable>
          <View style={s.s5} />
          <Pressable onPress={v.push_A22} style={s.s6}>
            <Svg width={24} height={24} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M18 8.5a6 6 0 0 0-12 0c0 6.5-2.5 8.5-2.5 8.5h17S18 15 18 8.5" />
              <Path d="M13.7 20.5a2 2 0 0 1-3.4 0" />
            </Svg>
            <View style={s.s7} />
          </Pressable>
        </View>
        <View style={s.s8}>
          <Text style={s.s9}>Good morning, Dave</Text>
        </View>
        <View style={s.s10}>
          <Text style={s.s11}>Wednesday 8 July</Text>
        </View>
      </View>
      <View style={s.s12}>
        <Anim name="pulseDot" duration={2000} loop style={s.s13} />
        <Text style={s.s14}>
          On duty since 06:12, Laverton VIC
        </Text>
      </View>
      <ScrollView style={s.s5} contentContainerStyle={s.s15} showsVerticalScrollIndicator={false}>
        <View style={s.s16}>
          <Pressable onPress={v.push_A21} style={s.s17}>
            <Text style={s.s18}>
              This shift
            </Text>
            <Text style={s.s19}>
              02:47
            </Text>
            <Text style={s.s20}>
              On duty
            </Text>
          </Pressable>
          <Pressable onPress={v.push_A21} style={s.s17}>
            <Text style={s.s18}>
              This week
            </Text>
            <Text style={s.s21}>
              34 h 32 m
            </Text>
            <Text style={s.s22}>
              Under the limit
            </Text>
          </Pressable>
          <Pressable onPress={v.push_A5} style={s.s17}>
            <Text style={s.s18}>
              Next job
            </Text>
            <Text style={s.s23}>
              CN-48213
            </Text>
            <Text style={s.s24}>
              09:30
            </Text>
          </Pressable>
        </View>
        <View style={s.s25}>
          <Text style={s.s26}>
            Before your run
          </Text>
          <Pressable onPress={v.push_A16} style={s.s27}>
            <View style={s.s28}>
              <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#B45309" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M12 21s-7-4.4-7-9.6A4.4 4.4 0 0 1 12 8a4.4 4.4 0 0 1 7 3.4C19 16.6 12 21 12 21z" />
              </Svg>
            </View>
            <View style={s.s5}>
              <Text style={s.s29}>
                Fit for Duty
              </Text>
              <Text style={s.s30}>
                4 questions and a photo
              </Text>
            </View>
            <View style={s.s31}>
              <Text style={s.s32}>Required</Text>
            </View>
            <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.gatePrestart} style={s.s33}>
            <View style={s.s34}>
              <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
                <Rect x="5" y="11" width={14} height={9} rx="2" />
                <Path d="M8 11V8a4 4 0 0 1 8 0v3" />
              </Svg>
            </View>
            <View style={s.s5}>
              <Text style={s.s35}>
                Pre start inspection
              </Text>
              <Text style={s.s36}>
                16 checks on 1RG4XT
              </Text>
            </View>
            <View style={s.s37}>
              <Text style={s.s38}>Locked</Text>
            </View>
          </Pressable>
        </View>
        <Pressable onPress={v.takeBreak} style={s.s39}>
          <Text style={s.s40}>Take a break</Text>
        </Pressable>
        <Pressable onPress={v.open_A27_M2} style={s.s41}>
          <Text style={s.s40}>Clock off</Text>
        </Pressable>
      </ScrollView>
      <TabBar active="run" onRun={v.tabRun} onNav={v.tab_A6} onComp={v.tab_A25} onMsg={v.tab_A22} onProf={v.tab_A34} />
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#0E2033",
    flexGrow: 0,
    flexShrink: 0,
    paddingBottom: 20,
    paddingLeft: 12,
    paddingRight: 12,
  },
  s2: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  s3: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,.1)",
    borderColor: "rgba(255,255,255,.16)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    height: 36,
    paddingBottom: 0,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 0,
  },
  s4: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    lineHeight: 13,
  },
  s5: {
    flex: 1,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    position: "relative",
    width: 44,
  },
  s7: {
    backgroundColor: "#DC2626",
    borderColor: "#0E2033",
    borderRadius: 999,
    borderWidth: 2,
    height: 9,
    position: "absolute",
    right: 9,
    top: 9,
    width: 9,
  },
  s8: {
    marginTop: 14,
    paddingBottom: 0,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 0,
  },
  s9: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 32,
    lineHeight: 36,
  },
  s10: {
    marginTop: 2,
    paddingBottom: 0,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 0,
  },
  s11: {
    color: "rgba(255,255,255,.62)",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderBottomColor: "#BBF7D0",
    borderBottomWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
  },
  s13: {
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 10,
    width: 10,
  },
  s14: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 20,
  },
  s15: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 16,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s16: {
    flexDirection: "row",
    gap: 10,
  },
  s17: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 12,
  },
  s18: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s19: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 24,
    lineHeight: 26,
    marginTop: 8,
    textAlign: "left",
  },
  s20: {
    color: "#16A34A",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 2,
    textAlign: "left",
  },
  s21: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
    marginTop: 8,
    textAlign: "left",
  },
  s22: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 2,
    textAlign: "left",
  },
  s23: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 14,
    lineHeight: 18,
    marginTop: 10,
    textAlign: "left",
  },
  s24: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
    textAlign: "left",
  },
  s25: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s26: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s27: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
    minHeight: 64,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s28: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s29: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "left",
  },
  s30: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s31: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 999,
    flexDirection: "row",
    height: 24,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s32: {
    color: "#B45309",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s33: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s34: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s35: {
    color: "#94A3B8",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "left",
  },
  s36: {
    color: "#94A3B8",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s37: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderRadius: 999,
    flexDirection: "row",
    height: 24,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s38: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s39: {
    alignItems: "center",
    backgroundColor: "#F5A21E",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s40: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s41: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
});
