// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, TextInput, StyleSheet } from 'react-native';
import Svg, { Circle, Path, Rect } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA29() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Start unscheduled work" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <Pressable onPress={v.open_A29_M1} style={s.s4}>
          <View style={s.s2}>
            <Text style={s.s5}>
              Reason
            </Text>
            <Text style={s.s6}>
              {v.reason}
            </Text>
          </View>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M9 6l6 6-6 6" />
          </Svg>
        </Pressable>
        <Pressable onPress={v.open_A29_M2} style={s.s7}>
          <View style={s.s8}>
            <Svg width="100%" height={150} viewBox="0 0 360 150" preserveAspectRatio="xMidYMid slice">
              <Rect width={360} height={150} fill="#F5EFE2" />
              <Rect x="232" y="8" width={120} height={52} rx="6" fill="#EAF0E4" />
              <Path d="M-10 108C60 96 96 44 176 44S300 74 372 40" stroke="#E3D8C2" strokeWidth="15" fill="none" strokeLinecap="round" />
              <Path d="M52 -10C68 46 40 96 66 170" stroke="#E9E1D0" strokeWidth="9" fill="none" />
              <Path d="M258 -10C266 52 300 96 282 170" stroke="#E9E1D0" strokeWidth="9" fill="none" />
              <Path d="M-10 66H372" stroke="#EDE6D7" strokeWidth="5" fill="none" />
              <Path d="M-10 108C60 96 96 44 176 44S300 74 372 40" stroke="#F5A21E" strokeWidth="3.5" strokeDasharray="9 7" fill="none" strokeLinecap="round" />
              <Circle cx="176" cy="44" r="13" fill="#F5A21E" />
              <Circle cx="176" cy="44" r="4.5" fill="#0F1B2A" />
            </Svg>
          </View>
          <View style={s.s9}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.9" strokeLinecap="round">
              <Path d="M20 10.5c0 5.4-8 11-8 11s-8-5.6-8-11a8 8 0 0 1 16 0z" />
              <Circle cx="12" cy="10.5" r="2.4" />
            </Svg>
            <Text style={s.s10}>
              Corio VIC, 2 Kirkwood Road · 14:02
            </Text>
          </View>
        </Pressable>
        <View style={s.s11}>
          <Text style={s.s12}>
            Odometer
          </Text>
          <TextInput style={s.s13} defaultValue="684 210" />
        </View>
        <View style={s.s11}>
          <Text style={s.s12}>
            What are you doing
          </Text>
          <TextInput style={s.s14} defaultValue="Collecting 1BF7KQ from the workshop, keys with the service desk" multiline textAlignVertical="top" numberOfLines={3} />
        </View>
        <Pressable onPress={v.startUnscheduled} style={s.s15}>
          <Text style={s.s16}>Start work</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 14,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 14,
    width: "100%",
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    lineHeight: 22,
    marginTop: 2,
    textAlign: "left",
  },
  s7: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    width: "100%",
  },
  s8: {
    height: 150,
    position: "relative",
  },
  s9: {
    alignItems: "center",
    borderTopColor: "#E2E8F0",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 8,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s11: {
    flexDirection: "column",
    flexShrink: 0,
    gap: 6,
  },
  s12: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s13: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "RobotoMono_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s14: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
    width: "100%",
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s16: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
