// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, TextInput, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA29_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <View style={s.s2}>
        <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" strokeWidth="1.75" strokeLinecap="round">
          <Path d="M17.5 18H7a4.5 4.5 0 0 1-.6-8.96A6 6 0 0 1 17 8.6" />
          <Path d="M4 3.5l16.5 17" />
        </Svg>
        <Text style={s.s3}>
          You are offline. Everything here is saved on your phone.
        </Text>
      </View>
      <AppHeader title="Start unscheduled work" showBack={true} onBack={v.back} />
      <ScrollView style={s.s4} contentContainerStyle={s.s5} showsVerticalScrollIndicator={false}>
        <Pressable onPress={v.open_A29_M1} style={s.s6}>
          <View style={s.s4}>
            <Text style={s.s7}>
              Reason
            </Text>
            <Text style={s.s8}>
              {v.reason}
            </Text>
          </View>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M9 6l6 6-6 6" />
          </Svg>
        </Pressable>
        <View style={s.s9}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.75" strokeLinecap="round">
            <Path d="M20 10.5c0 5.4-8 11-8 11s-8-5.6-8-11a8 8 0 0 1 16 0z" />
            <Circle cx="12" cy="10.5" r="2.4" />
          </Svg>
          <Text style={s.s10}>
            Your location is saved on this phone and will sync when you are back online.
          </Text>
        </View>
        <View style={s.s11}>
          <Text style={s.s12}>
            Odometer
          </Text>
          <TextInput style={s.s13} defaultValue="684 210" />
        </View>
        <View style={s.s11}>
          <Text style={s.s12}>
            What are you doing
          </Text>
          <TextInput style={s.s14} defaultValue="Collecting 1BF7KQ from the workshop, keys with the service desk" multiline textAlignVertical="top" numberOfLines={3} />
        </View>
        <Pressable onPress={v.startUnscheduledOffline} style={s.s15}>
          <Text style={s.s16}>Start work</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#16324F",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "center",
    backgroundColor: "#16324F",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 10,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s3: {
    color: "#FFFFFF",
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    lineHeight: 18,
  },
  s4: {
    flex: 1,
  },
  s5: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingBottom: 14,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 14,
    width: "100%",
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s8: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    lineHeight: 22,
    marginTop: 2,
    textAlign: "left",
  },
  s9: {
    alignItems: "flex-start",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  s10: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s11: {
    flexDirection: "column",
    flexShrink: 0,
    gap: 6,
  },
  s12: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s13: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "RobotoMono_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s14: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
    width: "100%",
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s16: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
