// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, TextInput, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useVals } from '@/proto/runtime/vals';
import { LoginBackground } from '@/proto/components/LoginBackground';
import { FleetWordmark } from '@/proto/components/FleetWordmark';

export default function ScreenA2_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <LoginBackground />
      <View style={[s.s1, { height: insets.top }]} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <FleetWordmark />
        <Text style={s.s4}>
          Sign in to start your shift
        </Text>
        <View style={s.s5}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#DC2626" strokeWidth="1.75" strokeLinecap="round">
            <Circle cx="12" cy="12" r="9" />
            <Path d="M12 7.5v5" />
            <Path d="M12 16.2h.01" />
          </Svg>
          <Text style={s.s6}>
            That password did not match. Your email is still here.
          </Text>
        </View>
        <View style={s.s7}>
          <Text style={s.s8}>
            Email
          </Text>
          <TextInput style={s.s9} defaultValue="dave.whitmore@redgum.com.au" keyboardType="email-address" autoCapitalize="none" />
        </View>
        <View style={s.s10}>
          <Text style={s.s8}>
            Password
          </Text>
          <TextInput style={s.s11} defaultValue="····" secureTextEntry />
        </View>
        <Pressable onPress={v.rep_A26} style={s.s12}>
          <Text style={s.s13}>Sign in</Text>
        </Pressable>
        <Pressable onPress={v.open_A2_M1} style={s.s14}>
          <Text style={s.s15}>Forgot password</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    paddingBottom: 32,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 24,
  },
  s4: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 30,
    marginTop: 24,
  },
  s5: {
    alignItems: "flex-start",
    backgroundColor: "#FEF2F2",
    borderColor: "#FCA5A5",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s6: {
    color: "#991B1B",
    fontFamily: "Inter_500Medium",
    fontSize: 14,
    lineHeight: 20,
  },
  s7: {
    flexDirection: "column",
    gap: 6,
    marginTop: 20,
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s9: {
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s10: {
    flexDirection: "column",
    gap: 6,
    marginTop: 16,
  },
  s11: {
    borderColor: "#DC2626",
    borderRadius: 10,
    borderWidth: 1.5,
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 24,
    width: "100%",
  },
  s13: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s14: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    marginTop: 8,
  },
  s15: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 14,
    textAlign: "center",
  },
});
