// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA30_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Job saved" showBack={false} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <Svg width={26} height={26} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
          </View>
          <View>
            <Text style={s.s6}>
              Job added to your run
            </Text>
            <Text style={s.s7}>
              Kate Ryan has been notified
            </Text>
          </View>
        </View>
        <View style={s.s8}>
          <View style={s.s9}>
            <Text style={s.s10}>4</Text>
          </View>
          <View style={s.s2}>
            <Text style={s.s11}>
              Barwon Fuel Haulage
            </Text>
            <Text style={s.s7}>
              Corio VIC · Workshop collection
            </Text>
            <View style={s.s12}>
              <Text style={s.s13}>
                15:00
              </Text>
              <View style={s.s14}>
                <Text style={s.s15}>Added by you</Text>
              </View>
            </View>
          </View>
        </View>
        <Pressable onPress={v.rep_A4} style={s.s16}>
          <Text style={s.s17}>Back to run</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 16,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 24,
    lineHeight: 28,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexDirection: "row",
    gap: 12,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  s9: {
    backgroundColor: "#2563EB",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 28,
    width: 28,
  },
  s10: {
    color: "#fff",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 14,
    lineHeight: 28,
    textAlign: "center",
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 18,
    lineHeight: 22,
  },
  s12: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  s13: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 13,
    lineHeight: 18,
  },
  s14: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 999,
    flexDirection: "row",
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s15: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textTransform: "uppercase",
  },
  s16: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s17: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
