// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, TextInput, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA31_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Comments" showBack={true} onBack={v.back} />
      <View style={s.s2}>
        <Svg width={44} height={44} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round">
          <Path d="M21 14.5a2 2 0 0 1-2 2H7.5L3.5 20.5V5a2 2 0 0 1 2-2h13.5a2 2 0 0 1 2 2z" />
        </Svg>
        <Text style={s.s3}>
          Nothing here yet
        </Text>
        <Text style={s.s4}>
          Notes you leave stay with this job and this vehicle.
        </Text>
      </View>
      <View style={[s.s5, { paddingBottom: Math.max(12, insets.bottom) }]}>
        <Pressable onPress={v.open_A31_M1} style={s.s6}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M4 8.5h3l1.6-2.4h6.8L17 8.5h3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1z" />
            <Circle cx="12" cy="13" r="3.4" />
          </Svg>
        </Pressable>
        <TextInput style={s.s7} placeholder="Leave a note for the next driver" placeholderTextColor="#94A3B8" />
        <Pressable onPress={v.push_A31} style={s.s8}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M4 12h15" />
            <Path d="M13 6l6 6-6 6" />
          </Svg>
        </Pressable>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "center",
    flex: 1,
    flexDirection: "column",
    gap: 10,
    justifyContent: "center",
    paddingBottom: 32,
    paddingLeft: 32,
    paddingRight: 32,
    paddingTop: 32,
  },
  s3: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
    textAlign: "center",
  },
  s4: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderTopColor: "#E2E8F0",
    borderTopWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 8,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s7: {
    backgroundColor: "#F4F6FA",
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 1,
    color: "#0F1B2A",
    flex: 1,
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    height: 44,
    paddingBottom: 0,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 0,
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 999,
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
});
