// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, Image, StyleSheet } from 'react-native';
import Svg, { Ellipse, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA32() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <View style={s.s2}>
        <Pressable onPress={v.back} style={s.s3}>
          <Svg width={24} height={24} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M15 18l-6-6 6-6" />
          </Svg>
        </Pressable>
        <View style={s.s4}>
          <Text style={s.s5}>Declaration photo</Text>
        </View>
        <View style={s.s6} />
      </View>
      <View style={s.s7}>
        <Image source={IMG.driver} resizeMode="cover" accessibilityLabel="Camera view" style={s.s8} />
        <View pointerEvents="none" style={s.s9} />
        <Svg width="100%" height="100%" viewBox="0 0 393 520" preserveAspectRatio="none">
          <Ellipse cx="196" cy="240" rx="118" ry="158" fill="none" stroke="#F5A21E" strokeWidth="2.5" strokeDasharray="14 10" />
        </Svg>
        <View style={s.s10}>
          <Text style={s.s11}>Take a photo for your declaration</Text>
        </View>
      </View>
      <View style={s.s12}>
        <Pressable onPress={v.open_A32_M1} style={s.s13}>
          <View style={s.s14} />
        </Pressable>
        <Pressable onPress={v.t_flip} style={s.s15}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M4 9a8 8 0 0 1 13-3l3 3" />
            <Path d="M20 15a8 8 0 0 1-13 3l-3-3" />
            <Path d="M20 4v5h-5M4 20v-5h5" />
          </Svg>
        </Pressable>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#0B1520",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "center",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 56,
    paddingBottom: 0,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 0,
  },
  s3: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  s4: {
    flex: 1,
  },
  s5: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "center",
  },
  s6: {
    width: 48,
  },
  s7: {
    flex: 1,
    overflow: "hidden",
    position: "relative",
  },
  s8: {
    bottom: 0,
    height: "100%",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    width: "100%",
  },
  s9: {
    backgroundColor: "rgba(0, 0, 0, 0.38)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  s10: {
    bottom: 20,
    left: 0,
    position: "absolute",
    right: 0,
  },
  s11: {
    color: "rgba(255,255,255,.9)",
    fontFamily: "Inter_500Medium",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#0B1520",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 150,
    justifyContent: "center",
    position: "relative",
  },
  s13: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "rgba(255,255,255,.35)",
    borderRadius: 999,
    borderWidth: 4,
    flexDirection: "row",
    height: 74,
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    width: 74,
  },
  s14: {
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    height: 58,
    width: 58,
  },
  s15: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,.12)",
    borderRadius: 999,
    borderWidth: 0,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    position: "absolute",
    right: 36,
    width: 48,
  },
});
