// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { TabBar } from '@/proto/components/TabBar';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA34() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { paddingTop: insets.top }]}>
        <Pressable onPress={v.push_A32} style={s.s2}>
          <Image source={IMG.driver} resizeMode="cover" accessibilityLabel="Dave Whitmore" style={s.s3} />
          <View style={s.s4}>
            <Svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M4 8.5h3l1.6-2.4h6.8L17 8.5h3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1z" />
              <Circle cx="12" cy="13" r="3.4" />
            </Svg>
          </View>
        </Pressable>
        <View style={s.s5}>
          <Text style={s.s6}>
            Dave Whitmore
          </Text>
          <Text style={s.s7}>
            MC licence, Victoria
          </Text>
        </View>
      </View>
      <ScrollView style={s.s5} contentContainerStyle={s.s8} showsVerticalScrollIndicator={false}>
        <View style={s.s9}>
          <Pressable onPress={v.push_A34_M1} style={s.s10}>
            <View style={s.s5}>
              <Text style={s.s11}>My companies</Text>
            </View>
            <Text style={s.s12}>
              2
            </Text>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.push_A34_M2} style={s.s10}>
            <View style={s.s5}>
              <Text style={s.s11}>Notification preferences</Text>
            </View>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.openOffers} style={s.s10}>
            <View style={s.s5}>
              <Text style={s.s11}>Looking for work</Text>
            </View>
            {v.availHelpOn ? (
              <View style={s.s13}>
                <Text style={s.s14}>3 offers</Text>
              </View>
            ) : null}
            {v.availHelpOff ? (
              <Text style={s.s12}>
                Off
              </Text>
            ) : null}
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.push_B4} style={s.s10}>
            <View style={s.s5}>
              <Text style={s.s11}>My file and compliance</Text>
            </View>
            <View style={s.s15}>
              <Text style={s.s16}>1 expired</Text>
            </View>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.push_A23} style={s.s10}>
            <View style={s.s5}>
              <Text style={s.s11}>Document wallet</Text>
            </View>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.push_A24} style={s.s10}>
            <View style={s.s5}>
              <Text style={s.s11}>Offline sync</Text>
            </View>
            <View style={s.s17}>
              <Text style={s.s18}>3</Text>
            </View>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.push_A19} style={s.s10}>
            <View style={s.s5}>
              <Text style={s.s11}>Fuel and odometer</Text>
            </View>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.push_A17} style={s.s10}>
            <View style={s.s5}>
              <Text style={s.s11}>Report an incident</Text>
            </View>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.t_help} style={s.s19}>
            <View style={s.s5}>
              <Text style={s.s11}>Help</Text>
            </View>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
        </View>
        <Pressable onPress={v.open_A34_M3} style={s.s20}>
          <Text style={s.s21}>Sign out</Text>
        </Pressable>
        <Text style={s.s22}>
          FleetSync 4.2.0 · Records held by each operator for three years
        </Text>
      </ScrollView>
      <TabBar active="profile" onRun={v.tabRun} onNav={v.tab_A6} onComp={v.tab_A25} onMsg={v.tab_A22} onProf={v.tab_A34} />
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    alignItems: "center",
    backgroundColor: "#0E2033",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 16,
    paddingBottom: 24,
    paddingLeft: 20,
    paddingRight: 20,
  },
  s2: {
    backgroundColor: "transparent",
    borderWidth: 0,
    flexGrow: 0,
    flexShrink: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    position: "relative",
  },
  s3: {
    borderColor: "rgba(255,255,255,.2)",
    borderRadius: 999,
    borderWidth: 2,
    height: 72,
    width: 72,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderColor: "#0E2033",
    borderRadius: 999,
    borderWidth: 2,
    bottom: -2,
    flexDirection: "row",
    height: 26,
    justifyContent: "center",
    position: "absolute",
    right: -2,
    width: 26,
  },
  s5: {
    flex: 1,
  },
  s6: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 30,
  },
  s7: {
    color: "rgba(255,255,255,.62)",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  s8: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s9: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s10: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 60,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "left",
  },
  s12: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "left",
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 999,
    flexDirection: "row",
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s14: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderRadius: 999,
    flexDirection: "row",
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s16: {
    color: "#991B1B",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s17: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 999,
    flexDirection: "row",
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s18: {
    color: "#B45309",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s19: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 60,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
    width: "100%",
  },
  s20: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s21: {
    color: "#DC2626",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s22: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
});
