// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA34_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="My companies" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <Text style={s.s6}>RF</Text>
          </View>
          <View style={s.s2}>
            <Text style={s.s7}>
              Redgum Freightlines
            </Text>
            <Text style={s.s8}>
              Laverton VIC
            </Text>
            <View style={s.s9}>
              <Text style={s.s10}>Full time</Text>
            </View>
          </View>
          <Pressable onPress={v.leaveRedgum} style={s.s11}>
            <Text style={s.s12}>Leave</Text>
          </Pressable>
        </View>
        <View style={s.s4}>
          <View style={s.s13}>
            <Text style={s.s14}>BF</Text>
          </View>
          <View style={s.s2}>
            <Text style={s.s7}>
              Barwon Fuel Haulage
            </Text>
            <Text style={s.s8}>
              Corio VIC
            </Text>
            <View style={s.s15}>
              <Text style={s.s16}>Casual</Text>
            </View>
          </View>
          <Pressable onPress={v.leaveBarwon} style={s.s11}>
            <Text style={s.s12}>Leave</Text>
          </Pressable>
        </View>
        <View style={s.s17}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.8" strokeLinecap="round">
            <Circle cx="12" cy="12" r="9" />
            <Path d="M12 11v5" />
            <Path d="M12 8h.01" />
          </Svg>
          <Text style={s.s18}>
            Leaving removes your access to that operator. It does not delete your records, they stay with the operator for three years.
          </Text>
        </View>
        <Pressable onPress={v.push_B5} style={s.s19}>
          <Text style={s.s20}>Add a company</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "flex-start",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#0E2033",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s6: {
    color: "#F5A21E",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 16,
    lineHeight: 16,
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s9: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 999,
    flexDirection: "row",
    height: 24,
    marginTop: 10,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s10: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textTransform: "uppercase",
  },
  s11: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  s12: {
    color: "#DC2626",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#0EA5A4",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s14: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 16,
    lineHeight: 16,
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 999,
    flexDirection: "row",
    height: 24,
    marginTop: 10,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s16: {
    color: "#B45309",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textTransform: "uppercase",
  },
  s17: {
    alignItems: "flex-start",
    backgroundColor: "#EEF3F9",
    borderRadius: 12,
    flexDirection: "row",
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s18: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s19: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s20: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
