// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA35() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View>
          <Text style={s.s4}>
            Three things FleetSync needs
          </Text>
          <Text style={s.s5}>
            Each one is used only while you are on duty.
          </Text>
        </View>
        <View style={s.s6}>
          <View style={s.s7}>
            <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M20 10.5c0 5.4-8 11-8 11s-8-5.6-8-11a8 8 0 0 1 16 0z" />
              <Circle cx="12" cy="10.5" r="2.6" />
            </Svg>
          </View>
          <View>
            <Text style={s.s8}>
              Location
            </Text>
            <Text style={s.s9}>
              So your start, stops and deliveries are recorded.
            </Text>
          </View>
        </View>
        <View style={s.s6}>
          <View style={s.s7}>
            <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M4 8.5h3l1.6-2.4h6.8L17 8.5h3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1z" />
              <Circle cx="12" cy="13" r="3.4" />
            </Svg>
          </View>
          <View>
            <Text style={s.s8}>
              Camera
            </Text>
            <Text style={s.s9}>
              For declaration photos, defects and proof of delivery.
            </Text>
          </View>
        </View>
        <View style={s.s6}>
          <View style={s.s7}>
            <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M18 8.5a6 6 0 0 0-12 0c0 6.5-2.5 8.5-2.5 8.5h17S18 15 18 8.5" />
              <Path d="M13.7 20.5a2 2 0 0 1-3.4 0" />
            </Svg>
          </View>
          <View>
            <Text style={s.s8}>
              Notifications
            </Text>
            <Text style={s.s9}>
              So you know when a job changes.
            </Text>
          </View>
        </View>
        <View style={s.s2} />
        <Pressable onPress={v.open_A35_M1} style={s.s10}>
          <Text style={s.s11}>Continue</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 20,
    paddingBottom: 24,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 24,
  },
  s4: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 30,
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  s6: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 14,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s8: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 22,
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 2,
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s11: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
