// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, Image, TextInput, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA36() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Your details" sub="Used on every record you sign" showBack={false} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <Pressable onPress={v.push_A32} style={s.s5}>
            <Image source={IMG.driver} resizeMode="cover" accessibilityLabel="Dave Whitmore" style={s.s6} />
            <View style={s.s7}>
              <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M4 8.5h3l1.6-2.4h6.8L17 8.5h3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1z" />
                <Circle cx="12" cy="13" r="3.4" />
              </Svg>
            </View>
          </Pressable>
        </View>
        <View style={s.s8}>
          <Text style={s.s9}>
            Licence number
          </Text>
          <TextInput style={s.s10} defaultValue="042 118 663" />
        </View>
        <View style={s.s8}>
          <Text style={s.s9}>
            Licence expiry
          </Text>
          <TextInput style={s.s10} defaultValue="01/08/2026" />
        </View>
        <View style={s.s8}>
          <Text style={s.s9}>
            Mobile
          </Text>
          <TextInput style={s.s11} defaultValue="0412 884 190" />
        </View>
        <View style={s.s8}>
          <Text style={s.s9}>
            Emergency contact
          </Text>
          <TextInput style={s.s11} defaultValue="Julie Whitmore, 0413 220 771" />
        </View>
        <Pressable onPress={v.rep_A26} style={s.s12}>
          <Text style={s.s13}>Save and continue</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 16,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    flexDirection: "row",
    justifyContent: "center",
  },
  s5: {
    backgroundColor: "transparent",
    borderWidth: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    position: "relative",
  },
  s6: {
    borderColor: "#FFFFFF",
    borderRadius: 999,
    borderWidth: 3,
    boxShadow: "0 4px 12px rgba(15,27,42,.12)",
    height: 96,
    width: 96,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderColor: "#F4F6FA",
    borderRadius: 999,
    borderWidth: 3,
    bottom: -2,
    flexDirection: "row",
    height: 34,
    justifyContent: "center",
    position: "absolute",
    right: -2,
    width: 34,
  },
  s8: {
    flexDirection: "column",
    flexShrink: 0,
    gap: 6,
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s10: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "RobotoMono_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s11: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 4,
    width: "100%",
  },
  s13: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
