// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { TabBar } from '@/proto/components/TabBar';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA4() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Today's run" sub="Wednesday 8 July" showBack={false} rightPlus={true} onRight={v.push_A30} />
      <View style={s.s2}>
        <View style={s.s3}>
          <Text style={s.s4}>
            Stops
          </Text>
          <Text style={s.s5}>
            3
          </Text>
        </View>
        <View style={s.s3}>
          <Text style={s.s4}>
            Distance
          </Text>
          <Text style={s.s5}>
            812 km
          </Text>
        </View>
        <View style={s.s3}>
          <Text style={s.s4}>
            Finish
          </Text>
          <Text style={s.s5}>
            16:40
          </Text>
        </View>
      </View>
      <ScrollView style={s.s6} contentContainerStyle={s.s7} showsVerticalScrollIndicator={false}>
        {v.stopsOrdered.map((st, stI) => (
            <React.Fragment key={stI}>
            <View style={s.s8}>
              <Pressable onPress={st.open} style={s.s9}>
                <View style={s.s10}>
                  <Text style={s.s11}>{st.n}</Text>
                </View>
                <View style={s.s6}>
                  <Text style={s.s12}>
                    {st.customer}
                  </Text>
                  <Text style={s.s13}>
                    {st.site} · {st.pallets}
                  </Text>
                  <View style={s.s14}>
                    <Text style={s.s15}>
                      {st.window}
                    </Text>
                    {st.amber ? (
                      <View style={s.s16}>
                        <Text style={s.s17}>{st.status}</Text>
                      </View>
                    ) : null}
                    {st.muted ? (
                      <View style={s.s18}>
                        <Text style={s.s19}>{st.status}</Text>
                      </View>
                    ) : null}
                  </View>
                </View>
                {st.i0 ? (
                  <Image source={IMG.palletsDock} resizeMode="cover" accessibilityLabel="Loading dock" style={s.s20} />
                ) : null}
                {st.i1 ? (
                  <Image source={IMG.depotYard} resizeMode="cover" accessibilityLabel="Depot yard" style={s.s20} />
                ) : null}
                {st.i2 ? (
                  <Image source={IMG.highway} resizeMode="cover" accessibilityLabel="Highway" style={s.s20} />
                ) : null}
              </Pressable>
              <Pressable onPress={st.more} style={s.s21}>
                <Svg width={16} height={16} viewBox="0 0 24 24" fill="#2563EB">
                  <Circle cx="5" cy="12" r="2" />
                  <Circle cx="12" cy="12" r="2" />
                  <Circle cx="19" cy="12" r="2" />
                </Svg>
                <Text style={s.s22}>Stop actions</Text>
              </Pressable>
            </View>
            </React.Fragment>
        ))}
        <Pressable onPress={v.push_A7} style={s.s23}>
          <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#0F1B2A" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M4 7h11M4 12h7M4 17h13" />
            <Path d="M18 5v8l3-3" />
          </Svg>
          <Text style={s.s24}>Order your stops</Text>
        </Pressable>
      </ScrollView>
      <TabBar active="run" onRun={v.tabRun} onNav={v.tab_A6} onComp={v.tab_A25} onMsg={v.tab_A22} onProf={v.tab_A34} />
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    backgroundColor: "#0E2033",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    paddingBottom: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
  },
  s3: {
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
  },
  s4: {
    color: "rgba(255,255,255,.5)",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.8,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s5: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
  },
  s6: {
    flex: 1,
  },
  s7: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    overflow: "hidden",
  },
  s9: {
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
    width: "100%",
  },
  s10: {
    backgroundColor: "#0E2033",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 28,
    width: 28,
  },
  s11: {
    color: "#fff",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 14,
    lineHeight: 28,
    textAlign: "center",
  },
  s12: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 18,
    lineHeight: 22,
    textAlign: "left",
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 1,
    textAlign: "left",
  },
  s14: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  s15: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s16: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 999,
    flexDirection: "row",
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s17: {
    color: "#B45309",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s18: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s19: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s20: {
    borderRadius: 12,
    flexGrow: 0,
    flexShrink: 0,
    height: 56,
    width: 56,
  },
  s21: {
    alignItems: "center",
    backgroundColor: "#FCFDFE",
    borderTopColor: "#E2E8F0",
    borderTopWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 6,
    height: 44,
    justifyContent: "center",
    width: "100%",
  },
  s22: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    lineHeight: 13,
  },
  s23: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    gap: 8,
    height: 52,
    justifyContent: "center",
    width: "100%",
  },
  s24: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 15,
  },
});
