// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { Path, Polygon, Rect } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA5() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Coastline Grocers" sub="CN-48213" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <Text style={s.s5}>
            Status
          </Text>
          {v.statusRows.map((t, tI) => (
              <React.Fragment key={tI}>
              <Pressable onPress={t.openStatus} style={s.s6}>
                {t.done ? (
                  <View style={s.s7}>
                    <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round">
                      <Path d="M5 12.5l4.5 4.5L19 7" />
                    </Svg>
                  </View>
                ) : null}
                {t.current ? (
                  <View style={s.s8} />
                ) : null}
                {t.later ? (
                  <View style={s.s9} />
                ) : null}
                <View style={s.s2}>
                  <Text style={s.s10}>
                    {t.label}
                  </Text>
                  <Text style={s.s11}>
                    {t.note}
                  </Text>
                </View>
                <View style={s.s12}>
                  <Text style={s.s13}>{t.at}</Text>
                </View>
              </Pressable>
              </React.Fragment>
          ))}
        </View>
        <Pressable onPress={v.push_A5_M1} style={s.s14}>
          <View style={s.s15}>
            <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#B45309" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 11l3 3 5-6" />
              <Rect x="4" y="4" width={16} height={16} rx="3" />
            </Svg>
          </View>
          <View style={s.s2}>
            <Text style={s.s10}>
              Pre check for this job
            </Text>
            <Text style={s.s16}>
              3 of 6 complete
            </Text>
          </View>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#B45309" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M9 6l6 6-6 6" />
          </Svg>
        </Pressable>
        <View style={s.s17}>
          <View style={s.s18}>
            <Text style={s.s19}>
              Pallets
            </Text>
            <Text style={s.s20}>
              22
            </Text>
          </View>
          <View style={s.s18}>
            <Text style={s.s19}>
              Window
            </Text>
            <Text style={s.s20}>
              09:30 to 11:00
            </Text>
          </View>
          <Pressable onPress={v.open_A5_M2} style={s.s21}>
            <Text style={s.s19}>
              Site contact
            </Text>
            <View style={s.s22}>
              <Text style={s.s23}>
                Marco Ferretti
              </Text>
              <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M9 6l6 6-6 6" />
              </Svg>
            </View>
          </Pressable>
          <Pressable onPress={v.open_A5_M3} style={s.s21}>
            <Text style={s.s19}>
              Documents
            </Text>
            <View style={s.s22}>
              <Text style={s.s23}>
                3
              </Text>
              <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M9 6l6 6-6 6" />
              </Svg>
            </View>
          </Pressable>
          <Pressable onPress={v.push_A31} style={s.s24}>
            <Text style={s.s19}>
              Comments
            </Text>
            <View style={s.s25}>
              <Image source={IMG.allocator} resizeMode="cover" accessibilityLabel="Kate Ryan" style={s.s26} />
              <Image source={IMG.driver} resizeMode="cover" accessibilityLabel="Dave Whitmore" style={s.s27} />
              <Text style={s.s23}>
                2
              </Text>
              <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M9 6l6 6-6 6" />
              </Svg>
            </View>
          </Pressable>
        </View>
        <View style={s.s28}>
          <Pressable onPress={v.push_A6} style={s.s29}>
            <Svg width={24} height={24} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
              <Polygon points="3 11 21 3 13 21 11 13 3 11" />
            </Svg>
          </Pressable>
          <Pressable onPress={v.arrived} style={s.s30}>
            <Text style={s.s31}>I have arrived</Text>
          </Pressable>
        </View>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  s6: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 8,
    width: "100%",
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  s8: {
    backgroundColor: "#F5A21E",
    borderColor: "#FEF6E9",
    borderRadius: 999,
    borderWidth: 4,
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    width: 24,
  },
  s9: {
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 2,
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    width: 24,
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "left",
  },
  s12: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s14: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderColor: "#F5A21E",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    gap: 12,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    width: "100%",
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s16: {
    color: "#B45309",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s17: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s18: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 52,
  },
  s19: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 20,
  },
  s20: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
  s21: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 52,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    width: "100%",
  },
  s22: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  s23: {
    color: "#0F1B2A",
    fontFamily: "Inter_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
  s24: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 52,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    width: "100%",
  },
  s25: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  s26: {
    borderRadius: 999,
    height: 24,
    width: 24,
  },
  s27: {
    borderRadius: 999,
    height: 24,
    marginLeft: -14,
    width: 24,
  },
  s28: {
    flexDirection: "row",
    gap: 10,
  },
  s29: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: 56,
  },
  s30: {
    alignItems: "center",
    backgroundColor: "#F5A21E",
    borderRadius: 12,
    borderWidth: 0,
    flex: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
  },
  s31: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
