// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA5_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Job pre check" sub="CN-48213 · 6 items" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          {v.checkRows.map((r, rI) => (
              <React.Fragment key={rI}>
              <View style={s.s5}>
                <View style={s.s2}>
                  <Text style={s.s6}>
                    {r.name}
                  </Text>
                  <View>
                    <Pressable onPress={r.fail} style={s.s7}>
                      <Text style={s.s8}>Add comment</Text>
                    </Pressable>
                  </View>
                </View>
                <Pressable onPress={r.pass} style={s.s9}>
                  {r.isPass ? (
                    <View style={s.s10}>
                      <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round">
                        <Path d="M5 12.5l4.5 4.5L19 7" />
                      </Svg>
                    </View>
                  ) : null}
                  {r.notPass ? (
                    <View style={s.s11}>
                      <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                        <Path d="M5 12.5l4.5 4.5L19 7" />
                      </Svg>
                    </View>
                  ) : null}
                </Pressable>
                <Pressable onPress={r.fail} style={s.s9}>
                  {r.isFail ? (
                    <View style={s.s12}>
                      <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.6" strokeLinecap="round">
                        <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
                      </Svg>
                    </View>
                  ) : null}
                  {r.notFail ? (
                    <View style={s.s11}>
                      <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2.2" strokeLinecap="round">
                        <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
                      </Svg>
                    </View>
                  ) : null}
                </Pressable>
              </View>
              </React.Fragment>
          ))}
        </View>
        <Pressable onPress={v.back} style={s.s13}>
          <Text style={s.s14}>Done</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s5: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 64,
    paddingBottom: 12,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 12,
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s7: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 2,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  s8: {
    color: "#2563EB",
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  s9: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    width: 44,
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 12,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s11: {
    alignItems: "center",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1.5,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#DC2626",
    borderRadius: 12,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s14: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
