// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { TabBar } from '@/proto/components/TabBar';
import { useVals } from '@/proto/runtime/vals';
import { InteractiveFleetMap } from '@/proto/components/InteractiveFleetMap';

export default function ScreenA6() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={s.s1}>
        <View style={s.s2}>
          <InteractiveFleetMap expanded={v.zoomK !== 1} />
        </View>
        <View style={[s.s3, { top: insets.top }]}>
          <Pressable onPress={v.t_voice} style={s.s4}>
            <Svg width={38} height={38} viewBox="0 0 24 24" fill="none" stroke="#F5A21E" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M12 20V8a4 4 0 0 1 4-4h2" />
              <Path d="M15 7l3-3-3-3" />
            </Svg>
            <View style={s.s5}>
              <Text style={s.s6}>
                In 2.4 km
              </Text>
              <Text style={s.s7}>
                Take the M31 south
              </Text>
            </View>
          </Pressable>
        </View>
        <Pressable onPress={v.toggleZoom} style={s.s8}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#0F1B2A" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5" />
          </Svg>
        </Pressable>
        <View style={s.s9}>
          <Pressable onPress={v.push_A18} style={s.s4}>
            <View style={s.s5}>
              <Text style={s.s10}>
                Remaining
              </Text>
              <Text style={s.s11}>
                284 km · ETA 11:04
              </Text>
            </View>
            <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M9 6l6 6-6 6" />
            </Svg>
          </Pressable>
          <View style={s.s12}>
            <Pressable onPress={v.open_A6_M1} style={s.s13}>
              <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#166534" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M5 12.5l4.5 4.5L19 7" />
              </Svg>
              <Text style={s.s14}>Heavy vehicle route</Text>
            </Pressable>
            <View style={s.s5} />
            <Pressable onPress={v.back} style={s.s15}>
              <Text style={s.s16}>End</Text>
            </Pressable>
          </View>
        </View>
      </View>
      <TabBar active="navigate" onRun={v.tabRun} onNav={v.tab_A6} onComp={v.tab_A25} onMsg={v.tab_A22} onProf={v.tab_A34} />
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F5EFE2",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flex: 1,
    overflow: "hidden",
    position: "relative",
  },
  s2: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  s3: {
    backgroundColor: "#0E2033",
    borderRadius: 16,
    boxShadow: "0 8px 24px rgba(15,27,42,.28)",
    left: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    position: "absolute",
    right: 16,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    gap: 14,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    width: "100%",
  },
  s5: {
    flex: 1,
  },
  s6: {
    color: "rgba(255,255,255,.6)",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s7: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
    textAlign: "left",
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 0,
    boxShadow: "0 4px 14px rgba(15,27,42,.18)",
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    position: "absolute",
    right: 16,
    top: 150,
    width: 48,
  },
  s9: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    bottom: 16,
    boxShadow: "0 8px 24px rgba(15,27,42,.16)",
    left: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    position: "absolute",
    right: 16,
  },
  s10: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 24,
    lineHeight: 28,
    marginTop: 2,
    textAlign: "left",
  },
  s12: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderColor: "#BBF7D0",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    height: 30,
    paddingBottom: 0,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 0,
  },
  s14: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 12,
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    height: 36,
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
  },
  s16: {
    color: "#DC2626",
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    lineHeight: 13,
    textAlign: "center",
  },
});
