// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA7() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Order your stops" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          {v.reorderRows.map((r, rI) => (
              <React.Fragment key={rI}>
              <View style={s.s5}>
                <View style={s.s6}>
                  <Text style={s.s7}>{r.n}</Text>
                </View>
                <View style={s.s2}>
                  <Text style={s.s8}>
                    {r.customer}
                  </Text>
                  <Text style={s.s9}>
                    {r.site} · {r.window}
                  </Text>
                </View>
                <View style={s.s10}>
                  <Pressable onPress={r.up} style={s.s11}>
                    <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                      <Path d="M6 14l6-6 6 6" />
                    </Svg>
                  </Pressable>
                  <Pressable onPress={r.down} style={s.s11}>
                    <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                      <Path d="M6 10l6 6 6-6" />
                    </Svg>
                  </Pressable>
                </View>
              </View>
              </React.Fragment>
          ))}
        </View>
        <View style={s.s12}>
          <View style={s.s13}>
            <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M12 3v3M12 18v3M3 12h3M18 12h3" />
              <Circle cx="12" cy="12" r="4" />
            </Svg>
            <Text style={s.s8}>
              Reordering saves 34 km and 41 minutes
            </Text>
          </View>
          <Text style={s.s14}>
            Albury before Wodonga keeps you off the Hume in the afternoon peak.
          </Text>
        </View>
        <Pressable onPress={v.open_A7_M1} style={s.s15}>
          <Text style={s.s16}>Use suggested order</Text>
        </Pressable>
        <Pressable onPress={v.back} style={s.s17}>
          <Text style={s.s18}>Keep my order</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    paddingBottom: 4,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 4,
  },
  s5: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 64,
    paddingBottom: 10,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 10,
  },
  s6: {
    backgroundColor: "#0E2033",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 26,
    width: 26,
  },
  s7: {
    color: "#fff",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 13,
    lineHeight: 26,
    textAlign: "center",
  },
  s8: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
  },
  s10: {
    flexDirection: "column",
    flexGrow: 0,
    flexShrink: 0,
  },
  s11: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    height: 32,
    justifyContent: "center",
    width: 44,
  },
  s12: {
    backgroundColor: "#EEF3F9",
    borderColor: "#BFD5EE",
    borderRadius: 16,
    borderWidth: 1,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s13: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  s14: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s16: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s17: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s18: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
