// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA8() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Job status" sub="CN-48213" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        {v.statusRows.map((t, tI) => (
            <React.Fragment key={tI}>
            <Pressable onPress={t.open} style={s.s4}>
              {t.done ? (
                <View style={s.s5}>
                  <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                    <Path d="M5 12.5l4.5 4.5L19 7" />
                  </Svg>
                </View>
              ) : null}
              {t.current ? (
                <View style={s.s6} />
              ) : null}
              {t.later ? (
                <View style={s.s7} />
              ) : null}
              <View style={s.s2}>
                <Text style={s.s8}>
                  {t.label}
                </Text>
                <Text style={s.s9}>
                  {t.note}
                </Text>
              </View>
              <View style={s.s10}>
                <Text style={s.s11}>{t.at}</Text>
              </View>
            </Pressable>
            </React.Fragment>
        ))}
        <View style={s.s12}>
          <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.8" strokeLinecap="round">
            <Path d="M20 10.5c0 5.4-8 11-8 11s-8-5.6-8-11a8 8 0 0 1 16 0z" />
            <Circle cx="12" cy="10.5" r="2.4" />
          </Svg>
          <Text style={s.s13}>
            Every change is timestamped and geotagged.
          </Text>
        </View>
        <Pressable onPress={v.push_A10} style={s.s14}>
          <Text style={s.s15}>Scan pallets</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 10,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    minHeight: 72,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    width: "100%",
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  s6: {
    backgroundColor: "#F5A21E",
    borderColor: "#FEF6E9",
    borderRadius: 999,
    borderWidth: 5,
    flexGrow: 0,
    flexShrink: 0,
    height: 32,
    width: 32,
  },
  s7: {
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 2,
    flexGrow: 0,
    flexShrink: 0,
    height: 32,
    width: 32,
  },
  s8: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
    textAlign: "left",
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s10: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 14,
    lineHeight: 18,
    textAlign: "left",
  },
  s12: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
    paddingBottom: 4,
    paddingLeft: 4,
    paddingRight: 4,
    paddingTop: 4,
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s14: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s15: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
