// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA8_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <View style={s.s2}>
        <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" strokeWidth="1.75" strokeLinecap="round">
          <Path d="M17.5 18H7a4.5 4.5 0 0 1-.6-8.96A6 6 0 0 1 17 8.6" />
          <Path d="M4 3.5l16.5 17" />
        </Svg>
        <Text style={s.s3}>
          Offline. Status changes are queued.
        </Text>
      </View>
      <AppHeader title="Job status" sub="CN-48213" showBack={true} onBack={v.back} />
      <ScrollView style={s.s4} contentContainerStyle={s.s5} showsVerticalScrollIndicator={false}>
        {v.statusRows.map((t, tI) => (
            <React.Fragment key={tI}>
            <View style={s.s6}>
              {t.done ? (
                <View style={s.s7}>
                  <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                    <Path d="M5 12.5l4.5 4.5L19 7" />
                  </Svg>
                </View>
              ) : null}
              {t.current ? (
                <View style={s.s8} />
              ) : null}
              {t.later ? (
                <View style={s.s9} />
              ) : null}
              <View style={s.s4}>
                <Text style={s.s10}>
                  {t.label}
                </Text>
                <Text style={s.s11}>
                  {t.note}
                </Text>
              </View>
              {t.current ? (
                <View style={s.s12}>
                  <Text style={s.s13}>Queued</Text>
                </View>
              ) : null}
            </View>
            </React.Fragment>
        ))}
        <Pressable onPress={v.push_A24} style={s.s14}>
          <Text style={s.s15}>Open offline sync</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#16324F",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "center",
    backgroundColor: "#16324F",
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 10,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  s3: {
    color: "#FFFFFF",
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    lineHeight: 18,
  },
  s4: {
    flex: 1,
  },
  s5: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 10,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    minHeight: 72,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    width: "100%",
  },
  s7: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  s8: {
    backgroundColor: "#F5A21E",
    borderColor: "#FEF6E9",
    borderRadius: 999,
    borderWidth: 5,
    flexGrow: 0,
    flexShrink: 0,
    height: 32,
    width: 32,
  },
  s9: {
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 2,
    flexGrow: 0,
    flexShrink: 0,
    height: 32,
    width: 32,
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#F4F6FA",
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textTransform: "uppercase",
  },
  s14: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s15: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
