// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, Image, TextInput, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA9() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Proof of delivery" sub="CN-48213" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <Text style={s.s6}>
              Pallets delivered
            </Text>
            <Text style={s.s7}>
              22 of 22
            </Text>
          </View>
          <View style={s.s8}>
            <View style={s.s9}>
              <Text style={s.s6}>Received by</Text>
            </View>
            <TextInput style={s.s10} defaultValue="M Ferretti" />
          </View>
        </View>
        <Pressable onPress={v.push_A9_M1} style={s.s11}>
          {v.noSig ? (
            <View style={s.s12}>
              <Svg width={26} height={26} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M3 19c3 0 4-8 7-8s3 5 5 5 2-3 6-3" />
              </Svg>
              <Text style={s.s13}>Tap to sign</Text>
            </View>
          ) : null}
          {v.sig ? (
            <View style={s.s14}>
              <Svg width="100%" height={150} viewBox="0 0 320 150">
                <Path d="M30 104c14-30 26-46 34-44s6 34 16 38 16-40 28-40 8 34 20 36 20-30 34-32 22 18 34 14 24-18 30-24" fill="none" stroke="#0F1B2A" strokeWidth="3" strokeLinecap="round" />
              </Svg>
              <View style={s.s15}>
                <Text style={s.s16}>M Ferretti · 11:52</Text>
              </View>
            </View>
          ) : null}
        </Pressable>
        <View style={s.s17}>
          <View style={s.s19}>
            <Image source={IMG.palletsDock} resizeMode="cover" accessibilityLabel="Delivered pallets" style={s.s20} />
          </View>
          <Pressable onPress={v.push_A9_M2} style={s.s21}>
            <Svg width={24} height={24} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="1.75" strokeLinecap="round">
              <Path d="M12 6v12M6 12h12" />
            </Svg>
            <Text style={s.s22}>Add photo</Text>
          </Pressable>
        </View>
        <Pressable onPress={v.open_A9_M3} style={s.s23}>
          <Text style={s.s24}>Add a closing comment</Text>
        </Pressable>
        <Pressable onPress={v.completeDelivery} style={s.s25}>
          <Text style={s.s26}>Complete delivery</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s5: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 52,
  },
  s6: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 20,
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
  s8: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    minHeight: 52,
  },
  s9: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s10: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 8,
    borderWidth: 1,
    color: "#0F1B2A",
    flex: 1,
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    height: 40,
    paddingBottom: 0,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 0,
    textAlign: "right",
  },
  s11: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#94A3B8",
    borderRadius: 16,
    borderStyle: "dashed",
    borderWidth: 1.5,
    flexDirection: "row",
    height: 150,
    justifyContent: "center",
    overflow: "hidden",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    width: "100%",
  },
  s12: {
    alignItems: "center",
    flexDirection: "column",
    gap: 8,
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "Inter_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
  s14: {
    height: "100%",
    position: "relative",
    width: "100%",
  },
  s15: {
    bottom: 8,
    position: "absolute",
    right: 12,
  },
  s16: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 11,
    lineHeight: 16,
  },
  s17: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
  },
  s18: {
    aspectRatio: 1.333,
    borderRadius: 12,
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
  },
  s19: {
    aspectRatio: 1.333,
    borderRadius: 12,
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    overflow: "hidden",
  },
  s20: {
    height: "100%",
    width: "100%",
  },
  s21: {
    alignItems: "center",
    aspectRatio: 1.333,
    backgroundColor: "#FFFFFF",
    borderColor: "#94A3B8",
    borderRadius: 12,
    borderStyle: "dashed",
    borderWidth: 1.5,
    flexBasis: 0,
    flexDirection: "column",
    flexGrow: 1,
    flexShrink: 1,
    gap: 6,
    justifyContent: "center",
  },
  s22: {
    color: "#5B6B7F",
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    lineHeight: 18,
  },
  s23: {
    backgroundColor: "transparent",
    borderWidth: 0,
    height: 48,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  s24: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "left",
  },
  s25: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s26: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
