// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA9_M1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Signature" sub="Coastline Grocers, Wodonga DC" showBack={true} onBack={v.back} />
      <View style={s.s2}>
        <Svg width="100%" height="100%" viewBox="0 0 393 520" preserveAspectRatio="none">
          <Path d="M40 320h313" stroke="#E2E8F0" strokeWidth="2" strokeDasharray="6 6" />
          <Path d="M70 300c26-56 48-86 62-82s12 62 30 70 30-74 52-74 14 62 36 66 38-56 62-60" fill="none" stroke="#0F1B2A" strokeWidth="4" strokeLinecap="round" />
        </Svg>
        <View style={s.s3}>
          <Text style={s.s4}>Sign above the line</Text>
        </View>
      </View>
      <View style={[s.s5, { paddingBottom: Math.max(28, insets.bottom) }]}>
        <Pressable onPress={v.clearSig} style={s.s6}>
          <Text style={s.s7}>Clear</Text>
        </Pressable>
        <Pressable onPress={v.setSig} style={s.s8}>
          <Text style={s.s9}>Done</Text>
        </Pressable>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    position: "relative",
  },
  s3: {
    bottom: 150,
    left: 40,
    position: "absolute",
  },
  s4: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 12,
    lineHeight: 18,
  },
  s5: {
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 10,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 16,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s8: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flex: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
  },
  s9: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
