// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenA9_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { paddingTop: insets.top }]}>
        <View style={s.s2}>
          <Svg width={26} height={26} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M5 12.5l4.5 4.5L19 7" />
          </Svg>
        </View>
        <Text style={s.s3}>
          CN-48213 delivered
        </Text>
        <Text style={s.s4}>
          11:52 · Wodonga DC, Victoria
        </Text>
      </View>
      <ScrollView style={s.s5} contentContainerStyle={s.s6} showsVerticalScrollIndicator={false}>
        <View style={s.s7}>
          <View style={s.s8}>
            <Text style={s.s9}>
              Pallets
            </Text>
            <Text style={s.s10}>
              22 of 22
            </Text>
          </View>
          <View style={s.s8}>
            <Text style={s.s9}>
              Received by
            </Text>
            <Text style={s.s11}>
              M Ferretti
            </Text>
          </View>
          <View style={s.s8}>
            <Text style={s.s9}>
              Signature
            </Text>
            <View style={s.s12}>
              <Text style={s.s13}>Captured</Text>
            </View>
          </View>
          <View style={s.s14}>
            <Text style={s.s9}>
              Photos
            </Text>
            <Text style={s.s10}>
              1
            </Text>
          </View>
        </View>
        <Pressable onPress={v.nextStop} style={s.s15}>
          <Text style={s.s16}>Next stop</Text>
        </Pressable>
        <Pressable onPress={v.root_A4} style={s.s17}>
          <Text style={s.s18}>Back to run</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#16A34A",
    flexGrow: 0,
    flexShrink: 0,
    paddingBottom: 24,
    paddingLeft: 20,
    paddingRight: 20,
  },
  s2: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,.2)",
    borderRadius: 999,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s3: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 32,
    lineHeight: 36,
    marginTop: 14,
  },
  s4: {
    color: "rgba(255,255,255,.86)",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 2,
  },
  s5: {
    flex: 1,
  },
  s6: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s7: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s8: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 20,
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "Inter_500Medium",
    fontSize: 15,
    lineHeight: 20,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 999,
    flexDirection: "row",
    height: 24,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
  },
  s13: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.66,
    lineHeight: 11,
    textTransform: "uppercase",
  },
  s14: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s16: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s17: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s18: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
