// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, TextInput, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenB1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Create an account" sub="Yours, not an operator's" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.8" strokeLinecap="round">
            <Circle cx="12" cy="12" r="9" />
            <Path d="M12 11v5" />
            <Path d="M12 8h.01" />
          </Svg>
          <Text style={s.s5}>
            Your account and your documents belong to you. Operators are added afterwards, one at a time, and each only sees what you allow.
          </Text>
        </View>
        <View style={s.s6}>
          <Text style={s.s7}>
            Full name
          </Text>
          <TextInput style={s.s8} defaultValue="Dave Whitmore" />
        </View>
        <View style={s.s6}>
          <Text style={s.s7}>
            Mobile
          </Text>
          <TextInput style={s.s8} defaultValue="0412 884 190" />
        </View>
        <View style={s.s6}>
          <Text style={s.s7}>
            Email
          </Text>
          <TextInput style={s.s8} placeholder="you@example.com.au" placeholderTextColor="#94A3B8" />
        </View>
        <View style={s.s9}>
          <View style={s.s10}>
            <Text style={s.s7}>
              Licence number
            </Text>
            <TextInput style={s.s11} defaultValue="042 118 663" />
          </View>
          <View style={s.s12}>
            <Text style={s.s7}>
              Class
            </Text>
            <TextInput style={s.s11} defaultValue="MC" />
          </View>
        </View>
        <View style={s.s6}>
          <Text style={s.s7}>
            State of issue
          </Text>
          <TextInput style={s.s8} defaultValue="Victoria" />
        </View>
        <Pressable onPress={v.registerContinue} style={s.s13}>
          <Text style={s.s14}>Continue to your documents</Text>
        </Pressable>
        <Text style={s.s15}>
          FleetSync checks your licence against VicRoads before any operator can allocate you work.
        </Text>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "flex-start",
    backgroundColor: "#EEF3F9",
    borderRadius: 12,
    flexDirection: "row",
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s5: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s6: {
    flexDirection: "column",
    flexShrink: 0,
    gap: 6,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s9: {
    flexDirection: "row",
    gap: 10,
  },
  s10: {
    flex: 1,
    flexDirection: "column",
    flexShrink: 0,
    gap: 6,
  },
  s11: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0F1B2A",
    flexShrink: 0,
    fontFamily: "RobotoMono_400Regular",
    fontSize: 16,
    height: 52,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 0,
    width: "100%",
  },
  s12: {
    flexDirection: "column",
    flexGrow: 0,
    flexShrink: 0,
    gap: 6,
    width: 96,
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    marginTop: 4,
    width: "100%",
  },
  s14: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
});
