// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenB2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Your file" sub="3 verified, 1 checking, 1 expired, 1 missing" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          {v.fileRows.map((f, fI) => (
              <React.Fragment key={fI}>
              <Pressable onPress={f.open} style={s.s5}>
                <View style={s.s2}>
                  <Text style={s.s6}>
                    {f.n}
                  </Text>
                  <Text style={s.s7}>
                    {f.s}
                  </Text>
                  <View style={s.s8}>
                    {f.isFs ? (
                      <View style={s.s9}>
                        <Svg width={11} height={11} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="3.4" strokeLinecap="round" strokeLinejoin="round">
                          <Path d="M5 12.5l4.5 4.5L19 7" />
                        </Svg>
                        <Text style={s.s10}>Checked by FleetSync</Text>
                      </View>
                    ) : null}
                    {f.isEmp ? (
                      <View style={s.s11}>
                        <Svg width={11} height={11} viewBox="0 0 24 24" fill="none" stroke="#0F766E" strokeWidth="3.4" strokeLinecap="round" strokeLinejoin="round">
                          <Path d="M5 12.5l4.5 4.5L19 7" />
                        </Svg>
                        <Text style={s.s12}>Confirmed by employer</Text>
                      </View>
                    ) : null}
                    {f.isVr ? (
                      <View style={s.s13}>
                        <Svg width={11} height={11} viewBox="0 0 24 24" fill="none" stroke="#166534" strokeWidth="3.4" strokeLinecap="round" strokeLinejoin="round">
                          <Path d="M5 12.5l4.5 4.5L19 7" />
                        </Svg>
                        <Text style={s.s14}>Matched with VicRoads</Text>
                      </View>
                    ) : null}
                    {f.isProg ? (
                      <View style={s.s15}>
                        <Svg width={11} height={11} viewBox="0 0 24 24" fill="none" stroke="#B45309" strokeWidth="3" strokeLinecap="round">
                          <Circle cx="12" cy="12" r="9" />
                          <Path d="M12 7.5V12l3 2" />
                        </Svg>
                        <Text style={s.s16}>Being checked</Text>
                      </View>
                    ) : null}
                    {f.isMissing ? (
                      <View style={s.s17}>
                        <Svg width={11} height={11} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                          <Path d="M12 16V4" />
                          <Path d="M8 8l4-4 4 4" />
                        </Svg>
                        <Text style={s.s18}>Tap to upload</Text>
                      </View>
                    ) : null}
                    {f.isExp ? (
                      <View style={s.s19}>
                        <Text style={s.s20}>Expired</Text>
                      </View>
                    ) : null}
                  </View>
                </View>
                <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <Path d="M9 6l6 6-6 6" />
                </Svg>
              </Pressable>
              </React.Fragment>
          ))}
        </View>
        <Pressable onPress={v.push_B4} style={s.s21}>
          <Text style={s.s22}>Check my compliance</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s5: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 76,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 1,
    textAlign: "left",
  },
  s8: {
    flexDirection: "row",
    marginTop: 8,
  },
  s9: {
    alignItems: "center",
    backgroundColor: "#EEF3F9",
    borderRadius: 999,
    flexDirection: "row",
    gap: 5,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s10: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s11: {
    alignItems: "center",
    backgroundColor: "#F0FDFA",
    borderRadius: 999,
    flexDirection: "row",
    gap: 5,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s12: {
    color: "#0F766E",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 999,
    flexDirection: "row",
    gap: 5,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s14: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 999,
    flexDirection: "row",
    gap: 5,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s16: {
    color: "#B45309",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s17: {
    alignItems: "center",
    borderColor: "#94A3B8",
    borderRadius: 999,
    borderStyle: "dashed",
    borderWidth: 1.5,
    flexDirection: "row",
    gap: 5,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s18: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s19: {
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderRadius: 999,
    flexDirection: "row",
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s20: {
    color: "#991B1B",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textAlign: "left",
    textTransform: "uppercase",
  },
  s21: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s22: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
