// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenB3() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title={v.doc} sub="Verification history" showBack={true} onBack={v.back} rightShare={true} onRight={v.push_B7} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
          </View>
          <View style={s.s2}>
            <Text style={s.s6}>
              Verified and current
            </Text>
            <Text style={s.s7}>
              Nothing for you to do on this one.
            </Text>
          </View>
        </View>
        <View style={s.s8}>
          <View style={s.s9}>
            <View>
              <Text style={s.s10}>
                {v.docKind}
              </Text>
              <Text style={s.s11}>
                {v.docNo}
              </Text>
            </View>
            <Image source={IMG.driver} resizeMode="cover" accessibilityLabel="Dave Whitmore" style={s.s12} />
          </View>
          <View style={s.s13} />
          <View style={s.s14}>
            <View>
              <Text style={s.s15}>
                Issued
              </Text>
              <Text style={s.s16}>
                {v.docIssued}
              </Text>
            </View>
            <View>
              <Text style={s.s15}>
                Expires
              </Text>
              <Text style={s.s16}>
                {v.docExpires}
              </Text>
            </View>
            <View>
              <Text style={s.s15}>
                Issued by
              </Text>
              <Text style={s.s17}>
                {v.docIssuer}
              </Text>
            </View>
          </View>
        </View>
        <View style={s.s18}>
          <Text style={s.s19}>
            Who has checked this
          </Text>
          {v.docByVr ? (
            <View style={s.s20}>
              <View style={s.s21}>
                <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round">
                  <Path d="M5 12.5l4.5 4.5L19 7" />
                </Svg>
              </View>
              <View style={s.s2}>
                <Text style={s.s22}>
                  Matched with VicRoads
                </Text>
                <Text style={s.s23}>
                  Number, class and expiry agree with the register. Rechecked nightly.
                </Text>
                <Text style={s.s24}>
                  13 June 2026, 02:10
                </Text>
              </View>
            </View>
          ) : null}
          {v.docByEmp ? (
            <View style={s.s20}>
              <View style={s.s25}>
                <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round">
                  <Path d="M5 12.5l4.5 4.5L19 7" />
                </Svg>
              </View>
              <View style={s.s2}>
                <Text style={s.s22}>
                  Confirmed by employer
                </Text>
                <Text style={s.s23}>
                  Kate Ryan sighted the original at the Laverton depot and signed for it.
                </Text>
                <Text style={s.s24}>
                  6 July 2026, 07:20
                </Text>
              </View>
            </View>
          ) : null}
          <View style={s.s26}>
            <View style={s.s27}>
              <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M5 12.5l4.5 4.5L19 7" />
              </Svg>
            </View>
            <View style={s.s2}>
              <Text style={s.s22}>
                Checked by FleetSync
              </Text>
              <Text style={s.s23}>
                Image is legible, name matches your account, no signs of alteration.
              </Text>
              <Text style={s.s24}>
                12 June 2026, 16:44
              </Text>
            </View>
          </View>
          <View style={s.s26}>
            <View style={s.s28} />
            <View style={s.s2}>
              <Text style={s.s29}>
                Uploaded by you
              </Text>
              <Text style={s.s24}>
                12 June 2026, 16:41
              </Text>
            </View>
          </View>
        </View>
        {v.docWarn ? (
          <View style={s.s30}>
            <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#B45309" strokeWidth="1.8" strokeLinecap="round">
              <Circle cx="12" cy="12" r="9" />
              <Path d="M12 7.5V12l3 2" />
            </Svg>
            <Text style={s.s31}>
              Expires in 24 days. Replace it before 1 August or Redgum Freightlines cannot allocate you work.
            </Text>
          </View>
        ) : null}
        <Pressable onPress={v.open_B2_M1} style={s.s32}>
          <Text style={s.s33}>Replace this document</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderColor: "#BBF7D0",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    gap: 12,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  s6: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s7: {
    color: "#166534",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    opacity: 0.8,
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderRadius: 6,
    boxShadow: "0 4px 18px rgba(15,27,42,.12)",
    flexShrink: 0,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s9: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 18,
    lineHeight: 22,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 11,
    lineHeight: 16,
  },
  s12: {
    borderRadius: 4,
    flexShrink: 0,
    height: 56,
    width: 44,
  },
  s13: {
    backgroundColor: "#E2E8F0",
    height: 1,
    marginBottom: 14,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 14,
  },
  s14: {
    flexDirection: "row",
    gap: 24,
  },
  s15: {
    color: "#94A3B8",
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    letterSpacing: 0.9,
    lineHeight: 12,
    textTransform: "uppercase",
  },
  s16: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 12,
    lineHeight: 18,
  },
  s17: {
    color: "#0F1B2A",
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 18,
  },
  s18: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s19: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s20: {
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
  },
  s21: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  s22: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s23: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s24: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 2,
  },
  s25: {
    alignItems: "center",
    backgroundColor: "#0EA5A4",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  s26: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  s27: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  s28: {
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 2,
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    width: 24,
  },
  s29: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s30: {
    alignItems: "flex-start",
    backgroundColor: "#FEF6E9",
    borderRadius: 12,
    flexDirection: "row",
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s31: {
    color: "#B45309",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s32: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s33: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
