// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenB3_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title={v.doc} sub="Being checked" showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <Anim name="spin" duration={900} loop style={s.s5} />
          <View style={s.s2}>
            <Text style={s.s6}>
              Being checked now
            </Text>
            <Text style={s.s7}>
              Usually clears by the next business day.
            </Text>
          </View>
        </View>
        <View style={s.s8}>
          <View style={s.s9}>
            <View>
              <Text style={s.s10}>
                {v.docKind}
              </Text>
              <Text style={s.s11}>
                {v.docNo}
              </Text>
            </View>
            <View style={s.s12}>
              <Text style={s.s13}>Not verified yet</Text>
            </View>
          </View>
          <View style={s.s14} />
          <View style={s.s15}>
            <View>
              <Text style={s.s16}>
                Submitted
              </Text>
              <Text style={s.s17}>
                {v.docIssued}
              </Text>
            </View>
            <View>
              <Text style={s.s16}>
                Valid
              </Text>
              <Text style={s.s18}>
                {v.docExpires}
              </Text>
            </View>
          </View>
          <Text style={s.s19}>
            Checked against {v.docIssuer}. Nothing you send is visible to an operator until it clears.
          </Text>
        </View>
        <View style={s.s20}>
          <Text style={s.s21}>
            Where it is up to
          </Text>
          <View style={s.s22}>
            <View style={s.s23}>
              <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M5 12.5l4.5 4.5L19 7" />
              </Svg>
            </View>
            <View style={s.s2}>
              <Text style={s.s6}>
                Uploaded by you
              </Text>
              <Text style={s.s24}>
                6 July 2026, 09:04
              </Text>
            </View>
          </View>
          <View style={s.s25}>
            <View style={s.s26}>
              <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M5 12.5l4.5 4.5L19 7" />
              </Svg>
            </View>
            <View style={s.s2}>
              <Text style={s.s6}>
                Checked by FleetSync
              </Text>
              <Text style={s.s27}>
                Legible, name matches your account.
              </Text>
              <Text style={s.s24}>
                6 July 2026, 09:06
              </Text>
            </View>
          </View>
          <View style={s.s25}>
            <Anim name="spin" duration={900} loop style={s.s28} />
            <View style={s.s2}>
              <Text style={s.s29}>
                Waiting on {v.docIssuer}
              </Text>
              <Text style={s.s27}>
                The register answers in business hours. We retry every 30 minutes.
              </Text>
            </View>
          </View>
          <View style={s.s25}>
            <View style={s.s30} />
            <View style={s.s2}>
              <Text style={s.s31}>
                Added to your verified file
              </Text>
            </View>
          </View>
        </View>
        <View style={s.s32}>
          <Text style={s.s33}>
            While this runs
          </Text>
          <View style={s.s34}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
            <Text style={s.s35}>
              You can keep working. Nothing is blocked today.
            </Text>
          </View>
          <View style={s.s36}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="2" strokeLinecap="round">
              <Circle cx="12" cy="12" r="9" />
              <Path d="M12 11v5" />
              <Path d="M12 8h.01" />
            </Svg>
            <Text style={s.s37}>
              If it fails, we tell you what to send instead. Nobody is notified of a failure except you.
            </Text>
          </View>
        </View>
        <Pressable onPress={v.t_notifyClear} style={s.s38}>
          <Text style={s.s39}>Tell me when it clears</Text>
        </Pressable>
        <Pressable onPress={v.open_B2_M1} style={s.s40}>
          <Text style={s.s41}>Send a clearer copy</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderColor: "#F5A21E",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    gap: 12,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  s5: {
    borderColor: "#FBE0B4",
    borderRadius: 999,
    borderTopColor: "#B45309",
    borderWidth: 3,
    flexGrow: 0,
    flexShrink: 0,
    height: 34,
    width: 34,
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s7: {
    color: "#B45309",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderColor: "#94A3B8",
    borderRadius: 6,
    borderStyle: "dashed",
    borderWidth: 1.5,
    flexShrink: 0,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
    position: "relative",
  },
  s9: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 18,
    lineHeight: 22,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 11,
    lineHeight: 16,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 22,
    paddingBottom: 0,
    paddingLeft: 9,
    paddingRight: 9,
    paddingTop: 0,
  },
  s13: {
    color: "#B45309",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 0.6,
    lineHeight: 10,
    textTransform: "uppercase",
  },
  s14: {
    backgroundColor: "#E2E8F0",
    height: 1,
    marginBottom: 14,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 14,
  },
  s15: {
    flexDirection: "row",
    gap: 24,
  },
  s16: {
    color: "#94A3B8",
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    letterSpacing: 0.9,
    lineHeight: 12,
    textTransform: "uppercase",
  },
  s17: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 12,
    lineHeight: 18,
  },
  s18: {
    color: "#0F1B2A",
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 18,
  },
  s19: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
  },
  s20: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s21: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s22: {
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
  },
  s23: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  s24: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 2,
  },
  s25: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  s26: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  s27: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s28: {
    borderColor: "#FBE0B4",
    borderRadius: 999,
    borderTopColor: "#B45309",
    borderWidth: 3,
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    width: 24,
  },
  s29: {
    color: "#B45309",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s30: {
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 2,
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    width: 24,
  },
  s31: {
    color: "#94A3B8",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s32: {
    backgroundColor: "#EEF3F9",
    borderRadius: 14,
    flexShrink: 0,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  s33: {
    color: "#2563EB",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s34: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  s35: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s36: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  s37: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s38: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s39: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s40: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s41: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
