// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenB4() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="My compliance" sub="Checked 11:41 today" showBack={true} onBack={v.back} rightHelp={true} onRight={v.open_B4_M1} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <Svg width={26} height={26} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
          </View>
          <View style={s.s2}>
            <Text style={s.s6}>
              Cleared for general freight
            </Text>
            <Text style={s.s7}>
              Redgum Freightlines can allocate you work today.
            </Text>
          </View>
        </View>
        <View style={s.s8}>
          <View style={s.s9}>
            <Svg width={24} height={24} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.6" strokeLinecap="round">
              <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
            </Svg>
          </View>
          <View style={s.s2}>
            <Text style={s.s6}>
              Blocked for dangerous goods
            </Text>
            <Text style={s.s10}>
              Your DG licence expired on 2 July, so tanker work at Barwon Fuel Haulage stays closed.
            </Text>
          </View>
        </View>
        <View style={s.s11}>
          {v.fileRows.map((f, fI) => (
              <React.Fragment key={fI}>
              <Pressable onPress={f.open} style={s.s12}>
                {f.bad ? (
                  <View style={s.s13}>
                    <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#DC2626" strokeWidth="3" strokeLinecap="round">
                      <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
                    </Svg>
                  </View>
                ) : null}
                {f.prog ? (
                  <View style={s.s14}>
                    <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#B45309" strokeWidth="2.4" strokeLinecap="round">
                      <Circle cx="12" cy="12" r="9" />
                      <Path d="M12 7.5V12l3 2" />
                    </Svg>
                  </View>
                ) : null}
                {f.ok ? (
                  <View style={s.s15}>
                    <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                      <Path d="M5 12.5l4.5 4.5L19 7" />
                    </Svg>
                  </View>
                ) : null}
                {f.missing ? (
                  <View style={s.s16}>
                    <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round">
                      <Path d="M12 16V4" />
                      <Path d="M8 8l4-4 4 4" />
                    </Svg>
                  </View>
                ) : null}
                <View style={s.s2}>
                  <Text style={s.s17}>
                    {f.n}
                  </Text>
                  <Text style={s.s18}>
                    {f.s}
                  </Text>
                </View>
                <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <Path d="M9 6l6 6-6 6" />
                </Svg>
              </Pressable>
              </React.Fragment>
          ))}
        </View>
        <Pressable onPress={v.push_B7} style={s.s19}>
          <Text style={s.s20}>Share my file with an employer</Text>
        </Pressable>
        <Pressable onPress={v.open_B2_M1} style={s.s21}>
          <Text style={s.s22}>Replace the expired licence</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "flex-start",
    backgroundColor: "#ECFDF3",
    borderColor: "#BBF7D0",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    gap: 14,
    paddingBottom: 18,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 18,
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
  },
  s7: {
    color: "#166534",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  s8: {
    alignItems: "flex-start",
    backgroundColor: "#FEF2F2",
    borderColor: "#FCA5A5",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    gap: 14,
    paddingBottom: 18,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 18,
  },
  s9: {
    alignItems: "center",
    backgroundColor: "#DC2626",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s10: {
    color: "#991B1B",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  s11: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    borderWidth: 0,
    flexDirection: "row",
    gap: 12,
    minHeight: 68,
    paddingBottom: 14,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 14,
    width: "100%",
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  s14: {
    alignItems: "center",
    backgroundColor: "#FEF6E9",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  s15: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  s16: {
    alignItems: "center",
    borderColor: "#94A3B8",
    borderRadius: 999,
    borderStyle: "dashed",
    borderWidth: 1.5,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  s17: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s18: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s19: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s20: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s21: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s22: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
