// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenB6() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Company linked" showBack={false} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <Svg width={30} height={30} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
          </View>
          <Text style={s.s6}>
            Barwon Fuel Haulage linked
          </Text>
          <Text style={s.s7}>
            BFH-2291 · verified 11:41
          </Text>
        </View>
        <View style={s.s8}>
          <Text style={s.s9}>
            What they can see
          </Text>
          <View style={s.s10}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
            <Text style={s.s11}>
              Your verified file and expiry dates
            </Text>
          </View>
          <View style={s.s10}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
            <Text style={s.s11}>
              Work you do for them, and only that work
            </Text>
          </View>
          <View style={s.s12}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#DC2626" strokeWidth="2.6" strokeLinecap="round">
              <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
            </Svg>
            <Text style={s.s13}>
              Nothing from Redgum Freightlines
            </Text>
          </View>
        </View>
        <View style={s.s14}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#DC2626" strokeWidth="1.8" strokeLinecap="round">
            <Circle cx="12" cy="12" r="9" />
            <Path d="M12 7.5v5" />
            <Path d="M12 16.2h.01" />
          </Svg>
          <Text style={s.s15}>
            Barwon run tankers. Your dangerous goods licence expired on 2 July, so they cannot allocate you a tanker until it is replaced.
          </Text>
        </View>
        <Pressable onPress={v.companyLinked} style={s.s16}>
          <Text style={s.s17}>Done</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexDirection: "column",
    gap: 12,
    paddingBottom: 24,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 24,
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderRadius: 999,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: 56,
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 24,
    lineHeight: 28,
    textAlign: "center",
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s10: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 44,
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s12: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    minHeight: 44,
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s14: {
    alignItems: "flex-start",
    backgroundColor: "#FEF2F2",
    borderRadius: 12,
    flexDirection: "row",
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s15: {
    color: "#991B1B",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s16: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s17: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
