// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, Image, StyleSheet } from 'react-native';
import Svg, { G, Path, Rect } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IMG } from '@/proto/theme/images';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenB7() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Share my file" showBack={true} onBack={v.back} rightHelp={true} onRight={v.open_B7_M1} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <Svg width={168} height={168} viewBox="0 0 42 42">
            <Rect width={42} height={42} fill="#FFFFFF" />
            <G fill="#0F1B2A">
              <Path d="M2 2h10v10H2z" />
              <Path d="M30 2h10v10H30z" />
              <Path d="M2 30h10v10H2z" />
            </G>
            <G fill="#FFFFFF">
              <Path d="M4 4h6v6H4z" />
              <Path d="M32 4h6v6H32z" />
              <Path d="M4 32h6v6H4z" />
            </G>
            <G fill="#0F1B2A">
              <Path d="M6 6h2v2H6z" />
              <Path d="M34 6h2v2H34z" />
              <Path d="M6 34h2v2H6z" />
              <Path d="M14 2h2v2h-2z" />
              <Path d="M18 4h2v2h-2z" />
              <Path d="M14 6h4v2h-4z" />
              <Path d="M20 8h2v2h-2z" />
              <Path d="M16 10h2v2h-2z" />
              <Path d="M2 14h2v2H2z" />
              <Path d="M6 14h4v2H6z" />
              <Path d="M4 18h2v2H4z" />
              <Path d="M8 20h2v2H8z" />
              <Path d="M2 22h2v4H2z" />
              <Path d="M14 14h4v4h-4z" />
              <Path d="M20 16h2v2h-2z" />
              <Path d="M24 14h2v4h-2z" />
              <Path d="M28 16h4v2h-4z" />
              <Path d="M34 14h2v2h-2z" />
              <Path d="M38 16h2v4h-2z" />
              <Path d="M14 20h2v2h-2z" />
              <Path d="M18 22h4v2h-4z" />
              <Path d="M24 20h4v2h-4z" />
              <Path d="M30 22h2v2h-2z" />
              <Path d="M34 20h4v2h-4z" />
              <Path d="M14 24h2v4h-2z" />
              <Path d="M20 26h2v2h-2z" />
              <Path d="M26 24h4v2h-4z" />
              <Path d="M32 26h2v2h-2z" />
              <Path d="M36 24h2v2h-2z" />
              <Path d="M16 30h4v2h-4z" />
              <Path d="M22 30h2v4h-2z" />
              <Path d="M28 30h2v2h-2z" />
              <Path d="M34 30h4v2h-4z" />
              <Path d="M14 34h2v2h-2z" />
              <Path d="M18 36h4v2h-4z" />
              <Path d="M26 34h2v4h-2z" />
              <Path d="M32 36h2v2h-2z" />
              <Path d="M36 34h2v2h-2z" />
              <Path d="M30 36h2v2h-2z" />
              <Path d="M8 24h2v2H8z" />
              <Path d="M6 26h2v2H6z" />
            </G>
          </Svg>
          <Text style={s.s5}>
            Hold this up at the gate or in an interview. It opens your verified file, nothing else.
          </Text>
        </View>
        <View style={s.s6}>
          <Text style={s.s7}>
            Link
          </Text>
          <Text style={s.s8}>
            fleetsync.com.au/file/dw-042118663
          </Text>
          <Text style={s.s9}>
            Stays open for
          </Text>
          <View style={s.s10}>
            {v.shareRows.map((w, wI) => (
                <React.Fragment key={wI}>
                <Pressable onPress={w.pick} style={s.s11}>
                  {w.on ? (
                    <View style={s.s12}>
                      <Text style={s.s13}>{w.label}</Text>
                    </View>
                  ) : null}
                  {w.off ? (
                    <View style={s.s14}>
                      <Text style={s.s15}>{w.label}</Text>
                    </View>
                  ) : null}
                </Pressable>
                </React.Fragment>
            ))}
          </View>
        </View>
        <View style={s.s16}>
          <View style={s.s17}>
            <Image source={IMG.allocator} resizeMode="cover" accessibilityLabel="Kate Ryan" style={s.s18} />
            <View style={s.s2}>
              <Text style={s.s19}>Kate Ryan opened it</Text>
            </View>
            <Text style={s.s20}>
              6 July
            </Text>
          </View>
          <View style={s.s21}>
            <View style={s.s22}>
              <Text style={s.s23}>BF</Text>
            </View>
            <View style={s.s2}>
              <Text style={s.s19}>Barwon Fuel Haulage opened it</Text>
            </View>
            <Text style={s.s20}>
              1 July
            </Text>
          </View>
        </View>
        <Pressable onPress={v.copyLink} style={s.s24}>
          <Text style={s.s25}>Copy the link</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexDirection: "column",
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s5: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  s6: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s7: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s8: {
    color: "#2563EB",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },
  s9: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    marginTop: 16,
    textTransform: "uppercase",
  },
  s10: {
    backgroundColor: "#E2E8F0",
    borderRadius: 12,
    flexDirection: "row",
    gap: 4,
    marginTop: 8,
    paddingBottom: 4,
    paddingLeft: 4,
    paddingRight: 4,
    paddingTop: 4,
  },
  s11: {
    backgroundColor: "transparent",
    borderRadius: 9,
    borderWidth: 0,
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    height: 44,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  s12: {
    alignItems: "center",
    backgroundColor: "#0F1B2A",
    borderRadius: 9,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
  },
  s13: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 12,
  },
  s14: {
    alignItems: "center",
    borderRadius: 9,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 12,
  },
  s16: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s17: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 56,
  },
  s18: {
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 36,
    width: 36,
  },
  s19: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s20: {
    color: "#5B6B7F",
    fontFamily: "RobotoMono_400Regular",
    fontSize: 12,
    lineHeight: 16,
  },
  s21: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    minHeight: 56,
  },
  s22: {
    alignItems: "center",
    backgroundColor: "#F0FDFA",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  s23: {
    color: "#0F766E",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 13,
    lineHeight: 13,
  },
  s24: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s25: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
