// Generated by tools/prototype/generate.mjs — do not edit by hand.
import React from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { AppHeader } from '@/proto/components/AppHeader';
import { TabBar } from '@/proto/components/TabBar';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenC2() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Offers" sub="Visible to 12 operators near Laverton" showBack={true} onBack={v.back} rightHelp={true} onRight={v.open_C2_M1} />
      <View style={s.s2}>
        <Anim name="pulseDot" duration={2000} loop style={s.s3} />
        <View style={s.s4}>
          <Text style={s.s5}>Looking for work since 08:12</Text>
        </View>
        <Pressable onPress={v.open_C2_M1} style={s.s6}>
          <Text style={s.s7}>Settings</Text>
        </Pressable>
      </View>
      <ScrollView style={s.s4} contentContainerStyle={s.s8} showsVerticalScrollIndicator={false}>
        {v.offerRows.map((o, oI) => (
            <React.Fragment key={oI}>
            <Pressable onPress={o.open} style={s.s9}>
              <View style={s.s10}>
                {o.isViolet ? (
                  <View style={s.s11}>
                    <Text style={s.s12}>{o.mark}</Text>
                  </View>
                ) : null}
                {o.isTeal ? (
                  <View style={s.s13}>
                    <Text style={s.s12}>{o.mark}</Text>
                  </View>
                ) : null}
                <View style={s.s4}>
                  <Text style={s.s14}>
                    {o.op}
                  </Text>
                  <Text style={s.s15}>
                    {o.kind}
                  </Text>
                  <Text style={s.s15}>
                    {o.dist}
                  </Text>
                </View>
              </View>
              <View style={s.s16}>
                <View style={s.s4}>
                  <Text style={s.s17}>{o.when}</Text>
                </View>
                <View style={s.s18}>
                  <Text style={s.s19}>{o.rate}</Text>
                </View>
              </View>
              {o.blocked ? (
                <View style={s.s20}>
                  <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#DC2626" strokeWidth="2.6" strokeLinecap="round">
                    <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
                  </Svg>
                  <Text style={s.s21}>
                    {o.block}
                  </Text>
                </View>
              ) : null}
              {o.ok ? (
                <View style={s.s22}>
                  <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
                    <Path d="M5 12.5l4.5 4.5L19 7" />
                  </Svg>
                  <Text style={s.s23}>
                    Your file meets everything they ask for
                  </Text>
                </View>
              ) : null}
            </Pressable>
            </React.Fragment>
        ))}
        <View style={s.s24}>
          <Text style={s.s25}>Offers expire if you do not answer. Declining is private, the operator only sees that you passed.</Text>
        </View>
      </ScrollView>
      <TabBar active="run" onRun={v.tabRun} onNav={v.tab_A6} onComp={v.tab_A25} onMsg={v.tab_A22} onProf={v.tab_A34} />
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderBottomColor: "#BBF7D0",
    borderBottomWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
  },
  s3: {
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 10,
    width: 10,
  },
  s4: {
    flex: 1,
  },
  s5: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 20,
  },
  s6: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    flexDirection: "row",
    justifyContent: "center",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  s7: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  s8: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s9: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 16,
    borderWidth: 1,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    width: "100%",
  },
  s10: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
  },
  s11: {
    alignItems: "center",
    backgroundColor: "#7C3AED",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s12: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "left",
  },
  s13: {
    alignItems: "center",
    backgroundColor: "#0EA5A4",
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s14: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
    textAlign: "left",
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  s16: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  s17: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "left",
  },
  s18: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s19: {
    color: "#0F1B2A",
    fontFamily: "RobotoMono_500Medium",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
  },
  s20: {
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderRadius: 10,
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
  },
  s21: {
    color: "#991B1B",
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "left",
  },
  s22: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  s23: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "left",
  },
  s24: {
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s25: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
});
