// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Anim } from '@/proto/theme/anim';
import { AppHeader } from '@/proto/components/AppHeader';
import { TabBar } from '@/proto/components/TabBar';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenC2_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title="Offers" sub="Visible to 12 operators near Laverton" showBack={true} onBack={v.back} rightHelp={true} onRight={v.open_C2_M1} />
      <View style={s.s2}>
        <Anim name="pulseDot" duration={2000} loop style={s.s3} />
        <View style={s.s4}>
          <Text style={s.s5}>Looking for work since 08:12</Text>
        </View>
      </View>
      <View style={s.s6}>
        <Svg width={46} height={46} viewBox="0 0 24 24" fill="none" stroke="#94A3B8" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round">
          <Path d="M20 10.5c0 5.4-8 11-8 11s-8-5.6-8-11a8 8 0 0 1 16 0z" />
          <Circle cx="12" cy="10.5" r="2.6" />
        </Svg>
        <Text style={s.s7}>
          No offers yet
        </Text>
        <Text style={s.s8}>
          You are visible. Operators inside 75 km can see your verified file and will offer work when they need a driver.
        </Text>
        <Pressable onPress={v.open_C2_M1} style={s.s9}>
          <Text style={s.s10}>Widen the radius</Text>
        </Pressable>
      </View>
      <TabBar active="run" onRun={v.tabRun} onNav={v.tab_A6} onComp={v.tab_A25} onMsg={v.tab_A22} onProf={v.tab_A34} />
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    alignItems: "center",
    backgroundColor: "#ECFDF3",
    borderBottomColor: "#BBF7D0",
    borderBottomWidth: 1,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
  },
  s3: {
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexGrow: 0,
    flexShrink: 0,
    height: 10,
    width: 10,
  },
  s4: {
    flex: 1,
  },
  s5: {
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 20,
  },
  s6: {
    alignItems: "center",
    flex: 1,
    flexDirection: "column",
    gap: 12,
    justifyContent: "center",
    paddingBottom: 32,
    paddingLeft: 32,
    paddingRight: 32,
    paddingTop: 32,
  },
  s7: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 22,
    lineHeight: 26,
    textAlign: "center",
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  s9: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 48,
    justifyContent: "center",
    marginTop: 8,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 0,
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 15,
    textAlign: "center",
  },
});
