// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenC3() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title={v.offerOp} sub={v.offerKind} showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <Text style={s.s5}>
            Rate offered
          </Text>
          <Text style={s.s6}>
            {v.offerRate}
          </Text>
          <Text style={s.s7}>
            Paid weekly, penalty rates after 10 hours
          </Text>
        </View>
        <View style={s.s8}>
          <View style={s.s9}>
            <View style={s.s10}>
              <Text style={s.s11}>When</Text>
            </View>
            <Text style={s.s12}>
              {v.offerWhen}
            </Text>
          </View>
          <View style={s.s9}>
            <View style={s.s10}>
              <Text style={s.s11}>Route</Text>
            </View>
            <Text style={s.s12}>
              {v.offerRoute}
            </Text>
          </View>
          <View style={s.s9}>
            <View style={s.s10}>
              <Text style={s.s11}>Vehicle</Text>
            </View>
            <Text style={s.s12}>
              {v.offerVehicle}
            </Text>
          </View>
          <View style={s.s13}>
            <View style={s.s10}>
              <Text style={s.s11}>Depot</Text>
            </View>
            <Text style={s.s12}>
              {v.offerDist}
            </Text>
          </View>
        </View>
        <View style={s.s14}>
          <Text style={s.s15}>
            What they need from you
          </Text>
          <View style={s.s16}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
            <View style={s.s2}>
              <Text style={s.s17}>MC licence</Text>
            </View>
            <Text style={s.s18}>
              Matched
            </Text>
          </View>
          <View style={s.s19}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
            <View style={s.s2}>
              <Text style={s.s17}>Fatigue accreditation, BFM</Text>
            </View>
            <Text style={s.s18}>
              Verified
            </Text>
          </View>
          <View style={s.s20}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="2.2" strokeLinecap="round">
              <Circle cx="12" cy="12" r="9" />
              <Path d="M12 7.5V12l3 2" />
            </Svg>
            <View style={s.s2}>
              <Text style={s.s17}>Their site induction</Text>
            </View>
            <Text style={s.s21}>
              Sent after you accept
            </Text>
          </View>
        </View>
        <Pressable onPress={v.acceptOffer} style={s.s22}>
          <Text style={s.s23}>Accept this work</Text>
        </Pressable>
        <Pressable onPress={v.open_C3_M1} style={s.s24}>
          <Text style={s.s25}>Not this one</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    backgroundColor: "#0E2033",
    borderRadius: 16,
    flexShrink: 0,
    paddingBottom: 18,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 18,
  },
  s5: {
    color: "rgba(255,255,255,.55)",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 1,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s6: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 34,
    lineHeight: 38,
    marginTop: 4,
  },
  s7: {
    color: "rgba(255,255,255,.62)",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 4,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 4,
  },
  s9: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 16,
    justifyContent: "space-between",
    minHeight: 52,
  },
  s10: {
    flexGrow: 0,
    flexShrink: 0,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 20,
  },
  s12: {
    color: "#0F1B2A",
    fontFamily: "Inter_500Medium",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "right",
  },
  s13: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
    justifyContent: "space-between",
    minHeight: 52,
  },
  s14: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s16: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
    minHeight: 48,
  },
  s17: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s18: {
    color: "#166534",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
  },
  s19: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
  },
  s20: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
  },
  s21: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
  },
  s22: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s23: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s24: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s25: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
