// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppHeader } from '@/proto/components/AppHeader';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenC3_S1() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { height: insets.top }]} />
      <AppHeader title={v.offerOp} sub={v.offerKind} showBack={true} onBack={v.back} />
      <ScrollView style={s.s2} contentContainerStyle={s.s3} showsVerticalScrollIndicator={false}>
        <View style={s.s4}>
          <View style={s.s5}>
            <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.8" strokeLinecap="round">
              <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
            </Svg>
          </View>
          <View style={s.s2}>
            <Text style={s.s6}>
              You cannot accept this yet
            </Text>
            <Text style={s.s7}>
              {v.offerBlock}
            </Text>
          </View>
        </View>
        <View style={s.s8}>
          <View style={s.s9}>
            <Text style={s.s10}>
              {v.offerRate}
            </Text>
            <Text style={s.s11}>
              {v.offerDist}
            </Text>
          </View>
          <Text style={s.s12}>
            {v.offerWhen} · {v.offerRoute}
          </Text>
          <Text style={s.s13}>
            {v.offerVehicle}
          </Text>
        </View>
        <View style={s.s14}>
          <Text style={s.s15}>
            What they need from you
          </Text>
          <View style={s.s16}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
              <Path d="M5 12.5l4.5 4.5L19 7" />
            </Svg>
            <View style={s.s2}>
              <Text style={s.s17}>MC licence</Text>
            </View>
            <Text style={s.s18}>
              Matched
            </Text>
          </View>
          <View style={s.s19}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#DC2626" strokeWidth="2.6" strokeLinecap="round">
              <Path d="M6.5 6.5l11 11M17.5 6.5l-11 11" />
            </Svg>
            <View style={s.s2}>
              <Text style={s.s17}>Dangerous goods licence</Text>
            </View>
            <Text style={s.s20}>
              Expired 2 July
            </Text>
          </View>
          <View style={s.s21}>
            <Svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#5B6B7F" strokeWidth="2.2" strokeLinecap="round">
              <Circle cx="12" cy="12" r="9" />
              <Path d="M12 7.5V12l3 2" />
            </Svg>
            <View style={s.s2}>
              <Text style={s.s17}>Tanker safety induction</Text>
            </View>
            <Text style={s.s22}>
              Not supplied
            </Text>
          </View>
        </View>
        <View style={s.s23}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.8" strokeLinecap="round">
            <Circle cx="12" cy="12" r="9" />
            <Path d="M12 11v5" />
            <Path d="M12 8h.01" />
          </Svg>
          <Text style={s.s24}>
            Barwon Fuel Haulage can see that something is missing, but not which document. Fix it and the offer reopens for 48 hours.
          </Text>
        </View>
        <Pressable onPress={v.push_B3_S2} style={s.s25}>
          <Text style={s.s26}>Fix my dangerous goods licence</Text>
        </Pressable>
        <Pressable onPress={v.open_C3_M1} style={s.s27}>
          <Text style={s.s28}>Not interested anyway</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#FFFFFF",
    flexGrow: 0,
    flexShrink: 0,
  },
  s2: {
    flex: 1,
  },
  s3: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s4: {
    alignItems: "flex-start",
    backgroundColor: "#FEF2F2",
    borderColor: "#FCA5A5",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    gap: 14,
    paddingBottom: 18,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 18,
  },
  s5: {
    alignItems: "center",
    backgroundColor: "#DC2626",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  s6: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 20,
    lineHeight: 24,
  },
  s7: {
    color: "#991B1B",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  s8: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    opacity: 0.7,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s9: {
    alignItems: "baseline",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  s10: {
    color: "#0F1B2A",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 26,
    lineHeight: 30,
  },
  s11: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s12: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  s13: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  s14: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s16: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
    minHeight: 48,
  },
  s17: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  s18: {
    color: "#166534",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
  },
  s19: {
    alignItems: "center",
    borderBottomColor: "#E2E8F0",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
  },
  s20: {
    color: "#991B1B",
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 16,
  },
  s21: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
  },
  s22: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
  },
  s23: {
    alignItems: "flex-start",
    backgroundColor: "#EEF3F9",
    borderRadius: 12,
    flexDirection: "row",
    flexShrink: 0,
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s24: {
    color: "#0F1B2A",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s25: {
    alignItems: "center",
    backgroundColor: "#DC2626",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s26: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s27: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s28: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
