// Generated by tools/prototype/generate.mjs — do not edit by hand.
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useVals } from '@/proto/runtime/vals';

export default function ScreenC4() {
  const v = useVals();
  const insets = useSafeAreaInsets();
  return (
    <View style={s.s0}>
      <View style={[s.s1, { paddingTop: insets.top }]}>
        <View style={s.s2}>
          <Svg width={26} height={26} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
            <Path d="M5 12.5l4.5 4.5L19 7" />
          </Svg>
        </View>
        <Text style={s.s3}>
          Work accepted
        </Text>
        <Text style={s.s4}>
          {v.offerOp} · {v.offerWhen}
        </Text>
      </View>
      <ScrollView style={s.s5} contentContainerStyle={s.s6} showsVerticalScrollIndicator={false}>
        <View style={s.s7}>
          <Text style={s.s8}>
            What happens now
          </Text>
          <View style={s.s9}>
            <View style={s.s10}>
              <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M5 12.5l4.5 4.5L19 7" />
              </Svg>
            </View>
            <View style={s.s5}>
              <Text style={s.s11}>
                Added as a casual operator
              </Text>
              <Text style={s.s12}>
                They appear on your company screen from now on.
              </Text>
            </View>
          </View>
          <View style={s.s13}>
            <View style={s.s10}>
              <Svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round">
                <Path d="M5 12.5l4.5 4.5L19 7" />
              </Svg>
            </View>
            <View style={s.s5}>
              <Text style={s.s11}>
                Your verified file was shared
              </Text>
              <Text style={s.s12}>
                Licence, medical and fatigue accreditation only.
              </Text>
            </View>
          </View>
          <View style={s.s13}>
            <View style={s.s14} />
            <View style={s.s5}>
              <Text style={s.s15}>
                Site induction arrives by message
              </Text>
              <Text style={s.s12}>
                Read it before your first shift.
              </Text>
            </View>
          </View>
        </View>
        <View style={s.s16}>
          <Svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="#B45309" strokeWidth="1.8" strokeLinecap="round">
            <Circle cx="12" cy="12" r="9" />
            <Path d="M12 7.5V12l3 2" />
          </Svg>
          <Text style={s.s17}>
            These shifts count towards your fatigue hours across every operator, not just this one.
          </Text>
        </View>
        <Pressable onPress={v.push_A34_M1} style={s.s18}>
          <Text style={s.s19}>See my companies</Text>
        </Pressable>
        <Pressable onPress={v.acceptedDone} style={s.s20}>
          <Text style={s.s21}>Done</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  s0: {
    backgroundColor: "#F4F6FA",
    flex: 1,
    flexDirection: "column",
  },
  s1: {
    backgroundColor: "#16A34A",
    flexGrow: 0,
    flexShrink: 0,
    paddingBottom: 24,
    paddingLeft: 20,
    paddingRight: 20,
  },
  s2: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,.2)",
    borderRadius: 999,
    flexDirection: "row",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  s3: {
    color: "#FFFFFF",
    fontFamily: "BarlowSemiCondensed_700Bold",
    fontSize: 30,
    lineHeight: 34,
    marginTop: 14,
  },
  s4: {
    color: "rgba(255,255,255,.86)",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 2,
  },
  s5: {
    flex: 1,
  },
  s6: {
    flexDirection: "column",
    flexGrow: 1,
    gap: 14,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  s7: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    boxShadow: "0 1px 2px rgba(15,27,42,.06),0 4px 12px rgba(15,27,42,.05)",
    flexShrink: 0,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  s8: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.88,
    lineHeight: 14,
    textTransform: "uppercase",
  },
  s9: {
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
  },
  s10: {
    alignItems: "center",
    backgroundColor: "#16A34A",
    borderRadius: 999,
    flexDirection: "row",
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  s11: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s12: {
    color: "#5B6B7F",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s13: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  s14: {
    borderColor: "#E2E8F0",
    borderRadius: 999,
    borderWidth: 2,
    flexGrow: 0,
    flexShrink: 0,
    height: 24,
    width: 24,
  },
  s15: {
    color: "#5B6B7F",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 20,
  },
  s16: {
    alignItems: "flex-start",
    backgroundColor: "#FEF6E9",
    borderRadius: 12,
    flexDirection: "row",
    flexShrink: 0,
    gap: 10,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
  },
  s17: {
    color: "#B45309",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 18,
  },
  s18: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s19: {
    color: "#0F1B2A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
  s20: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    borderWidth: 0,
    flexDirection: "row",
    flexShrink: 0,
    height: 56,
    justifyContent: "center",
    width: "100%",
  },
  s21: {
    color: "#fff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    lineHeight: 16,
    textAlign: "center",
  },
});
