export type ScreenKind = "screen" | "modal" | "state";
export interface ScreenDefinition {
  id: string;
  title: string;
  module: string;
  kind: ScreenKind;
}
const s = (id: string, title: string, module: string): ScreenDefinition => ({
  id,
  title,
  module,
  kind: id.includes(".M") ? "modal" : id.includes(".S") ? "state" : "screen",
});

export const screens: ScreenDefinition[] = [
  s("A1", "Splash and brand launch", "Access"),
  s("A1.S1", "Update required", "Access"),
  s("A2", "Driver sign in", "Access"),
  s("A37", "Create an account", "Access"),
  s("A38", "Your file", "Access"),
  s("A38.C", "My compliance", "Access"),
  s("A38.S", "Share my file", "Access"),
  s("A38.L", "Heavy vehicle licence", "Access"),
  s("A38.M", "NHVR medical certificate", "Access"),
  s("A38.F", "Fatigue accreditation", "Access"),
  s("A38.D", "Dangerous goods licence", "Access"),
  s("A38.V", "Work rights, VEVO check", "Access"),
  s("A38.T", "Tanker safety induction", "Access"),
  s("A2.M1", "Forgot password", "Access"),
  s("A2.M2", "Reset link sent", "Access"),
  s("A2.S1", "Wrong credentials", "Access"),
  s("A2.S2", "No connection at sign in", "Access"),
  s("A26", "Company for today", "Access"),
  s("A26.A", "Add a company", "Access"),
  s("A26.L", "Company linked", "Access"),
  s("A26.LI", "Invitation accepted", "Access"),
  s("A26.S1", "Single company, auto continue", "Access"),
  s("A26.S2", "Pending invitation", "Access"),
  s("A26.M1", "What does this mean", "Access"),
  s("A35", "Permissions primer", "Access"),
  s("A35.M1", "Location permission dialogue", "Access"),
  s("A35.S1", "Permission denied recovery", "Access"),
  s("A36", "First run profile setup", "Access"),
  s("A27", "Driver dashboard, clocked off", "Dashboard"),
  s("A27.M1", "Clock on confirmation", "Dashboard"),
  s("A27.S1", "Clocked on, shift running", "Dashboard"),
  s("A27.S2", "On break", "Dashboard"),
  s("A27.S3", "No work allocated", "Dashboard"),
  s("A27.M2", "Clock off with shift summary", "Dashboard"),
  s("A27.M3", "Availability explainer", "Dashboard"),
  s("A27.M4", "Company switcher", "Dashboard"),
  s("A27.M5", "Cannot switch while clocked on", "Dashboard"),
  s("A3", "Start shift gate", "Dashboard"),
  s("A33", "Shift summary and clock off", "Dashboard"),
  s("A16", "Fit for duty declaration", "Compliance"),
  s("A16.M1", "Question help", "Compliance"),
  s("A32", "Declaration photo capture", "Compliance"),
  s("A32.M1", "Retake or use photo", "Compliance"),
  s("A32.S1", "Camera permission denied", "Compliance"),
  s("A16.S1", "Pass, gate cleared", "Compliance"),
  s("A16.S2", "Fail, shift blocked", "Compliance"),
  s("A16.M2", "Notify allocator", "Compliance"),
  s("A16.S3", "Submitted offline, queued", "Compliance"),
  s("A14", "Electronic pre start inspection", "Compliance"),
  s("A14.M1", "Vehicle and trailer selector", "Compliance"),
  s("A14.M2", "Check item detail, pass", "Compliance"),
  s("A14.M3", "Check item detail, fail", "Compliance"),
  s("A14.M4", "Camera capture for defect", "Compliance"),
  s("A14.M5", "Severity selector", "Compliance"),
  s("A14.S1", "Summary and sign off", "Compliance"),
  s("A14.S2", "Blocking defect, vehicle locked out", "Compliance"),
  s("A14.S3", "Tanker checklist", "Compliance"),
  s("A15", "Defect reporting", "Compliance"),
  s("A15.M1", "Add photograph", "Compliance"),
  s("A15.M2", "Work order raised", "Compliance"),
  s("A28", "How are you starting work", "Run"),
  s("A29", "Unscheduled work start", "Run"),
  s("A29.M1", "Reason selector", "Run"),
  s("A29.M2", "Location confirmation", "Run"),
  s("A29.S1", "Offline, location queued", "Run"),
  s("A4", "Digital run sheet", "Run"),
  s("A4.M1", "Stop actions", "Run"),
  s("A4.S1", "No run allocated", "Run"),
  s("A4.S2", "Run sheet offline", "Run"),
  s("A4.S3", "Fourteen stop run", "Run"),
  s("A30", "Create job", "Run"),
  s("A30.M1", "Address search", "Run"),
  s("A30.M2", "Use my location", "Run"),
  s("A30.S1", "Job saved", "Run"),
  s("A7", "Multi drop sequencing", "Run"),
  s("A7.M1", "Accept optimised order", "Run"),
  s("A6", "HV aware navigation", "Run"),
  s("A6.M1", "Route restriction warning", "Run"),
  s("A6.M2", "Reroute options", "Run"),
  s("A18", "Live GPS tracking and ETA", "Run"),
  s("A5", "Job detail", "Jobs"),
  s("A5.M1", "Job pre check expanded", "Jobs"),
  s("A5.M2", "Call site contact", "Jobs"),
  s("A5.M3", "Job documents", "Jobs"),
  s("A31", "Job comments and handover", "Jobs"),
  s("A31.M1", "Comment composer", "Jobs"),
  s("A31.S1", "No comments yet", "Jobs"),
  s("A8", "One tap job status", "Jobs"),
  s("A8.M1", "Status confirmation", "Jobs"),
  s("A8.S1", "Status queued offline", "Jobs"),
  s("A10", "Consignment and pallet scanning", "Jobs"),
  s("A10.M1", "Duplicate pallet scan", "Jobs"),
  s("A10.M2", "Manual pallet entry", "Jobs"),
  s("A9", "Electronic proof of delivery", "Jobs"),
  s("A9.M1", "Signature pad", "Jobs"),
  s("A9.M2", "Photograph of goods", "Jobs"),
  s("A9.M3", "Closing comment", "Jobs"),
  s("A9.S1", "Proof queued offline", "Jobs"),
  s("A11", "Unsuccessful delivery", "Jobs"),
  s("A11.M1", "Reason code selector", "Jobs"),
  s("A11.M2", "Photograph evidence", "Jobs"),
  s("A12", "Fatigue assistant", "Records"),
  s("A12.M1", "Break due reminder", "Records"),
  s("A12.M2", "Breach warning", "Records"),
  s("A13", "Electronic work diary", "Records"),
  s("A13.M1", "Change duty status", "Records"),
  s("A13.M2", "Correction request", "Records"),
  s("A21", "Timesheet and rest break", "Records"),
  s("A21.M1", "Start break", "Records"),
  s("A21.M2", "End break", "Records"),
  s("A17", "Safety incident report", "Records"),
  s("A17.M1", "Incident type selector", "Records"),
  s("A17.M2", "Photograph and witness", "Records"),
  s("A17.S1", "Incident submitted", "Records"),
  s("A19", "Fuel and fuel tax credit", "Records"),
  s("A19.M1", "Add a fuel fill", "Records"),
  s("A19.M2", "Receipt capture", "Records"),
  s("A20", "Odometer and engine hours", "Records"),
  s("A20.M1", "Telematics auto fill", "Records"),
  s("A20.M2", "Manual override", "Records"),
  s("A22", "Dispatch messaging", "Records"),
  s("A22.M1", "New message", "Records"),
  s("A22.S1", "Unread messages", "Records"),
  s("A23", "Document wallet", "Records"),
  s("A23.M1", "Document viewer", "Records"),
  s("A23.S1", "Document expiring soon", "Records"),
  s("A24", "Offline sync", "Records"),
  s("A24.M1", "Sync queue detail", "Records"),
  s("A25", "Accreditation wallet", "Records"),
  s("A25.M1", "Licence detail", "Records"),
  s("A25.S1", "Accreditation expiry alert", "Records"),
  s("A34", "Profile and settings", "Profile"),
  s("A34.M1", "My companies", "Profile"),
  s("A34.M2", "Notification preferences", "Profile"),
  s("A34.M3", "Sign out confirmation", "Profile"),
];

export const screenById = new Map(screens.map((item) => [item.id, item]));
export const modules = [...new Set(screens.map((item) => item.module))];
